(function(g){var window=this;'use strict';var Li=function(c){c.publish("cardstatechange",c.ag()&&c.l2()?1:0)},Gk=function(c,A){var J=g.Ae(A),q=J?A:arguments;
for(J=J?0:1;J<q.length;J++){if(c==null)return;c=c[q[J]]}return c},ciN=function(c){var A=g.tI(c);
c=g.eL(c);return new g.QZ(A.x,A.y,c.width,c.height)},Ai9=function(c,A,J){var q=q===void 0?{}:q;
var Y;return Y=g.Wt(c,A,function(){g.LX(Y);J.apply(c,arguments)},q)},Fp=function(c){c=g.YH(c);
delete Ci[c];g.cL(Ci)&&M1&&M1.stop()},qlR=function(){M1||(M1=new g.hN(function(){Jir()},20));
var c=M1;c.isActive()||c.start()},Jir=function(){var c=g.d9();
g.lC(Ci,function(A){YlO(A,c)});
g.cL(Ci)||qlR()},v8=function(c,A,J,q){g.rc.call(this);
if(!Array.isArray(c)||!Array.isArray(A))throw Error("Start and end parameters must be arrays");if(c.length!=A.length)throw Error("Start and end points must be the same length");this.K=c;this.D=A;this.duration=J;this.U=q;this.coords=[];this.progress=this.Y=0;this.T=null},YlO=function(c,A){A<c.startTime&&(c.endTime=A+c.endTime-c.startTime,c.startTime=A);
c.progress=(A-c.startTime)/(c.endTime-c.startTime);c.progress>1&&(c.progress=1);c.Y=1E3/(A-c.T);c.T=A;ppM(c,c.progress);c.progress==1?(c.C=0,Fp(c),c.onFinish(),c.Dq()):c.isPlaying()&&c.U1()},ppM=function(c,A){typeof c.U==="function"&&(A=c.U(A));
c.coords=Array(c.K.length);for(var J=0;J<c.K.length;J++)c.coords[J]=(c.D[J]-c.K[J])*A+c.K[J]},mVM=function(c,A){g.KA.call(this,c);
this.coords=A.coords;this.x=A.coords[0];this.y=A.coords[1];this.z=A.coords[2];this.duration=A.duration;this.progress=A.progress;this.fps=A.Y;this.state=A.C},Q$=function(c,A,J,q,Y){v8.call(this,A,J,q,Y);
this.element=c},jIJ=function(c,A,J,q,Y){if(A.length!=2||J.length!=2)throw Error("Start and end points must be 2D");
Q$.call(this,c,A,J,q,Y)},dVM=function(c){return Math.pow(c,3)},EDJ=function(c){return 3*c*c-2*c*c*c},OlV=function(c){g.P.call(this);
this.K=c||window;this.C=[]},Xp=function(c){return c.baseUrl||null},Zs=function(c,A){return g.IR(g.il(c,A),function(J){return!!J})},TOO=function(c,A,J){function q(pI){var cw=pI.hovercardButton;
if(!cw)return null;cw=cw.subscribeButtonRenderer;if(!cw)return null;var EL=p(cw.unsubscribedButtonText),h=p(cw.subscribedButtonText);if(cw.subscribed){var wa=p(cw.subscriberCountWithUnsubscribeText);var M8=p(cw.subscriberCountText)}else wa=p(cw.subscriberCountText),M8=p(cw.subscriberCountWithSubscribeText);var b$=null;if(pI.signinEndpoint){b$=Gk(pI,"signinEndpoint","webNavigationEndpointData","url");if(!b$){var Gw,OO;b$=(OO=g.l((Gw=cw.signInEndpoint)==null?void 0:Gw.commandMetadata,g.gV))==null?void 0:
OO.url}if(!b$)return null}return EL&&(h||b$)?{subscribed:cw.subscribed,subscribeText:EL,subscribeCount:wa,unsubscribeText:h,unsubscribeCount:M8,enabled:cw.enabled,signinUrl:b$,classic:pI.useClassicSubscribeButton}:null}
function Y(pI){if(pI){var cw=[],EL=pI.videoId;EL&&cw.push("v="+EL);(EL=pI.playlistId)&&cw.push("list="+EL);(pI=pI.startTimeSeconds)&&cw.push("t="+pI);return"/watch?"+cw.join("&")}}
function p(pI){if(!pI)return null;var cw=pI.simpleText;return cw?cw:pI.runs?g.il(pI.runs,function(EL){return EL.text}).join(""):null}
A=A.endscreenElementRenderer;if(!A)return null;var m=A.style,E=A.endpoint||{},O=null,T=null,R=!1,r=null,H=null,V=null,N=null,w=!1,W=null,C=null,G=null,Z=null,I=null,f=null;if(m==="VIDEO")g.l(E,g.UP)?O=g.l(E,g.UP).url:(f=g.l(E,g.J8),O=Y(f)),T=!1,r=c,A.thumbnailOverlays?(R=A.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,H=p(R.text),R=R.style==="LIVE"):H=p(A.videoDuration);else if(m==="PLAYLIST")g.l(E,g.UP)?O=g.l(E,g.UP).url:(f=g.l(E,g.J8),O=Y(f)),T=!1,r=c,V=p(A.playlistLength);else if(m===
"CHANNEL"){if(w=Gk(E,"browseEndpoint","browseId"))N=w,O="/channel/"+N;T=!1;r="new";(w=!!A.isSubscribe)?W=q(A):C=p(A.subscribersText)}else m==="WEBSITE"?((G=Gk(E,"urlEndpoint","url"))&&(O=G),T=!0,r="new",G=A.icon.thumbnails[0].url):m==="CREATOR_MERCHANDISE"&&(A.productPrice&&(Z=p(A.productPrice)),A.additionalFeesText&&(I=p(A.additionalFeesText)),(T=Gk(E,"urlEndpoint","url"))&&(O=T),T=!0,r="new");c=Gk(A,"title","accessibility","accessibilityData","label");var K=A.endpoint?A.endpoint.clickTrackingParams:
null,y="";if(A.metadata){var q8=p(A.metadata);q8&&(y=q8)}return{id:"element-"+J,type:m,title:p(A.title),metadata:y,callToAction:p(A.callToAction),vO:A.image,iconUrl:G,left:Number(A.left),width:Number(A.width),top:Number(A.top),aspectRatio:Number(A.aspectRatio),startMs:Math.floor(Number(A.startMs)),endMs:Math.floor(Number(A.endMs)),videoDuration:H,f_:R,playlistLength:V,channelId:N,subscribeButton:W,subscribersText:C,isSubscribe:w,targetUrl:O||null,NA:T,sessionData:K?{itct:K}:null,DzD:r,ZB:c?c:null,
isPlaceholder:A.isPlaceholder,impressionUrls:Zs(A.impressionUrls||[],Xp),U4:Zs(A.hovercardShowUrls||[],Xp),clickUrls:Zs(E.loggingUrls||[],Xp),visualElement:g.WQ(A.trackingParams),productPrice:Z,additionalFeesText:I,watchEndpoint:f||null}},RqH=function(c,A){var J={startMs:Math.floor(Number(c.startMs)),
impressionUrls:Zs(c.impressionUrls||[],Xp),elements:Zs(c.elements||[],function(q,Y){return TOO(A,q,Y)})};
c.trackingParams&&(J.visualElement=g.WQ(c.trackingParams));return J},riw=function(c){g.V5.call(this,c);
this.T=this.endscreen=null;this.K={};this.Y={};this.U=this.j=null;this.X=[];this.C=null;this.CJ=!0;this.D=0;c=c.B();this.L=g.xZ(c)||g.sE(c);this.events=new g.sM(this);g.U(this,this.events);this.events.Z(this.player,g.jo("creatorendscreen"),this.onCueRangeEnter);this.events.Z(this.player,g.dP("creatorendscreen"),this.onCueRangeExit);this.events.Z(this.player,"resize",this.RJ);this.events.Z(window,"focus",this.mfT);this.load();var A=g.AH("STYLE");(g.tv("HEAD")[0]||document.body).appendChild(A);this.addOnDisposeCallback(function(){g.mf(A)});
A.sheet&&(A.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),A.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},Hli=function(c){return c.player.getVideoData().Nq?"current":c.L?"new":"current"},IJ=function(c){return c.player.B().playerStyle==="creator-endscreen-editor"},V_H=function(c){var A=c.player.getVideoData(),J=A.videoId;
c.T&&c.T.abort();J={method:"POST",onFinish:function(Y){var p=c.T=null;Y.status===200&&(Y=Y.responseText,Y.substring(0,3)===")]}"&&(Y=Y.substring(3),p=JSON.parse(Y),p=RqH(p,Hli(c))));zk(c,p)},
urlParams:{v:J},withCredentials:!0};c.L&&(J.urlParams.ptype="embedded");var q=A.pk;q&&(J.postParams={ad_tracking:q});if(A=g.wZM(A))if(A=g.nc(A),A=g.tp(A))c.T=g.C2(A,J)},zk=function(c,A,J){J=J===void 0?!0:J;
c.player.hm("creatorendscreen");c.j&&(c.j.dispose(),c.j=null,c.U.dispose(),c.U=null);for(var q=g.u(Object.values(c.K)),Y=q.next();!Y.done;Y=q.next())Y.value.dispose();c.K={};c.Y={};c.X.length>0&&(c.X.forEach(function(E){E.dispose()}),c.X.length=0);
c.C&&(g.Ot(c.C,"ytp-ce-element-show"),c.C.setAttribute("aria-hidden","true"));c.D=0;if((c.endscreen=A)&&A.elements){J&&NOH(c);J=[];q=new g.p$(A.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});J.push(q);c.player.B().K||(c.j=new g.t({S:"div",V:"ytp-ce-shadow"}),g.Sx(c.player,c.j.element,4),c.U=new g.pk(c.j,200));for(q=0;q<A.elements.length;++q){Y=A.elements[q];var p=DVR(c,Y);if(p){c.K[Y.id]=p;c.Y[Y.id]=Y;g.Sx(c.player,p.element,4);var m=new g.p$(Y.startMs,Y.endMs,{id:"ytp-ce-element-"+
Y.id,namespace:"creatorendscreen"});J.push(m);kJR(c,p,Y)}else g.Sv(new g.eq("buildEndscreenElement null",Y))}c.player.Lo(J);c.RJ()}},NOH=function(c){var A=g.Gg(),J=g.CK();
J&&A&&c.endscreen.visualElement&&g.c9(g.KK)(void 0,J,A,c.endscreen.visualElement)},DVR=function(c,A){var J=null;
switch(A.type){case "VIDEO":c={S:"div",QP:["ytp-ce-element","ytp-ce-video"],G:{tabindex:"0","aria-label":A.ZB||"","aria-hidden":"true"},N:[{S:"div",V:"ytp-ce-element-shadow"},{S:"div",V:"ytp-ce-covering-image",G:SX(A)},{S:"div",V:"ytp-ce-covering-shadow-top"},{S:"a",V:"ytp-ce-covering-overlay",G:{href:x$(c,A.targetUrl),tabindex:"-1"},N:[{S:"div",QP:["ytp-ce-video-title","ytp-webkit-ellipsis"],G:{dir:g.ki(A.title||"")},KJ:A.title},{S:"div",V:A.f_?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
KJ:A.videoDuration||void 0}]}]};J=new g.t(c);break;case "PLAYLIST":c={S:"div",QP:["ytp-ce-element","ytp-ce-playlist"],G:{tabindex:"0","aria-label":A.ZB||"","aria-hidden":"true"},N:[{S:"div",V:"ytp-ce-element-shadow"},{S:"div",V:"ytp-ce-covering-image",G:SX(A)},{S:"div",V:"ytp-ce-covering-shadow-top"},{S:"a",V:"ytp-ce-covering-overlay",G:{href:x$(c,A.targetUrl),tabindex:"-1"},N:[{S:"div",QP:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],G:{dir:g.ki(A.title||"")},KJ:A.title},{S:"div",V:"ytp-ce-playlist-count",
N:[{S:"div",V:"ytp-ce-playlist-icon"},{S:"div",V:"ytp-ce-playlist-count-text",KJ:A.playlistLength||void 0}]}]}]};J=new g.t(c);break;case "CHANNEL":J={S:"div",QP:["ytp-ce-element","ytp-ce-channel",A.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],G:{tabindex:"0","aria-label":A.ZB||"","aria-hidden":"true"},N:[{S:"div",V:"ytp-ce-element-shadow"},{S:"div",V:"ytp-ce-expanding-overlay",N:[{S:"div",V:"ytp-ce-expanding-overlay-hider"},{S:"div",V:"ytp-ce-expanding-overlay-background"},{S:"div",V:"ytp-ce-expanding-overlay-content",
N:[{S:"div",V:"ytp-ce-expanding-overlay-body",N:[{S:"div",V:"ytp-ce-expanding-overlay-body-padding",N:[{S:"a",QP:["ytp-ce-channel-title","ytp-ce-link"],G:{href:x$(c,A.targetUrl),target:"_blank",tabindex:"-1",dir:g.ki(A.title||"")},KJ:A.title},A.subscribeButton?{S:"div",V:"ytp-ce-subscribe-container",N:[{S:"div",V:"ytp-ce-channel-subscribe"}]}:"",A.subscribersText?{S:"div",V:"ytp-ce-channel-subscribers-text",KJ:A.subscribersText}:"",A.metadata?{S:"div",QP:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],KJ:A.metadata}:""]}]}]}]},{S:"div",V:"ytp-ce-expanding-image",G:SX(A)}]};J=new g.t(J);var q=g.yy(document,"div","ytp-ce-channel-subscribe",J.element)[0];if(A.subscribeButton&&A.channelId){g.dc(q,"ytp-ce-subscribe-button");if(c.player.B().K){var Y=null;var p=A.sessionData.itct}else Y="endscreen",p=null;Y=new g.nZ(A.subscribeButton.subscribeText,A.subscribeButton.subscribeCount,A.subscribeButton.unsubscribeText,A.subscribeButton.unsubscribeCount,!!A.subscribeButton.enabled,!!A.subscribeButton.classic,
A.channelId,!!A.subscribeButton.subscribed,Y,p,c.player,!1);q.appendChild(Y.element);c.X.push(Y)}break;case "WEBSITE":c={S:"div",QP:["ytp-ce-element","ytp-ce-website"],G:{tabindex:"0","aria-label":A.ZB||"","aria-hidden":"true"},N:[{S:"div",V:"ytp-ce-element-shadow"},{S:"div",V:"ytp-ce-expanding-overlay",N:[{S:"div",V:"ytp-ce-expanding-overlay-hider"},{S:"div",V:"ytp-ce-expanding-overlay-background"},{S:"div",V:"ytp-ce-expanding-overlay-content",N:[{S:"div",V:"ytp-ce-expanding-overlay-body",N:[{S:"div",
V:"ytp-ce-expanding-overlay-body-padding",N:[{S:"div",V:"ytp-ce-website-title",G:{dir:g.ki(A.title||"")},KJ:A.title},{S:"div",V:"ytp-ce-website-metadata",KJ:A.metadata},{S:"a",QP:["ytp-ce-website-goto","ytp-ce-link"],G:{href:x$(c,A.targetUrl),target:"_blank",tabindex:"-1"},KJ:A.callToAction}]}]}]}]},{S:"div",V:"ytp-ce-expanding-image",G:SX(A)},{S:"div",V:"ytp-ce-expanding-icon",G:gDC(A.iconUrl)}]};J=new g.t(c);break;case "CREATOR_MERCHANDISE":J="",A.productPrice&&(J={S:"div",V:"ytp-ce-merchandise-price-container",
N:[{S:"div",V:"ytp-ce-merchandise-price",KJ:A.productPrice}]},A.additionalFeesText&&J.N.push({S:"div",V:"ytp-ce-merchandise-additional-fees",KJ:A.additionalFeesText})),c={S:"div",QP:["ytp-ce-element","ytp-ce-merchandise"],G:{tabindex:"0","aria-label":A.ZB||"","aria-hidden":"true"},N:[{S:"div",V:"ytp-ce-element-shadow"},{S:"div",V:"ytp-ce-expanding-overlay",N:[{S:"div",V:"ytp-ce-expanding-overlay-hider"},{S:"div",V:"ytp-ce-expanding-overlay-background"},{S:"div",V:"ytp-ce-expanding-overlay-content",
N:[{S:"div",V:"ytp-ce-expanding-overlay-body",N:[{S:"div",V:"ytp-ce-expanding-overlay-body-padding",N:[{S:"div",V:"ytp-ce-merchandise-title",G:{dir:g.ki(A.title||"")},KJ:A.title},J,{S:"div",V:"ytp-ce-merchandise-metadata",KJ:A.metadata},{S:"a",QP:["ytp-ce-merchandise-goto","ytp-ce-link"],G:{href:x$(c,A.targetUrl),target:"_blank",tabindex:"-1"},KJ:A.callToAction}]}]}]}]},{S:"div",V:"ytp-ce-expanding-image",G:SX(A)},{S:"div",V:"ytp-ce-merchandise-invideo-cta-container",N:[{S:"div",V:"ytp-ce-merchandise-invideo-cta",
KJ:A.callToAction||void 0}]}]},J=new g.t(c)}A.isPlaceholder&&g.dc(J.element,"ytp-ce-placeholder");return J},SX=function(c){if(c.vO)var A=c.vO.thumbnails;
return gDC(A?A[A.length-1].url:null)},gDC=function(c){return c?{style:"background-image: url("+c+")"}:{}},kJR=function(c,A,J){function q(O){O&&(A.listen("blur",function(){O.style.display!="none"&&c.CJ&&O.focus()}),A.Z(O,"focus",p),A.Z(O,"blur",m))}
function Y(O){c.D+=O;c.D>0?(g.dc(A.element,"ytp-ce-force-expand"),P8(c,J.id,!0)):(g.Ot(A.element,"ytp-ce-force-expand"),g.Ot(A.element,"ytp-ce-element-hover"),P8(c,J.id,!1))}
function p(){Y(1)}
function m(){Y(-1)}
A.listen("mouseenter",function(){oDw(c,A,J)});
A.listen("mouseleave",function(){uei(c,A,J)});
c.player.B().K||A.listen("click",function(){g.dc(A.element,"ytp-ce-element-hover")});
A.listen("click",function(O){$VV(c,J,O)});
A.listen("keypress",function(O){$VV(c,J,O)});
A.listen("focus",function(){oDw(c,A,J)});
A.listen("blur",function(){uei(c,A,J)});
A.listen("touchstart",function(){oDw(c,A,J)});
var E=g.ej("ytp-ce-expanding-overlay-hider",A.element);E&&A.Z(E,"touchstart",function(O){O.stopPropagation();g.Ot(A.element,"ytp-ce-element-hover");g.Ot(A.element,"ytp-ce-force-expand")});
A.listen("keydown",function(O){c.CJ=O.keyCode===9&&!O.shiftKey});
q(g.ej("ytp-sb-subscribe",A.element));q(g.ej("ytp-sb-unsubscribe",A.element));A.listen("focus",p);A.listen("blur",m)},$VV=function(c,A,J){if(A.targetUrl&&(!J||J.type!=="keypress"||J.keyCode===13)){for(var q=J.target;q&&!g.jS(q,"ytp-ce-element");){g.jS(q,"subscribe-label")&&wpx(c,A);
if(g.jS(q,"ytp-ce-channel-subscribe"))return;q=q.parentElement||null}if(!q||g.jS(q,"ytp-ce-element-hover")){J.preventDefault();J.stopPropagation();if(q=c.K[A.id])uei(c,q,A),q.element.blur();if(J.ctrlKey||J.metaKey||A.DzD==="new")wpx(c,A),c.player.sendVideoStatsEngageEvent(17,void 0),c.player.pauseVideo(),J=g.nc(x$(c,A.targetUrl)),J=g.tp(J),g.yN(J,void 0,A.sessionData);else{var Y=g.c1(c.player.B())||c.player.getVideoData().Nq,p=function(){var m=x$(c,A.targetUrl),E=A.sessionData,O=A.watchEndpoint,T=
g.mF(m);Y&&T&&(T.v||T.list)?c.player.J5(T.v,E,T.list,!1,void 0,O||void 0):g.iZ(m,E)};
wpx(c,A,function(){c.player.sendVideoStatsEngageEvent(17,p)})}}}},x$=function(c,A){c=c.player.B();
if(A){if(A.startsWith("//"))return c.protocol+":"+A;if(A.startsWith("/"))return g.jY(c)+A}else return"";return A},oDw=function(c,A,J){g.jS(A.element,"ytp-ce-element-hover")||(J.type==="VIDEO"||J.type==="PLAYLIST"?g.dc(A.element,"ytp-ce-element-hover"):c.player.B().K?(new g.hN(function(){g.dc(A.element,"ytp-ce-element-hover")},200)).start():g.dc(A.element,"ytp-ce-element-hover"),sR(c,J.U4),P8(c,J.id,!0))},uei=function(c,A,J){g.Ot(A.element,"ytp-ce-element-hover");
g.Ot(A.element,"ytp-ce-force-expand");P8(c,J.id,!1)},P8=function(c,A,J){c.j&&(J?c.U.show():c.U.hide());
for(var q=g.u(Object.keys(c.K)),Y=q.next();!Y.done;Y=q.next())Y=Y.value,Y!==A&&g.Rf(c.K[Y].element,"ytp-ce-element-shadow-show",J)},sR=function(c,A,J){function q(){p||(Y++,Y===A.length&&(m.stop(),J&&J()))}
if(!A||A.length===0||IJ(c))J&&J();else{A=WgH(c,A);var Y=0,p=!1,m=new g.hN(function(){p=!0;J&&J()},1E3,c);
m.start();for(c=0;c<A.length;c++)g.fd(A[c],q)}},wpx=function(c,A,J){sR(c,A.clickUrls,J);
(c=g.CK())&&A.NA&&g.EP(c,A.visualElement)},WgH=function(c,A){var J=c.player.getVideoData().clientPlaybackNonce;
c=c.player.getCurrentTime().toFixed(2);J={CPN:J,AD_CPN:J,MT:c};c=[];for(var q=0;q<A.length;q++)c.push(LgO(A[q],J));return c},LgO=function(c,A){return c.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(J){var q=unescape(J);
q=q.substring(1,q.length-1);return A[q]?escape(A[q]):J})},GJR=function(c){return typeof c==="string"?c:""},UR=function(c,A,J){for(var q in A)if(A[q]===c)return c;
return J},CYe=function(c,A,J,q){this.value=c;
this.target=A;this.showLinkIcon=J;this.C=q},fi=function(c){return c.value?c.value:null},lg=function(c){if(!c)return null;
var A=g.nc(GJR(c.value));A=g.tp(A);if(!A)return null;var J=UR(c.target,M_O,"current");if(J==null)c=null;else{var q=c.show_link_icon;c=new CYe(A,J,q==="true"||q==="false"?q==="true":!0,c.pause_on_navigation!=null?c.pause_on_navigation:!0)}return c},Fgw=function(c,A,J){this.type=c;
this.trigger=A;this.url=J},XpR=function(c){if(!c)return null;
var A=UR(c.type,vDx),J=UR(c.trigger,QIM);c=c.url;c=Array.isArray(c)&&c.length?c[0]:c;c=lg(c?c:null);return A?new Fgw(A,J,c):null},Zle=function(c,A,J,q,Y){this.id=c;
this.type=A;this.style=J;this.data=Y;this.action=q||[]},IhM=function(c,A){return g.VJ(c.action,A)},zqO=function(c,A){this.context=c;
this.C=A},SlV=function(c){return c.customMessage?aJ("div","iv-card-message",c.customMessage):""},bg=function(c,A){c="background-image: url("+c+");";
var J=[];A&&J.push(A);return{S:"div",V:"iv-card-image",G:{style:c},N:J}},xVe=function(c){if(!c.metaInfo||c.metaInfo.length===0)return"";
var A=[];c=g.u(c.metaInfo);for(var J=c.next();!J.done;J=c.next())A.push(aJ("li","",J.value));return{S:"ul",V:"iv-card-meta-info",N:A}},aJ=function(c,A,J){A?typeof A==="string"?A={"class":A}:Array.isArray(A)&&(A={"class":A.join(" ")}):A={};
A.dir=g.ki(J);return{S:c,G:A,KJ:J}},PYN=function(c){if(!c.customMessage)return"";
var A=["iv-card-action","iv-card-primary-link"],J={};c.i5&&(A.push("iv-card-action-icon"),J.style="background-image: url("+c.i5+");");J.dir=g.ki(c.customMessage);var q=[{S:"span",KJ:c.customMessage}];c.showLinkIcon&&(q.push("\u00a0"),q.push({S:"span",V:"iv-card-link-icon"}));return{S:"div",QP:A,G:J,N:q}},t$=function(c,A,J,q){if(q){A=g.u(A);
for(var Y=A.next();!Y.done;Y=A.next())c.C(Y.value,q,J.id,J.sessionData,J.Zb.click,5)}},sIV=function(c,A){this.merchant=c;
this.price=A},UVi=function(c){var A;
(A=c)&&!(A=c.length>1?c.charAt(0)==="/"&&c.charAt(1)!=="/":c==="/")&&(A=c.replace(/^(https?:)?\/\//,"").split("/",1),A=!A||A.length<1||!A[0]?[]:A[0].toLowerCase().split(".").reverse(),A=A[0]==="com"&&A[1]==="youtube"||A[0]==="be"&&A[1]==="youtu");return A?c.indexOf("/redirect?")===-1:!1},fhr=function(c,A){return A?A:UVi(c)?"current":"new"},ig=function(c,A){g.P.call(this);
var J=this;this.element=c;this.context=A;this.My=!1;this.Ba=new Map;this.I8=new Map;this.context.J.addEventListener(g.jo("annotations_module"),function(q){(q=J.Ba.get(q))&&q.apply(J)});
this.context.J.addEventListener(g.dP("annotations_module"),function(q){(q=J.I8.get(q))&&q.apply(J)})},y$=function(c,A,J,q,Y,p,m){c.context.C.listen(A,"click",function(E){c.fS(J,q,Y,p||[],m||0,E)});
c.context.C.listen(A,"touchstart",function(){c.My=!1});
c.context.C.listen(A,"touchmove",function(){c.My=!0})},lh9=function(c){var A;
return((A=g.l(c,g.UP))==null?0:A.url)?g.l(c,g.UP).url:(c=g.l(c,g.J8))&&c.videoId?(A="/watch?v="+c.videoId,c.playlistId&&(A+="&list="+c.playlistId),c.index&&(A+="&index="+c.index),c.startTimeSeconds&&(A+="&t="+c.startTimeSeconds),A):null},eX=function(c,A,J){return{Uy:(c.impressionLoggingUrlsV2s||[]).map(function(q){return q.baseUrl||""}),
click:(J.loggingUrls||[]).map(function(q){return q.baseUrl||""}),
close:(A.dismissLoggingUrlsV2s||[]).map(function(q){return q.baseUrl||""}),
d9:(A.impressionLoggingUrlsV2s||[]).map(function(q){return q.baseUrl||""}),
LD:(A.clickLoggingUrlsV2s||[]).map(function(q){return q.baseUrl||""})}},ahH=function(c,A,J){ig.call(this,A,J);
var q=this;this.J=c;this.eventId=null;this.CY=this.wF=this.F1=this.j=this.isInitialized=!1;this.cards=[];this.va=this.X=this.dF=this.U=this.xT=this.C=null;this.CJ=[];this.l$=this.D=this.oG=this.Oq=null;this.Y=0;this.Fl=new g.hN(function(){},J.o8.tS?4E3:3E3);
g.U(this,this.Fl);this.pJ=new g.hN(function(){});
g.U(this,this.pJ);this.nJ=new zqO(J,function(Y,p,m,E,O,T){y$(q,Y,p,m,E,O,T)});
this.L=new g.t({S:"div",V:"iv-drawer",G:{id:"iv-drawer"},N:[{S:"div",V:"iv-drawer-header",G:{"aria-role":"heading"},N:[{S:"span",V:"iv-drawer-header-text"},{S:"button",QP:["iv-drawer-close-button","ytp-button"],G:{"aria-label":"Hide cards",tabindex:"0"}}]},{S:"div",V:"iv-drawer-content"}]});g.U(this,this.L);this.T=this.L.element;this.Xl=new g.pk(this.L,330);g.U(this,this.Xl);this.oJ=g.ej("iv-drawer-header-text",this.T);this.K=g.ej("iv-drawer-content",this.T);this.addCueRange(0,J.videoData.lengthSeconds*
1E3,"",function(){q.F1&&ni(q,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(q.F1=q.j)&&Ki(q)});
this.eg=new g.sM(this);g.U(this,this.eg);this.J.addEventListener("videodatachange",this.PZ.bind(this))},blr=function(c,A){A=A.data;
A.autoOpenMs&&c.addCueRange(A.autoOpenMs,0x8000000000000,"",function(){ni(c,"YOUTUBE_DRAWER_AUTO_OPEN")});
A.autoCloseMs&&c.addCueRange(A.autoCloseMs,0x8000000000000,"",function(){Ki(c)});
var J=A.headerText;g.d5(c.oJ,J);c.X&&c.X.setAttribute("title",J);A.eventId&&(c.eventId=A.eventId);c.Oq=g.WQ(A.trackingParams);c.D=g.WQ(A.closeTrackingParams);c.oG=g.WQ(A.iconTrackingParams)},t_R=function(c,A){var J=A.cardId?A.cardId:"cr:"+c.Y,q=c.J.B().experiments.zx("enable_error_corrections_infocard_web_client");
if(!A.content&&A.teaser.simpleCardTeaserRenderer&&q){var Y=A.teaser.simpleCardTeaserRenderer,p=A.icon?A.icon.infoCardIconRenderer:null;A={id:J,timestamp:c.Y,type:"simple",teaserText:g.o1(Y.message),teaserDurationMs:Number(A.cueRanges[0].teaserDurationMs),startMs:Number(A.cueRanges[0].startCardActiveMs),autoOpen:!!A.autoOpen,sessionData:{},sponsored:!1,Zb:{},AQ:null,QI:Y.trackingParams?g.WQ(Y.trackingParams):null,oG:p&&p.trackingParams?g.WQ(p.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
i5:null,title:"",customMessage:"",url:null,onClickCommand:Y.onTapCommand||null};h$(c,A)}else{var m;if((m=A.content)==null?0:m.simpleCardContentRenderer){if(!A.cueRanges.length)return;p=(Y=A.content)==null?void 0:Y.simpleCardContentRenderer;Y=A.teaser.simpleCardTeaserRenderer;var E=A.icon?A.icon.infoCardIconRenderer:null;A={id:J,timestamp:c.Y,type:"simple",teaserText:g.o1(Y.message),teaserDurationMs:Number(A.cueRanges[0].teaserDurationMs),startMs:Number(A.cueRanges[0].startCardActiveMs),autoOpen:!!A.autoOpen,
sessionData:B8(c,J,A,p),sponsored:!1,Zb:eX(p,Y,p.command),AQ:p.trackingParams?g.WQ(p.trackingParams):null,QI:Y.trackingParams?g.WQ(Y.trackingParams):null,oG:E&&E.trackingParams?g.WQ(E.trackingParams):null,imageUrl:cJ(p.image.thumbnails,290).url,displayDomain:p.displayDomain?g.o1(p.displayDomain):null,showLinkIcon:!!p.showLinkIcon,i5:null,title:p.title?g.o1(p.title):"",customMessage:p.callToAction?g.o1(p.callToAction):"",url:g.l(p.command,g.UP).url?lg({pause_on_navigation:!c.context.videoData.isLivePlayback,
target:"new",value:g.l(p.command,g.UP).url}):null,onClickCommand:null};h$(c,A)}else{var O;if((O=A.content)==null?0:O.collaboratorInfoCardContentRenderer){if(!A.cueRanges.length)return;Y=(p=A.content)==null?void 0:p.collaboratorInfoCardContentRenderer;p=A.teaser.simpleCardTeaserRenderer;E=A.icon?A.icon.infoCardIconRenderer:null;A={id:J,timestamp:c.Y,type:"collaborator",teaserText:g.o1(p.message),teaserDurationMs:Number(A.cueRanges[0].teaserDurationMs),startMs:Number(A.cueRanges[0].startCardActiveMs),
autoOpen:!!A.autoOpen,sessionData:B8(c,J,A,Y),sponsored:!1,Zb:eX(Y,p,Y.endpoint),AQ:Y.trackingParams?g.WQ(Y.trackingParams):null,QI:p.trackingParams?g.WQ(p.trackingParams):null,oG:E&&E.trackingParams?g.WQ(E.trackingParams):null,channelId:g.l(Y.endpoint,g.CN).browseId,customMessage:Y.customText?g.o1(Y.customText):null,profileImageUrl:cJ(Y.channelAvatar.thumbnails,290).url,title:Y.channelName?g.o1(Y.channelName):"",metaInfo:[Y.subscriberCountText?g.o1(Y.subscriberCountText):""],url:lg({pause_on_navigation:!c.context.videoData.isLivePlayback,
target:"new",value:g.l(Y.endpoint,g.CN).canonicalBaseUrl?g.l(Y.endpoint,g.CN).canonicalBaseUrl:"/channel/"+g.l(Y.endpoint,g.CN).browseId}),onClickCommand:null};h$(c,A)}else{var T;if((T=A.content)==null?0:T.playlistInfoCardContentRenderer){if(!A.cueRanges.length)return;Y=(E=A.content)==null?void 0:E.playlistInfoCardContentRenderer;p=A.teaser.simpleCardTeaserRenderer;E=A.icon?A.icon.infoCardIconRenderer:null;A={id:J,timestamp:c.Y,type:"playlist",teaserText:g.o1(p.message),teaserDurationMs:Number(A.cueRanges[0].teaserDurationMs),
startMs:Number(A.cueRanges[0].startCardActiveMs),autoOpen:!!A.autoOpen,sessionData:B8(c,J,A,Y),sponsored:!1,Zb:eX(Y,p,Y.action),AQ:Y.trackingParams?g.WQ(Y.trackingParams):null,QI:p.trackingParams?g.WQ(p.trackingParams):null,oG:E&&E.trackingParams?g.WQ(E.trackingParams):null,RQ:cJ(Y.playlistThumbnail.thumbnails,258).url,customMessage:Y.customMessage?g.o1(Y.customMessage):null,playlistVideoCount:g.o1(Y.playlistVideoCount),title:Y.playlistTitle?g.o1(Y.playlistTitle):"",metaInfo:[Y.channelName?g.o1(Y.channelName):
"",Y.videoCountText?g.o1(Y.videoCountText):""],url:lg({pause_on_navigation:!c.context.videoData.isLivePlayback,target:"new",value:lh9(Y.action)}),onClickCommand:null};h$(c,A)}else{var R;if((R=A.content)==null?0:R.videoInfoCardContentRenderer){if(!A.cueRanges.length)return;var r;Y=(r=A.content)==null?void 0:r.videoInfoCardContentRenderer;p=A.teaser.simpleCardTeaserRenderer;E=A.icon?A.icon.infoCardIconRenderer:null;A={id:J,timestamp:c.Y,type:"video",teaserText:g.o1(p.message),teaserDurationMs:Number(A.cueRanges[0].teaserDurationMs),
startMs:Number(A.cueRanges[0].startCardActiveMs),autoOpen:!!A.autoOpen,sessionData:B8(c,J,A,Y),sponsored:!1,Zb:eX(Y,p,Y.action),AQ:Y.trackingParams?g.WQ(Y.trackingParams):null,QI:p.trackingParams?g.WQ(p.trackingParams):null,oG:E&&E.trackingParams?g.WQ(E.trackingParams):null,RQ:cJ(Y.videoThumbnail.thumbnails,258).url,videoDuration:Y.lengthString?g.o1(Y.lengthString):null,customMessage:Y.customMessage?g.o1(Y.customMessage):null,title:Y.videoTitle?g.o1(Y.videoTitle):"",metaInfo:[Y.channelName?g.o1(Y.channelName):
"",Y.viewCountText?g.o1(Y.viewCountText):""],isLiveNow:!!Y.badge,url:lg({pause_on_navigation:!c.context.videoData.isLivePlayback,target:"new",value:lh9(Y.action)}),onClickCommand:null};h$(c,A)}}}}}c.Y++},cJ=function(c,A){for(var J=-1,q=-1,Y=0;Y<c.length;Y++){if(c[Y].height===A||c[Y].width===290)return c[Y];
((c[Y].height||0)<A||(c[Y].width||0)<290)&&(J<0||(c[J].height||0)<(c[Y].height||0)||(c[J].width||0)<(c[Y].width||0))?J=Y:((c[Y].height||0)>=A||(c[Y].width||0)>=290)&&(q<0||(c[q].height||0)>(c[Y].height||0)||(c[q].width||0)>(c[Y].width||0))&&(q=Y)}return c[q>=0?q:J]},B8=function(c,A,J,q){return{feature:J.feature?J.feature:"cards",
src_vid:c.context.videoData.videoId,annotation_id:A,ei:c.context.videoData.eventId||"",itct:q.trackingParams||""}},yiH=function(c,A){if(A=ile(c,A))A===c.C&&(c.C=null),c.J.removeCueRange(A.Mq.id),g.mf(A.L9),g.oi(c.cards,A),c.dW(),AQ(c)},ni=function(c,A,J){if(!c.j){c.Xl.show();
c.xT=new g.hN(function(){g.dc(c.context.J.getRootNode(),g.cT.IV_DRAWER_OPEN)},0);
c.xT.start();c.eg.Z(c.K,"mousewheel",function(m){c.Fl.start();m.preventDefault();m=m||window.event;var E=0;m.type=="MozMousePixelScroll"?E=0==(m.axis==m.HORIZONTAL_AXIS)?m.detail:0:window.opera?E=m.detail:E=m.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?m.wheelDeltaY/-30:m.wheelDeltaY/-1.2:m.wheelDelta/-1.6:m.wheelDeltaY/-3;if(m=E)c.K.scrollTop+=m});
c.j=!0;var q=g.CK();q&&c.Oq&&c.D&&g.jd(q,[c.Oq,c.D]);A={TRIGGER_TYPE:A};for(var Y=g.u(c.cards),p=Y.next();!p.done;p=Y.next())p=p.value,p.YL||(p.YL=!0,eqx(c.context.logger,p.Mq.Zb.Uy,A)),q&&g.jd(q,[p.Mq.AQ]);Li(c.J);J&&(c.U=new g.hN(function(){c.dF=c.X;c.va.focus()},330),c.U.start())}},Ki=function(c){c.j&&(c.Xl.hide(),g.QD(c.eg),g.Ot(c.context.J.getRootNode(),g.cT.IV_DRAWER_OPEN),c.j=!1,Li(c.J),c.U&&c.U.stop(),c.U=new g.hN(function(){c.dF&&(c.dF.focus(),c.dF=null)},330),c.U.start())},nDJ=function(c){g.Et(c.nY(),
[g.cT.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.Sx(c.J,c.T,5);c.AP();c.X=g.ej("ytp-cards-button",c.J.getRootNode());c.va=g.ej("iv-drawer-close-button",c.T);c.isInitialized=!0},KgC=function(c){c.CJ.push(g.mG("iv-teaser-shown",c.jK,c));
c.CJ.push(g.mG("iv-teaser-hidden",c.rKF,c));c.CJ.push(g.mG("iv-teaser-clicked",c.n7,c));c.CY=!0},hqR=function(c,A){var J;
return A.onClickCommand&&((J=g.l(A.onClickCommand,g.MeN))==null?void 0:J.targetId)==="engagement-panel-error-corrections"?(c.l$=A,!0):!1},BO9=function(c,A){c.l$=A;
var J=c.J.getVideoData();if(!J)return!1;J=g.v1(J);if(J==null?0:J.markersMap)for(var q,Y=0;((q=J)==null?void 0:q.markersMap.length)>Y;Y++){var p=void 0,m=(p=J)==null?void 0:p.markersMap[Y];if(m.key==="ERROR_CORRECTION_MARKERS"&&(p=void 0,(m=(p=m.value)==null?void 0:p.markers)&&m.length>0))return q=void 0,A.startMs=((q=g.l(m[0],g.upI))==null?void 0:q.timeRangeStartMillis)||0,c.l$=null,!0}return!1},h$=function(c,A){if(!hqR(c,A)||BO9(c,A)){var J=ccr(c,A);
if(J){var q={Mq:A,L9:J.element,YL:!1};if(A.onClickCommand)c.J.W("web_infocards_teaser_show_logging_fix")&&(c.CY||KgC(c),yiH(c,A.id),J=c.findLastIndex(q),g.MR(c.cards,J,0,q));else{c.isInitialized||nDJ(c);yiH(c,A.id);var Y=c.findLastIndex(q);g.MR(c.cards,Y,0,q);J.Sg(c.K,Y);c.dW()}A.autoOpen?c.addCueRange(A.startMs,0x8000000000000,A.id,function(){c.j||(c.C=q,AQ(c),Acr(c,q),ni(c,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(J=c.context.J.getCurrentTime()*1E3,J<5E3&&J>A.startMs&&Jcw(c,q),c.addCueRange(A.startMs,
A.startMs+1,A.id,function(){Jcw(c,q)}),AQ(c))}}},ccr=function(c,A){switch(A.type){case "simple":c=c.nJ;
var J=A.displayDomain?{S:"div",V:"iv-card-image-text",KJ:A.displayDomain}:void 0;var q=PYN(A);J={S:"div",QP:["iv-card"],N:[{S:"a",V:"iv-click-target",G:{href:A.url?fi(A.url)||"":""},N:[bg(A.imageUrl,J),{S:"div",V:"iv-card-content",N:[aJ("h2",void 0,A.title),q]}]}]};J=new g.t(J);t$(c,g.io("iv-click-target",J.element),A,A.url);A=J;break;case "collaborator":c=c.nJ;J={S:"div",QP:["iv-card","iv-card-channel"],N:[{S:"a",QP:["iv-click-target"],G:{href:fi(A.url)||"","data-ytid":A.channelId},N:[bg(A.profileImageUrl),
{S:"div",V:"iv-card-content",N:[SlV(A),{S:"h2",V:"iv-card-primary-link",KJ:A.title},xVe(A)]}]}]};J=new g.t(J);t$(c,g.io("iv-click-target",J.element),A,A.url);A=J;break;case "playlist":c=c.nJ;J={S:"div",QP:["iv-card","iv-card-playlist"],N:[{S:"a",V:"iv-click-target",G:{href:fi(A.url)||""},N:[bg(A.RQ,{S:"div",V:"iv-card-image-overlay",N:[{S:"span",V:"iv-card-playlist-video-count",KJ:A.playlistVideoCount}]}),{S:"div",V:"iv-card-content",N:[SlV(A),aJ("h2","iv-card-primary-link",A.title),xVe(A)]}]}]};
J=new g.t(J);t$(c,g.io("iv-click-target",J.element),A,A.url);A=J;break;case "productListing":c=c.nJ;var Y=A.offers.length!=0;J=["iv-card"];q="";var p=PYN(A);Y&&(J.push("iv-card-product-listing"),q="iv-card-primary-link",p=A.offers[0],Y=[],p.price&&Y.push({S:"div",V:"iv-card-offer-price",KJ:p.price}),p.merchant&&Y.push({S:"div",V:"iv-card-offer-merchant",KJ:p.merchant}),p={S:"div",N:Y});Y=A.url?fi(A.url)||"":"";J={S:"div",QP:J,G:{tabindex:"0"},N:[{S:"a",QP:["iv-card-image","iv-click-target"],G:{style:"background-image: url("+
A.imageUrl+");",href:Y,"aria-hidden":"true",tabindex:"-1"}},{S:"div",V:"iv-card-content",N:[A.sponsored?{S:"div",V:"iv-card-sponsored",N:["Sponsored",{S:"div",V:"iv-ad-info-container",N:[{S:"div",V:"iv-ad-info",KJ:"{{adInfo}}"},{S:"div",V:"iv-ad-info-icon-container",N:[{S:"div",V:"iv-ad-info-icon"},{S:"div",V:"iv-ad-info-callout"}]}]}]}:"",{S:"a",V:"iv-click-target",G:{href:Y},N:[aJ("h2",q,A.title),p]}]}]};J=new g.t(J);q=g.AH("span");g.d5(q,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
J.ir(q,"adInfo");t$(c,g.io("iv-click-target",J.element),A,A.url);A=J;break;case "video":c=c.nJ;q=A.videoDuration?{S:"span",V:"iv-card-video-duration",KJ:A.videoDuration}:void 0;p=A.isLiveNow?{S:"span",QP:["yt-badge","yt-badge-live"],KJ:"LIVE NOW"}:null;Y={S:"div",QP:["iv-card","iv-card-video"],N:[{S:"a",V:"iv-click-target",G:{href:((J=A.url)==null?void 0:fi(J))||""},N:[bg(A.RQ,q),{S:"div",V:"iv-card-content",N:[SlV(A),aJ("h2","iv-card-primary-link",A.title),xVe(A),p]}]}]};J=new g.t(Y);t$(c,g.io("iv-click-target",
J.element),A,A.url);A=J;break;default:return null}return A},q7w=function(c){if(c.C)return c.C.Mq.type==="productListing";
if(c.J.W("enable_wn_infocards")){var A;return!((A=c.cards)==null||!A.length)&&g.yg(c.cards,function(J){return J.Mq.type==="productListing"})}return g.yg(c.cards,function(J){return J.Mq.type==="productListing"})},AQ=function(c){g.Rf(c.J.getRootNode(),"ytp-cards-shopping-active",q7w(c))},Jcw=function(c,A){if(!g.jS(c.J.getRootNode(),"ytp-cards-teaser-shown")){if(c.C!==A){var J=g.CK(),q=c.C?c.C.Mq.oG:c.oG;
J&&q&&g.dZ(J,[q]);c.C=A;AQ(c)}if(J=c.isInitialized)J=c.nY().style.display=="none";J||(J=c.context.J.getPlayerState(),q=J===0&&c.context.J.getCurrentTime()===0,J=!(J===1||J===3||q));J||A.Mq.teaserDurationMs&&c.J.Nb(!0,{teaserText:A.Mq.teaserText,durationMs:A.Mq.teaserDurationMs,onClickCommand:A.Mq.onClickCommand});c.pJ.isActive()||((!c.j||!c.Fl.isActive()&&c.wF)&&Acr(c,A),c.pJ.start(910+A.Mq.teaserDurationMs))}},Acr=function(c,A){c.L.qy?(A=new v8([0,
c.K.scrollTop],[0,A.L9.offsetTop],600,EDJ),c.context.j.listen(A,"animate",function(J){c.K.scrollTop=J.y}),c.context.j.listen(A,"finish",function(J){c.K.scrollTop=J.y}),A.play()):(c.L.LY(!0),c.K.scrollTop=A.L9.offsetTop,c.L.LY(!1))},JQ=function(c){return c.C&&c.C.Mq?c.C.Mq:c.cards[0]&&c.cards[0].Mq?c.cards[0].Mq:null},ile=function(c,A){return g.VJ(c.cards,function(J){return J.Mq.id===A})},qH=function(c,A,J){ig.call(this,c,A);
this.annotation=J;this.isActive=!1},Y7R=function(c){var A=c.annotation.data;
"start_ms"in A&&"end_ms"in A&&c.addCueRange(Number(A.start_ms),Number(A.end_ms),c.annotation.id,function(){c.show()},function(){c.hide()})},YW=function(c,A,J){qH.call(this,c,A,J);
this.K=null;this.D=!1;this.j=null;this.T=!1;this.C=this.Y=this.U=null},p$N=function(c,A){var J=J===void 0?0:J;
var q=ciN(A).width;g.aU(A,q);J=new jIJ(A,[q,A.offsetTop],[q-q-J,A.offsetTop],200,dVM);g.U(c,J);c.context.j.listen(J,"begin",function(){g.na(A,!0)});
J.play()},dDw=function(c,A){if(A.channel_name){var J=c.createElement({S:"div",
QP:["iv-branding-context-name"],KJ:A.channel_name}),q=c.createElement({S:"div",QP:["iv-branding-context-subscribe"]}),Y=A.standalone_subscribe_button_data;Y&&(c.C=new g.nZ(Y.subscribeText,Y.subscribeCount,Y.unsubscribeText,Y.unsubscribeCount,!!Y.enabled,!!Y.classic,A.channel_id,!!Y.subscribed,Y.feature,A.session_data.itct,c.context.J,!1),c.C.Sg(q));var p=c.createElement({S:"div",QP:["iv-branding-context-subscribe-caret"]}),m=c.createElement({S:"div",QP:["branding-context-container-inner"]});m.appendChild(p);
m.appendChild(J);m.appendChild(q);g.na(m,!1);var E=c.createElement({S:"div",QP:["branding-context-container-outer"]});E.appendChild(m);g.SL(E,"right",A.image_width+"px");g.qr(c.nY(),E);c.j=new g.hN(function(){mDR(c,m,E)},500);
g.U(c,c.j);c.context.C.listen(c.nY(),"mouseover",function(){juM(c,m,E,p,A.image_height)});
c.context.C.listen(c.nY(),"mouseout",function(){c.j.start()})}},juM=function(c,A,J,q,Y){c.j.stop();
if(!c.T){var p=g.eL(A);c.C||(A.style.width=g.lP(p.width,!0),J.style.width=g.lP(p.width,!0));g.SL(q,"top",p.height-Math.max(Math.min(p.height,Y)/2+10,20)+"px");g.SL(q,"right","1px");c.T=!0;g.na(A,!0);c.U=new g.hN(function(){g.dc(this.nY(),"iv-branding-active")},0,c);
c.U.start()}},mDR=function(c,A,J){g.Ot(c.nY(),"iv-branding-active");
c.Y=new g.hN(function(){g.na(A,!1);c.C||(J.style.width=g.lP(0,!0))},250);
c.Y.start();c.T=!1},EbH=function(c,A,J,q,Y,p,m){this.C=c;
this.j=A;this.o8=J;this.videoData=q;this.logger=Y;this.J=p;this.K=m},OVC=function(c,A,J){qH.call(this,c,A,J);
var q=this;this.X=this.isCollapsed=this.L=!1;this.Y=5E3;this.K=this.j=this.C=this.T=null;this.D=this.createElement({S:"div",QP:["iv-promo-contents"]});this.U=new g.hN(function(){q.C.setAttribute("aria-hidden","true");g.na(q.j,!1);g.na(q.K,!0)},700,this);
g.U(this,this.U)},RiN=function(c){var A=c.annotation.data;
if(c.annotation.style==="cta")var J=6;else if(c.annotation.style==="video"||c.annotation.style==="playlist")J=7;c.Y=A.collapsedelay_ms||c.Y;var q=["iv-promo","iv-promo-inactive"];c.nY().setAttribute("aria-hidden","true");c.nY().setAttribute("aria-label","Promotion");c.nY().tabIndex=0;var Y=c.annotation.di(),p=A.image_url;if(p){var m=c.createElement({S:"div",QP:["iv-promo-img","iv-click-target"]});p=c.createElement({S:"img",G:{src:p,"aria-hidden":"true"}});m.appendChild(p);A.video_duration&&!A.is_live?
(p=c.createElement({S:"span",V:"iv-promo-video-duration",KJ:A.video_duration}),m.appendChild(p)):A.playlist_length&&(p=c.createElement({S:"span",V:"iv-promo-playlist-length",KJ:A.playlist_length.toString()}),m.appendChild(p));Y&&y$(c,m,Y,c.annotation.id,A.session_data,void 0,J)}Y?(p=c.createElement({S:"a",V:"iv-promo-txt"}),g.hp(p,fi(Y)),c.C=p):c.C=c.createElement({S:"div",V:"iv-promo-txt"});switch(c.annotation.style){case "cta":case "website":var E=c.createElement({S:"p",N:[{S:"strong",KJ:A.text_line_1}]});
var O=c.createElement({S:"p",N:[{S:"span",V:"iv-promo-link",KJ:A.text_line_2}]});if(p=A.text_line_3){q.push("iv-promo-website-card-cta-redesign");var T=c.createElement({S:"button",QP:["iv-promo-round-expand-icon","ytp-button"]});p=c.createElement({S:"button",QP:["iv-button","iv-promo-button"],N:[{S:"span",V:"iv-button-content",KJ:p}]});var R=c.createElement({S:"div",V:"iv-promo-button-container"});R.appendChild(p);Y&&y$(c,c.nY(),Y,c.annotation.id,A.session_data,void 0,J)}g.dc(c.C,"iv-click-target");
Y&&y$(c,c.C,Y,c.annotation.id,A.session_data,void 0,J);break;case "playlist":case "video":E=c.createElement({S:"p",N:[{S:"span",KJ:A.text_line_1}]}),O=c.createElement({S:"p",N:[{S:"strong",KJ:A.text_line_2}]}),A.is_live&&(E=O,O=c.createElement({S:"span",QP:["yt-badge","iv-promo-badge-live"],KJ:"LIVE NOW"})),g.dc(c.C,"iv-click-target"),Y&&y$(c,c.C,Y,c.annotation.id,A.session_data,void 0,J),q.push("iv-promo-video")}E&&c.C.appendChild(E);O&&c.C.appendChild(O);c.D.appendChild(c.C);R&&c.D.appendChild(R);
J=c.createElement({S:"div",V:"iv-promo-actions"});c.K=c.createElement({S:"button",QP:["iv-promo-expand","ytp-button"]});c.K.title="Expand";c.context.C.listen(c.K,"click",function(r){TnR(c,5E3,r)});
J.appendChild(c.K);g.na(c.K,!1);c.context.C.listen(c.nY(),"mouseover",c.qS,c);c.context.C.listen(c.nY(),"mouseout",c.uP,c);c.context.C.listen(c.nY(),"touchend",function(r){TnR(c,5E3,r)});
c.j=c.createElement({S:"button",QP:["iv-promo-close","ytp-button"]});c.j.title="Close";c.context.C.listen(c.j,"click",c.annotation.style==="cta"&&A.text_line_3?c.iP:c.G9,c);J.appendChild(c.j);g.Et(c.nY(),q);m&&(g.qr(c.nY(),m),T&&m.appendChild(T));g.qr(c.nY(),c.D);g.qr(c.nY(),J)},TnR=function(c,A,J){J.stopPropagation();
rcH(c);HVC(c,A);c.C.focus()},VO9=function(c){c.isCollapsed||c.X||c.T||(g.dc(c.nY(),"iv-promo-collapsed"),c.isCollapsed=!0,c.U.start())},rcH=function(c){c.U.stop();
c.isCollapsed&&(g.Ts(c.nY(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),c.isCollapsed=!1,c.C&&c.C.removeAttribute("aria-hidden"),g.na(c.K,!1),g.na(c.j,!0))},HVC=function(c,A){c.T||(c.T=g.PV(function(){Nne(this);
VO9(this)},A,c))},Nne=function(c){c.T&&(g.e1.clearTimeout(c.T),c.T=null)},DDr=function(c){this.J=c},eqx=function(c,A,J){A&&(J?pC(c,A.map(function(q){return g.XZ(q,J)})):pC(c,A))},pC=function(c,A,J,q){var Y=1,p=void 0,m=-1;
if(J){var E=!1;p=function(){Y--;Y||E||(clearTimeout(m),E=!0,J())};
m=setTimeout(function(){E=!0;J()},1E3)}A=g.u(A||[]);
for(var O=A.next();!O.done;O=A.next())O=O.value,Y++,g.fd(O,p);q&&(Y++,q!==0&&c.J.sendVideoStatsEngageEvent(q,p))},kQO=function(c){g.V5.call(this,c);
var A=this;this.CJ=this.X=!1;this.loadNumber=0;this.Y={};this.logger=new DDr(this.player);this.T=new g.sM(this);this.U=this.D=null;this.events=new g.sM(this);this.dO=this.L=this.C=null;this.l$=[];g.U(this,this.T);this.T.Z(this.player,"onVideoAreaChange",function(){A.publish("onVideoAreaChange")});
this.T.Z(this.player,"onHideControls",function(){A.publish("onHideControls")});
this.T.Z(this.player,"onShowControls",function(){A.publish("onShowControls")});
this.T.Z(this.player,"resize",function(q){A.publish("resize",q)});
this.T.Z(this.player,"presentingplayerstatechange",function(q){A.publish("presentingplayerstatechange",q)});
this.subscribe("presentingplayerstatechange",this.Eg,this);this.subscribe("resize",this.t2,this);this.player.B().wF.subscribe("vast_info_card_add",this.VK,this);g.U(this,this.events);this.nJ=this.createElement({S:"div",V:"video-custom-annotations"});this.K=new g.t({S:"div",QP:["ytp-player-content","ytp-iv-player-content"]});g.U(this,this.K);g.Sx(this.player,this.K.element,4);this.K.hide();this.j=new g.t({S:"div",QP:["ytp-iv-video-content"]});g.U(this,this.j);c=this.createElement({S:"div",V:"video-annotations"});
c.appendChild(this.nJ);this.j.element.appendChild(c);this.JC()&&this.load();var J=this.createElement({S:"style"});(g.tv("HEAD")[0]||document.body).appendChild(J);this.addOnDisposeCallback(function(){g.mf(J)});
if(c=J.sheet)c.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),c.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),c.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),c.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),c.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),c.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),c.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),c.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),c.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),c.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},gbN=function(c){c=c.createElement({S:"div",
QP:["annotation","annotation-type-custom"]});g.na(c,!1);return c},obC=function(c,A){A=!A.isCued()&&!g.e(A,1024);
c.K.LY(A);c.j.LY(A)},uAH=function(c,A,J){c.X=!0;
c.U=g.C2(A,J)},$Dx=function(c,A){for(var J={},q=g.u(A.attributes),Y=q.next();!Y.done;Y=q.next())Y=Y.value,J[Y.name]=Y.nodeValue;
for(q=0;q<A.childNodes.length;q++)if(Y=A.childNodes[q],g.Je(Y)&&Y.nodeType==1){if(J[Y.tagName])var p=J[Y.tagName];else if(Y.tagName==="data"){Y.childNodes.length>0&&(p=Y.childNodes[0].nodeValue,J[Y.tagName]=typeof p==="string"?p.trim():p);continue}else p=[],J[Y.tagName]=p;Y&&Y.tagName==="TEXT"?Y.childNodes.length===1&&Y.childNodes[0].nodeType===3?p.push(Y.childNodes[0].nodeValue):p.push(""):Y&&p.push($Dx(c,Y))}return J},GQw=function(c){var A=g.x(c.player.getVideoData());
if(A.eg){var J=c.player.B().wF.get(A.videoId);if(J){var q={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(Y,p,m){Y=c.loadNumber;p=A.videoId;c.loaded&&c.loadNumber===Y&&c.player.getVideoData().videoId===p&&(m=g.Nz(m)&&m.responseXML?m.responseXML:null)&&w$w(c,m)}};
g.qB()&&(q.onFinish=WCx(c,q.onFinish));q.postParams={ic_only:"1"};LCO(q,J);c.X=!0;g.C2(A.eg,q)}}},LCO=function(c,A){c.method="POST";
c.postParams=c.postParams||{};A.aO&&(c.postParams.ic_coll=A.aO);A.MR&&(c.postParams.ic_xml=A.MR);A.NF&&(c.postParams.ic_track=A.NF)},Crw=function(c){var A=new g.t({S:"div"});
g.na(A.element,!1);var J=new ahH(c.player,A.element,mR(c));g.U(J,A);A.Sg(c.K.element);J.UQ();return J},FCR=function(c,A){var J,q;
if(A=(J=A.getWatchNextResponse())==null?void 0:(q=J.cards)==null?void 0:q.cardCollectionRenderer)c.CJ=!0,MOR(c,A),A.headerText&&c.dO&&(J=g.o1(A.headerText),c.dO.setAttribute("title",J))},mR=function(c){if(!c.L){var A=new OlV(c);
g.U(c,A);var J=new g.Dw(c);g.U(c,J);c.L=new EbH(A,J,c.player.B(),c.player.getVideoData(),c.logger,c.player,c.Dc)}return c.L},w$w=function(c,A){var J=!1,q=A.getElementsByTagName("annotations");
if(q&&!(q.length<1)&&(q=q[0].getAttribute("itct"))){var Y=g.CK();if(Y){var p=g.Gg();p&&g.c9(g.nK)(void 0,Y,p,[g.WQ(q)])}}A=A.getElementsByTagName("annotation");for(q=0;q<A.length;q++){p=$Dx(c,A[q]);Y=null;try{if(p){var m=p.id,E=/.+/;var O=typeof m==="string"&&E!=null&&m!=null&&m.match(E)?m:"";var T=UR(p.type,vbe),R=UR(p.style,QuJ),r=GJR(p.data),H=r.length!==0?JSON.parse(r):{};var V=p.action;p=XpR;if(V==null)var N=null;else if(g.Ae(V)){E=[];for(var w=g.u(V),W=w.next();!W.done;W=w.next()){var C=p(W.value);
C&&E.push(C)}N=E}else{var G=p(V);N=G?[G]:[]}Y=O&&T?new Zle(O,T,R,N,H):null}else Y=null}catch(q8){}if(Y)if(Y.type==="branding"||Y.type==="promotion"){p=c;E=Y;var Z=gbN(p),I=null;switch(E.type){case "branding":if(p.player.B().Zy)break;p.K.element.appendChild(Z);I=new YW(Z,mR(p),E);break;case "promotion":g.Sx(p.player,Z,4),I=new OVC(Z,mR(p),E)}I&&I.UQ();if(p=I)g.U(c,p),c.Y[Y.id]=p}else if(Y.type==="card"||Y.type==="drawer"){c.C||(c.C=Crw(c),g.U(c,c.C));if(Y.type==="card"){Z=c.C;var f=(J=Y)&&J.data&&
J.data.card_type;Y=J.data;if(f)switch(p=Y.tracking||{},p={Uy:p.impression,click:p.click,close:p.close,d9:p.teaser_impression,LD:p.teaser_click},E=Y.tracking_params||{},I=null,f){case "collaborator":J={id:J.id,timestamp:Y.timestamp||0,type:Y.card_type,teaserText:Y.teaser_text,teaserDurationMs:Y.teaser_duration_ms,startMs:Y.start_ms,autoOpen:Y.auto_open||!1,sessionData:Y.session_data||{},sponsored:Y.sponsored||!1,Zb:p,AQ:E.card?g.WQ(E.card):null,QI:E.teaser?g.WQ(E.teaser):null,oG:E.icon?g.WQ(E.icon):
null,channelId:Y.channel_id,customMessage:Y.custom_message?Y.custom_message:null,profileImageUrl:Y.image_url,title:Y.title,metaInfo:Y.meta_info,url:lg({pause_on_navigation:Y.pause_on_navigation,target:Y.target||"new",value:Y.url}),onClickCommand:null};h$(Z,J);break;case "playlist":J={id:J.id,timestamp:Y.timestamp||0,type:Y.card_type,teaserText:Y.teaser_text,teaserDurationMs:Y.teaser_duration_ms,startMs:Y.start_ms,autoOpen:Y.auto_open||!1,sessionData:Y.session_data||{},sponsored:Y.sponsored||!1,Zb:p,
AQ:E.card?g.WQ(E.card):null,QI:E.teaser?g.WQ(E.teaser):null,oG:E.icon?g.WQ(E.icon):null,RQ:Y.image_url,playlistVideoCount:Y.playlist_video_count,customMessage:Y.custom_message?Y.custom_message:null,title:Y.title,metaInfo:Y.meta_info,url:g.x(lg({pause_on_navigation:Y.pause_on_navigation,target:Y.target||"new",value:Y.url})),onClickCommand:null};h$(Z,J);break;case "productListing":Y.signin_url&&(I=lg({target:"current",value:Y.signin_url}));f=[];for(var K=Y.offers||[],y=0;y<K.length;y++)f.push(new sIV(g.oG(K[y].merchant),
g.oG(K[y].price)));J={id:J.id,timestamp:Y.timestamp||0,type:Y.card_type,teaserText:Y.teaser_text,teaserDurationMs:Y.teaser_duration_ms,startMs:Y.start_ms,autoOpen:Y.auto_open||!1,sessionData:Y.session_data||{},sponsored:Y.sponsored||!1,Zb:p,AQ:E.card?g.WQ(E.card):null,QI:E.teaser?g.WQ(E.teaser):null,oG:E.icon?g.WQ(E.icon):null,imageUrl:Y.image_url,displayDomain:Y.display_domain?Y.display_domain:null,showLinkIcon:!!Y.show_link_icon,i5:Y.button_icon_url?Y.button_icon_url:null,title:Y.title,customMessage:Y.custom_message?
Y.custom_message:null,url:g.x(lg({pause_on_navigation:Y.pause_on_navigation,target:Y.target||"new",value:Y.url})),AVx:I,rVq:Y.signin_title?Y.signin_title:void 0,KWg:Y.signin_message?Y.signin_message:void 0,offers:f,onClickCommand:null};h$(Z,J);break;case "simple":J={id:J.id,timestamp:Y.timestamp||0,type:Y.card_type,teaserText:Y.teaser_text,teaserDurationMs:Y.teaser_duration_ms,startMs:Y.start_ms,autoOpen:Y.auto_open||!1,sessionData:Y.session_data||{},sponsored:Y.sponsored||!1,Zb:p,AQ:E.card?g.WQ(E.card):
null,QI:E.teaser?g.WQ(E.teaser):null,oG:E.icon?g.WQ(E.icon):null,imageUrl:Y.image_url,displayDomain:Y.display_domain?Y.display_domain:null,showLinkIcon:!!Y.show_link_icon,i5:Y.button_icon_url?Y.button_icon_url:null,title:Y.title,customMessage:Y.custom_message?Y.custom_message:null,url:g.x(lg({pause_on_navigation:Y.pause_on_navigation,target:Y.target||"new",value:Y.url})),onClickCommand:null};h$(Z,J);break;case "video":J={id:J.id,timestamp:Y.timestamp||0,type:Y.card_type,teaserText:Y.teaser_text,teaserDurationMs:Y.teaser_duration_ms,
startMs:Y.start_ms,autoOpen:Y.auto_open||!1,sessionData:Y.session_data||{},sponsored:Y.sponsored||!1,Zb:p,AQ:E.card?g.WQ(E.card):null,QI:E.teaser?g.WQ(E.teaser):null,oG:E.icon?g.WQ(E.icon):null,RQ:Y.image_url,videoDuration:Y.video_duration||null,customMessage:Y.custom_message?Y.custom_message:null,title:Y.title,metaInfo:Y.meta_info,isLiveNow:!!Y.is_live_now,url:g.x(lg({pause_on_navigation:Y.pause_on_navigation,target:Y.target||"new",value:Y.url})),onClickCommand:null},h$(Z,J)}}else blr(c.C,Y);J=!0}}J&&
(Li(c.player),c.t2())},MOR=function(c,A){var J=!1;
c.C||(c.C=Crw(c),g.U(c,c.C));for(var q=g.u(A.cards||[]),Y=q.next();!Y.done;Y=q.next())Y=Y.value,Y.cardRenderer&&(t_R(c.C,Y.cardRenderer),J=!0);if(J){var p;(p=c.player.getVideoData())!=null&&g.IS(p)||(J=c.C,q=A.headerText?g.o1(A.headerText):"",g.d5(J.oJ,q),J.X&&J.X.setAttribute("title",q),J.context.videoData.eventId&&(J.eventId=J.context.videoData.eventId),J.Oq=A.trackingParams?g.WQ(A.trackingParams):null,J.D=A.closeButton.infoCardIconRenderer.trackingParams?g.WQ(A.closeButton.infoCardIconRenderer.trackingParams):
null,J.oG=A.icon.infoCardIconRenderer.trackingParams?g.WQ(A.icon.infoCardIconRenderer.trackingParams):null,c.t2());Li(c.player)}},X$H=function(c,A,J,q,Y){if(!c.player.B().Zy){var p=[];
A.navigationEndpoint&&g.l(A.navigationEndpoint,g.CN)&&g.l(A.navigationEndpoint,g.CN).browseId&&p.push(new Fgw("openUrl","click",new CYe("/channel/"+g.l(A.navigationEndpoint,g.CN).browseId,"new",!0,!0)));var m=A.watermark.thumbnails[0];q={channel_name:A.channelName,end_ms:A.endTimeMs,image_height:m.height,image_type:1,image_url:m.url,image_width:m.width,is_mobile:!1,session_data:{annotation_id:J,ei:Y,feature:"iv",itct:A.trackingParams,src_vid:q},start_ms:A.startTimeMs};if(A.subscribeButton&&g.l(A.subscribeButton,
g.MC)){q.channel_id=g.l(A.subscribeButton,g.MC).channelId;var E;A=g.l(A.subscribeButton,g.MC);m=Y=null;A.subscribed?(A.subscriberCountWithUnsubscribeText&&(Y=g.o1(A.subscriberCountWithUnsubscribeText)),A.subscriberCountText&&(m=g.o1(A.subscriberCountText))):(A.subscriberCountText&&(Y=g.o1(A.subscriberCountText)),A.subscriberCountWithSubscribeText&&(m=g.o1(A.subscriberCountWithSubscribeText)));var O,T=((O=g.l((E=A.signInEndpoint)==null?void 0:E.commandMetadata,g.gV))==null?void 0:O.url)||"";E={subscribeText:g.o1(A.unsubscribedButtonText),
subscribeCount:Y||"",unsubscribeText:g.o1(A.subscribedButtonText),unsubscribeCount:m||"",enabled:A.enabled||!1,classic:!1,subscribed:A.subscribed||!1,feature:"iv",signInUrl:T};q.standalone_subscribe_button_data=E}p=new Zle(J,"branding","branding",p,q);E=gbN(c);c.K.element.appendChild(E);p=new YW(E,mR(c),p);p.UQ();g.U(p,p);c.Y[J]=p}},WCx=function(c,A){return function(){var J=g.xI.apply(0,arguments);
c.Uq()||c.l$.push(g.lT.Ab(function(){A.apply(null,g.M(J))}))}},ZVe=function(c){return c==="annotation-editor"||c==="live-dashboard"};
g.MY.prototype.Nb=g.mY(45,function(c,A){var J=g.vO(this.rX());J&&J.Nb(c,A)});
var Ci={},M1=null;g.Tw(v8,g.rc);g.D=v8.prototype;g.D.getDuration=function(){return this.duration};
g.D.play=function(c){if(c||this.C==0)this.progress=0,this.coords=this.K;else if(this.isPlaying())return!1;Fp(this);this.startTime=c=g.d9();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.T=this.startTime;this.progress||this.C8();this.R9("play");this.isPaused()&&this.R9("resume");this.C=1;var A=g.YH(this);A in Ci||(Ci[A]=this);qlR();YlO(this,c);return!0};
g.D.stop=function(c){Fp(this);this.C=0;c&&(this.progress=1);ppM(this,this.progress);this.onStop();this.Dq()};
g.D.pause=function(){this.isPlaying()&&(Fp(this),this.C=-1,this.R9("pause"))};
g.D.rF=function(){this.C==0||this.stop(!1);this.R9("destroy");v8.Th.rF.call(this)};
g.D.destroy=function(){this.dispose()};
g.D.U1=function(){this.R9("animate")};
g.D.R9=function(c){this.dispatchEvent(new mVM(c,this))};
g.Tw(mVM,g.KA);g.Tw(Q$,v8);Q$.prototype.j=function(){};
Q$.prototype.U1=function(){this.j();Q$.Th.U1.call(this)};
Q$.prototype.Dq=function(){this.j();Q$.Th.Dq.call(this)};
Q$.prototype.C8=function(){this.j();Q$.Th.C8.call(this)};
g.Tw(jIJ,Q$);jIJ.prototype.j=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.k(OlV,g.P);g.D=OlV.prototype;g.D.listen=function(c,A,J,q){J=(0,g.pH)(J,q||this.K);c=g.Wt(c,A,J);this.C.push(c);return c};
g.D.MN=function(c,A,J,q){J=(0,g.pH)(J,q||this.K);c=Ai9(c,A,J);this.C.push(c);return c};
g.D.Jz=function(c){g.LX(c);g.oi(this.C,c)};
g.D.removeAll=function(){g.LX(this.C);this.C.length=0};
g.D.rF=function(){this.removeAll();g.P.prototype.rF.call(this)};g.k(riw,g.V5);g.D=riw.prototype;g.D.load=function(){g.V5.prototype.load.call(this);if(!IJ(this)){var c=g.Wx$(this.player.getVideoData());c?(c=RqH(c,Hli(this)),zk(this,c,!1)):V_H(this)}};
g.D.unload=function(){zk(this,null);this.T&&(this.T.abort(),this.T=null);g.V5.prototype.unload.call(this)};
g.D.Jo=function(c,A){return IJ(this)?c==="loadCustomEndscreenRenderer"?(c=RqH(A,"new"),zk(this,c),!0):null:null};
g.D.getOptions=function(){return IJ(this)?["loadCustomEndscreenRenderer"]:[]};
g.D.RJ=function(){if(this.endscreen&&this.endscreen.elements){var c=this.player.getVideoContentRect();if(c&&c.width!==0&&c.height!==0){var A=this.player.getPlayerSize();if(A&&A.width!==0&&A.height!==0){var J=c.width/c.height;var q=0;for(var Y=-1,p=0;p<IYe.length;p++){var m=Math.abs(A.width-IYe[p]);if(Y===-1||q>=m)Y=p,q=m}q=zii[Y];this.j&&g.SL(this.j.element,"outline-width",Math.max(A.width,A.height)+"px");for(A=0;A<this.endscreen.elements.length;++A)if(p=this.endscreen.elements[A].id,Y=this.K[p],
m=this.Y[p],Y&&m){var E=m.width*J/m.aspectRatio,O=Math.round(m.width*c.width);p=Math.round(E*c.height);var T=c.left+Math.round(m.left*c.width),R=c.top+Math.round(m.top*c.height);g.yZ(Y.element,O,p);g.aU(Y.element,T,R);g.Ts(Y.element,S7J);O>256||p>256?g.dc(Y.element,"ytp-ce-large-round"):O>96||p>96?g.dc(Y.element,"ytp-ce-medium-round"):g.dc(Y.element,"ytp-ce-small-round");g.Ts(Y.element,xDr);O=m.left+m.width/2;m=m.top+E/2;g.dc(Y.element,O<=.5&&m<=.5?"ytp-ce-top-left-quad":O>.5&&m<=.5?"ytp-ce-top-right-quad":
O<=.5&&m>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Ts(Y.element,zii);g.dc(Y.element,q);(Y=g.yy(document,"div","ytp-ce-expanding-overlay-body",Y.element)[0])&&g.SL(Y,"height",p+"px")}}}}};
g.D.onCueRangeEnter=function(c){if(this.endscreen)if(c.getId()==="ytp-ce-in-endscreen")sR(this,this.endscreen.impressionUrls),(c=g.CK())&&this.endscreen.visualElement&&g.mS(c,this.endscreen.visualElement),this.C&&(g.dc(this.C,"ytp-ce-element-show"),this.C.removeAttribute("aria-hidden"),this.player.ag()?g.dc(this.C,"ytp-ce-hide-button-lower"):g.Ot(this.C,"ytp-ce-hide-button-lower"));else{c=c.getId().substring(15);var A=this.K[c],J=this.Y[c];g.dc(A.element,"ytp-ce-element-show");A.element.removeAttribute("aria-hidden");
A=this.player.getRootNode();g.dc(A,"ytp-ce-shown");sR(this,J.impressionUrls);(A=g.CK())&&g.mS(A,J.visualElement);this.player.B().X&&this.player.gF("endscreenelementshown",c)}};
g.D.onCueRangeExit=function(c){if(c.getId()==="ytp-ce-in-endscreen")this.C&&(g.Ot(this.C,"ytp-ce-element-show"),this.C.setAttribute("aria-hidden","true"));else{c=c.getId().substring(15);var A=this.K[c];g.Ot(A.element,"ytp-ce-element-show");A.element.setAttribute("aria-hidden","true");A=this.player.getRootNode();g.Ot(A,"ytp-ce-shown");this.player.B().X&&this.player.gF("endscreenelementhidden",c)}};
g.D.mfT=function(c){var A=this;c.target===window&&(new g.hN(function(){for(var J=g.u(Object.values(A.K)),q=J.next();!q.done;q=J.next())g.Ts(q.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.D.LY=function(c){for(var A=g.u(Object.values(this.K)),J=A.next();!J.done;J=A.next())J=J.value,c?J.element.setAttribute("hidden",""):J.element.removeAttribute("hidden")};
g.D.oxl=function(c){this.C&&this.player.getRootNode().removeChild(this.C);c&&(g.dc(c,"ytp-ce-hide-button-container"),this.C=c,g.Sx(this.player,this.C,4))};
var IYe=[346,426,470,506,570,640,853,1280,1920],zii="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),xDr=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],S7J=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var M_O={CYK:"current",ZXl:"new"};var vDx={CLOSE:"close",gdJ:"openUrl",SUBSCRIBE:"subscribe"},QIM={Nx$:"click",CLOSE:"close",lGq:"hidden",akF:"rollOut",xOK:"rollOver",gsT:"shown"};Zle.prototype.di=function(){var c=IhM(this,function(A){return A.type==="openUrl"&&A.url!=null});
return c?c.url:null};
var QuJ={M4T:"anchored",ze:"branding",CHANNEL:"channel",sCl:"cta",rSl:"highlightText",MVl:"label",PLAYLIST:"playlist",POPUP:"popup",u7J:"speech",SUBSCRIBE:"subscribe",noF:"title",VIDEO:"video",ih8:"website"},vbe={ze:"branding",hRP:"card",SP0:"drawer",KaT:"highlight",Tqa:"marker",nsx:"promotion",TEXT:"text",Uwx:"widget"};g.k(ig,g.P);g.D=ig.prototype;g.D.addCueRange=function(c,A,J,q,Y){c=new g.p$(c,A,{id:J,namespace:"annotations_module"});q&&this.Ba.set(c,q);Y&&this.I8.set(c,Y);this.context.J.Lo([c],1)};
g.D.UQ=function(){this.context.K.subscribe("resize",this.dW,this)};
g.D.nY=function(){return this.element};
g.D.fS=function(c,A,J,q,Y,p){if(this.My)return!1;p&&(p.stopPropagation(),p.preventDefault());this.navigate(c,J,q,Y);return!1};
g.D.show=function(){};
g.D.hide=function(){};
g.D.destroy=function(){g.mf(this.nY())};
g.D.dW=function(){};
g.D.navigate=function(c,A,J,q){var Y=this,p=fi(c);if(p){var m=fhr(p,c.target),E=function(){c.C&&Y.context.J.pauseVideo();var O=Y.context.videoData.Nq||!1,T=g.mF(p||"");O&&T&&(T.v||T.list)?Y.context.J.J5(T.v,A,T.list,!1):g.yN(p||"",m==="current"?"_top":void 0,A)};
m==="new"&&(E(),E=null);pC(this.context.logger,J,E,q);UVi(p)||(J=g.CK(),q=A.itct,J&&q&&g.EP(J,g.WQ(q)))}};
g.D.rF=function(){this.Ba.clear();this.I8.clear();g.P.prototype.rF.call(this)};
g.D.createElement=function(c){c=new g.t(c);g.U(this,c);return c.element};g.k(ahH,ig);g.D=ahH.prototype;g.D.PZ=function(){this.l$&&h$(this,this.l$)};
g.D.isAvailable=function(){var c;if(c=!!this.cards.length)(c=this.J.getRootNode())?(c=g.eL(c),c=173<c.width&&173<c.height):c=!1;return c};
g.D.dW=function(){var c=this.isAvailable();g.na(this.nY(),c);g.Rf(this.context.J.getRootNode(),g.cT.IV_DRAWER_ENABLED,c);Li(this.J)};
g.D.destroy=function(){this.J.Nb(!1);try{this.J.getRootNode().removeChild(this.T)}catch(c){}g.jW(this.CJ);g.QD(this.eg);this.xT&&this.xT.dispose();this.U&&this.U.dispose();ig.prototype.destroy.call(this)};
g.D.AP=function(){var c=this;this.context.C.listen(g.ej("iv-drawer-close-button",this.T),"click",this.m5,this);this.context.C.listen(this.K,"touchend",function(){c.Fl.start()});
this.context.C.listen(this.K,"scroll",this.TG,this);this.context.K.subscribe("onHideControls",function(){c.wF=!0});
this.context.K.subscribe("onShowControls",function(){c.wF=!1});
this.context.K.subscribe("onVideoAreaChange",function(){c.wF=g.jS(c.J.getRootNode(),"ytp-autohide")});
this.CJ.push(g.mG("iv-button-shown",this.KTy,this));this.CJ.push(g.mG("iv-button-hidden",this.bJP,this));KgC(this)};
g.D.findLastIndex=function(c){if(this.cards.length===0)return 0;var A=g.NR(this.cards,function(J){return c.Mq.startMs>J.Mq.startMs||c.Mq.startMs===J.Mq.startMs&&c.Mq.timestamp>=J.Mq.timestamp?!0:!1});
return A===-1?0:A+1};
g.D.m5=function(){if(this.j){pC(this.context.logger,JQ(this).Zb.close);var c=g.CK();c&&this.D&&g.EP(c,this.D);Ki(this)}};
g.D.TG=function(){g.Rf(this.T,"iv-drawer-scrolled",this.K.scrollTop>0)};
g.D.KTy=function(){var c=g.CK(),A=JQ(this);A=A?A.oG:this.oG;c&&A&&g.jd(c,[A])};
g.D.bJP=function(){var c=g.CK(),A=JQ(this);A=A?A.oG:this.oG;c&&A&&g.dZ(c,[A])};
g.D.jK=function(){var c=JQ(this);pC(this.context.logger,c.Zb.d9);var A=g.CK();if(A&&c)if(this.J.W("web_infocards_teaser_show_logging_fix")){var J=[];c.QI&&J.push(c.QI);c.oG&&J.push(c.oG);J.length>0&&g.jd(A,J)}else g.jd(A,[c.QI,c.oG])};
g.D.rKF=function(){var c=g.CK(),A=JQ(this);c&&A&&g.dZ(c,[A.QI])};
g.D.n7=function(c){var A=JQ(this),J=g.CK();this.C?c?(c=this.context.logger,pC(c,A.Zb.LD),c.J.sendVideoStatsEngageEvent(4,void 0),J&&A.QI&&g.EP(J,A.QI)):(c=this.context.logger,pC(c,A.Zb.LD),c.J.sendVideoStatsEngageEvent(4,void 0),J&&A.oG&&g.EP(J,A.oG)):(c=this.context.logger,pC(c,A.Zb.LD),c.J.sendVideoStatsEngageEvent(4,void 0),J&&this.oG&&g.EP(J,this.oG))};g.k(qH,ig);qH.prototype.UQ=function(){ig.prototype.UQ.call(this);Y7R(this)};
qH.prototype.show=function(){ig.prototype.show.call(this);var c=g.CK(),A=this.annotation.data;c&&A&&(A=A.session_data)&&g.jd(c,[g.WQ(A.itct)])};
qH.prototype.hide=function(){ig.prototype.hide.call(this);var c=g.CK(),A=this.annotation.data;c&&A&&(A=A.session_data)&&g.dZ(c,[g.WQ(A.itct)])};g.k(YW,qH);
YW.prototype.show=function(){if(!this.isActive){qH.prototype.show.call(this);if(!this.D){g.dc(this.nY(),"iv-branding");var c=this.annotation.data;this.K=this.createElement({S:"img",QP:["branding-img","iv-click-target"],G:{"aria-label":"Channel watermark",src:c.image_url,width:c.image_width,height:c.image_height}});g.na(this.K,!1);var A=this.createElement({S:"button",QP:["branding-img-container","ytp-button"]});A.appendChild(this.K);this.nY().appendChild(A);var J=this.annotation.di();J&&y$(this,A,
J,this.annotation.id,c.session_data);this.context.J.W("disable_branding_context")||dDw(this,c);this.D=!0}g.na(this.nY(),!0);this.isActive=!0;if(this.K){try{p$N(this,this.K)}catch(q){}g.dc(this.context.J.getRootNode(),"ytp-branding-shown");this.context.J.getRootNode().style.setProperty("--branding-image-width",this.K.getAttribute("width")+"px")}}};
YW.prototype.hide=function(){this.isActive&&(qH.prototype.hide.call(this),g.na(this.nY(),!1),this.isActive=!1,g.Ot(this.context.J.getRootNode(),"ytp-branding-shown"))};
YW.prototype.destroy=function(){this.C&&(this.C.dispose(),this.C=null);g.Ot(this.context.J.getRootNode(),"ytp-branding-shown");qH.prototype.destroy.call(this)};g.k(OVC,qH);g.D=OVC.prototype;g.D.show=function(){this.isActive||(qH.prototype.show.call(this),this.L||(RiN(this),this.L=!0),g.na(this.nY(),!0),g.PV(function(){g.Ot(this.nY(),"iv-promo-inactive")},100,this),this.nY().removeAttribute("aria-hidden"),this.isActive=!0,Nne(this),rcH(this),HVC(this,this.Y))};
g.D.hide=function(){this.isActive&&(g.dc(this.nY(),"iv-promo-inactive"),this.isActive=!1,this.nY().setAttribute("aria-hidden","true"))};
g.D.fS=function(c,A,J,q,Y,p){return this.isCollapsed?!1:qH.prototype.fS.call(this,c,A,J,q,Y,p)};
g.D.qS=function(c){this.X=!0;TnR(this,500,c)};
g.D.uP=function(){this.X=!1;VO9(this)};
g.D.G9=function(c){c.stopPropagation();this.hide()};
g.D.iP=function(c){c.stopPropagation();Nne(this);this.isCollapsed=!0;g.dc(this.nY(),"iv-promo-collapsed-no-delay");this.U.start()};
g.D.destroy=function(){this.U.dispose();qH.prototype.destroy.call(this)};g.k(kQO,g.V5);g.D=kQO.prototype;g.D.Jo=function(c,A){if(!ZVe(this.player.B().playerStyle))return null;switch(c){case "loadCustomAnnotationsXml":return(c=g.et(A))&&w$w(this,c),!0;case "removeCustomAnnotationById":return A&&this.C&&(yiH(this.C,A),Li(this.player)),!0}return null};
g.D.getOptions=function(){return ZVe(this.player.B().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.D.JC=function(){var c=this.player.B(),A=g.x(this.player.getVideoData()),J=c.annotationsLoadPolicy||A.annotationsLoadPolicy;return g.B0(A)||this.player.isMutedByEmbedsMutedAutoplay()?!1:J===1&&!A.BX||c.wF.get(A.videoId)||g.zY(A)||g.SA(A)?!0:!1};
g.D.t2=function(){if(this.j){var c=this.player.i$().getVideoContentRect(!0);g.yZ(this.j.element,c.width,c.height);g.aU(this.j.element,c.left,c.top)}if(this.C){var A=this.player.LX();c=this.C;A=A.width;g.Rf(c.T,"iv-drawer-small",A<=426);g.Rf(c.T,"iv-drawer-big",A>=1280)}};
g.D.Eg=function(c){obC(this,c.state);g.e(c.state,2)&&(this.ag()&&this.l2()&&this.player.getPresentingPlayerType()!==2&&this.IU(!1),this.Nb(!1))};
g.D.load=function(){function c(m){var E=A.loadNumber;A.U=null;A.loaded&&A.loadNumber===E&&A.player.getVideoData().videoId===q&&(m=g.Nz(m)&&m.responseXML?m.responseXML:null)&&(w$w(A,m),g.dc(A.player.getRootNode(),"iv-module-loaded"))}
var A=this;g.V5.prototype.load.call(this);obC(this,this.player.getPlayerStateObject());this.loadNumber++;var J=g.x(this.player.getVideoData()),q=J.videoId;g.qB()&&(c=WCx(this,c));var Y={format:"XML",onFinish:c,onError:function(){A.U=null},
urlParams:{}};J.isPharma&&(Y.urlParams.pharma="1");Y.method="POST";Y.withCredentials=!0;var p=this.player.B().wF.get(q);p&&LCO(Y,p);p=p&&(p.MR||p.aO);if(!J.X_||p)J.eg?uAH(this,J.eg,Y):(this.D=function(){if(!A.X)A.onVideoDataChange(Y);var m=g.x(A.player.getVideoData());(m==null?0:g.IS(m))&&!A.CJ&&FCR(A,m)},this.player.addEventListener("videodatachange",this.D));
g.Sx(this.player,this.j.element,4);this.t2();(p=g.zY(J))&&MOR(this,p);(p=g.SA(J))&&p.featuredChannel&&X$H(this,p.featuredChannel,p.annotationId||"branding",J.videoId||null,J.eventId||null);this.dO=g.ej("ytp-cards-button",this.player.getRootNode());g.IS(J)&&FCR(this,J)};
g.D.onVideoDataChange=function(c){var A=g.x(this.player.getVideoData());A.eg&&uAH(this,A.eg,c)};
g.D.unload=function(){this.player.hm("annotations_module");for(var c=g.u(Object.keys(this.Y)),A=c.next();!A.done;A=c.next())this.Y[A.value].destroy();this.L=null;this.C&&(this.C.destroy(),this.C=null,Li(this.player));this.X=!1;this.U&&(this.U.abort(),this.U=null);this.CJ=!1;this.Y={};this.K.hide();g.V5.prototype.unload.call(this);this.j.detach();this.D&&(this.player.removeEventListener("videodatachange",this.D),this.D=null)};
g.D.VK=function(c){c===this.player.getVideoData().videoId&&(this.loaded?GQw(this):this.load())};
g.D.ag=function(){var c;return((c=this.C)==null?void 0:c.isAvailable())||this.CJ};
g.D.l2=function(){return!!this.C&&this.C.j};
g.D.IU=function(c,A,J){A=A===void 0?!1:A;this.ag();this.C&&(c?J?ni(this.C,J,A):ni(this.C,"YOUTUBE_DRAWER_AUTO_OPEN",A):Ki(this.C))};
g.D.Nb=function(c,A){this.player.publish(c?"cardsteasershow":"cardsteaserhide",A)};
g.D.rF=function(){this.player.B().wF.unsubscribe("vast_info_card_add",this.VK,this);g.Ot(this.player.getRootNode(),g.cT.IV_DRAWER_OPEN);for(var c=this.l$,A=g.lT,J=0,q=c.length;J<q;J++)A.W1(c[J]);this.l$.length=0;g.V5.prototype.rF.call(this)};
g.D.createElement=function(c){c=new g.t(c);g.U(this,c);return c.element};g.HO("annotations_module",kQO);g.HO("creatorendscreen",riw);})(_yt_player);
