(function(g){var window=this;'use strict';var UDH=function(c,A,J){g.S(function(q){c.C=g.C2(A,J);g.u$(q)})},ji=function(c){c.isActive()||c.start()},fYR=function(c,A){return A?c.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},lYR=function(c){return g.c1(c)||c.W("web_enable_caption_language_preference_stickiness")},aYC=function(c,A){var J=new g.DS;
J.languageCode=c.languageCode;J.languageName=c.languageName;J.name=c.name;J.displayName=c.displayName;J.kind=c.kind;J.isDefault=!1;J.C=c.C;J.isTranslateable=c.isTranslateable;J.vssId=c.vssId;J.url=c.url;J.translationLanguage=A;c.xtags&&(J.xtags=c.xtags);c.captionId&&(J.captionId=c.captionId);return J},bVR=function(c,A){var J,q,Y;
return g.S(function(p){if(p.K==1)return J=c+"|"+A,g.X(p,g.Bm(),2);if(p.K!=3){q=p.C;if(!q)throw g.wQ("gct");return g.X(p,g.zN(q),3)}Y=p.C;return p.return(Y.get("captions",J))})},tOr=function(c,A,J){bVR(c,A).then(function(q){q&&J(q.trackData,new g.DS(q.metadata))})},eiH=function(c){if(!iVH.test(c))throw Error("'"+c+"' is not a valid hex color");
c.length==4&&(c=c.replace(ycH,"#$1$1$2$2$3$3"));c=c.toLowerCase();c=parseInt(c.slice(1),16);return[c>>16,c>>8&255,c&255]},nbC=function(){var c=void 0;
c=c===void 0?{}:c;var A="suggest_correction"in g.gyx?g.gyx.suggest_correction:"Edit caption";A=A||"";var J={},q;for(q in c){J={BT:J.BT};J.BT=q;var Y=function(p){return function(){return String(c[p.BT])}}(J);
A=A.replace(new RegExp("\\$\\{"+J.BT+"\\}","gi"),Y);A=A.replace(new RegExp("\\$"+J.BT,"gi"),Y)}return A},KCx=function(){return g.Sq("yt-player-caption-display-settings")},dH=function(){this.segments=[]},hi9=function(c,A){var J=g.Zx(c.segments,A);
J>=0||J<0&&(-J-1)%2===1||(J=-J-1,J>0&&A-c.segments[J-1]===1&&J<c.segments.length&&c.segments[J]-A===1?(g.g9(c.segments,J),g.g9(c.segments,J-1)):J>0&&A-c.segments[J-1]===1?c.segments[J-1]=A:J<c.segments.length&&c.segments[J]-A===1?c.segments[J]=A:(g.MR(c.segments,J,0,A),g.MR(c.segments,J+1,0,A)))},BnH=function(c,A,J,q,Y,p){g.P.call(this);
this.policy=c;this.player=A;this.CJ=J;this.X=q;this.U=Y;this.L=p;this.T=new dH;this.Y=-1;this.j=this.K=this.C=null;this.l$=0;this.D=new g.hN(this.Oj,1E3,this);this.events=new g.sM(this);g.U(this,this.D);g.U(this,this.events);this.events.Z(A,"SEEK_COMPLETE",this.vC);this.vC();this.Oj()},cYR=function(c){return c.C&&c.C.Y?c.C.Y+c.player.mR()<c.player.getCurrentTime():!1},AYC=function(c,A){if(c.policy.w1&&c.player.lR()){var J=g.K_(A,c.policy,{});
J.set("pot",c.player.lR());J=J.di()}else J=g.K_(A,c.policy,{}).di();var q={format:"RAW",withCredentials:!0};if(c.policy.dF){q.method="POST";var Y=A.T;Y&&Object.keys(Y).length>0?q.postBody=g.Bs(Y,g.di):q.postBody=(0,g.uG)([120,0])}c.U&&(q.responseType="arraybuffer");var p=++c.l$,m=(0,g.b)();c.j=g.Q0(J,q,3,100).then(function(E){if(c.policy.TY&&p%100===1){var O=(0,g.b)();c.player.b$("caprsp",{rn:p,ms:O-m,kb:(E.xhr.responseText.length/1024).toFixed()})}a:{E=E.xhr;c.Uq();if(c.K){var T=!(c.U?E.response:
E.responseText)||E.status>=400;if(O=g.JJc(E)){E=g.K_(c.K,c.policy,{});c.K.Ig(E,O);AYC(c,c.K);break a}if(T)c.player.b$("capfail",{status:E.status});else{var R;g.QL("fcb_r",(0,g.b)(),((R=c.player.getVideoData())==null?void 0:R.L)||"");R=c.K.Gx[0].Ha;c.X!=null&&c.Y!==R&&(O=c.K.Gx[0],c.U?c.X(E.response,(O.startTime+c.player.mR())*1E3):c.X(E.responseText,(O.startTime+c.player.mR())*1E3),c.Y=R)}}c.K=null;c.j=null}}).Ye(function(E){c.K=null;
c.j=null;var O;c.player.b$("capfail",{rn:p,status:(O=E.xhr)==null?void 0:O.status})});
c.K=A;hi9(c.T,c.K.Gx[0].Ha)},Er=function(c,A){g.Dr.call(this,A);
this.C=c;this.J=A;this.j=null;this.Y=!1;this.logger=new g.jB("caps");this.D=g.iT$(this.J,this.C)},qTM=function(c,A){var J=[],q;
for(q in c.C.C)if(c.C.C.hasOwnProperty(q)){var Y=c.C.C[q];if(g.gy(Y,A||null)){var p=Y.info.id,m=p,E="."+p,O="",T="";if(Y=Y.info.captionTrack)p=Y.languageCode,m=Y.displayName,E=Y.vssId,O=Y.kind,T=Y.id;else{Y=p;var R=g.fQR.get(Y);R==null&&(R=JYw[Y]||JYw[Y.replace(/-/g,"_")],g.fQR.set(Y,R));Y=R;m=Y||m}J.push(new g.DS({id:q,languageCode:p,languageName:m,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:E,kind:O,captionId:T}))}}return J},YTN=function(c,A){return A!=null&&A in c.C.C?c.C.C[A]:null},
pWV=function(c,A,J){var q=[],Y;
for(Y in c.C.C)if(c.C.C.hasOwnProperty(Y)){var p=c.C.C[Y];if(g.gy(p,J||null)){var m=p.info.captionTrack;m&&m.languageCode===A&&q.push(p)}}return q.length?q[0]:null},Or=function(c,A,J,q,Y,p,m,E,O,T){var R=T.isInline()&&!0,r={};
Object.assign(r,A);Object.assign(r,c.params);Object.assign(r,J);var H={};Object.assign(H,A.le);c.params.le&&Object.assign(H,c.params.le);Object.assign(H,J.le);R&&(r.windowOpacity=.6,H.backgroundOpacity=0);r.le=H;var V=r.bY===1,N=[{S:"span",V:"captions-text",G:{style:"word-wrap: normal; display: block;"}}],w,W,C;(E=E.zx("caption_edit_on_hover")&&((w=T.getVideoData().getPlayerResponse())==null?void 0:(W=w.captions)==null?void 0:(C=W.playerCaptionsTracklistRenderer)==null?void 0:C.openTranscriptCommand))&&
N.unshift({S:"button",V:"caption-edit",G:{tabindex:"0","aria-label":nbC()},N:[{S:"svg",G:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},N:[{S:"path",G:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.t.call(this,{S:"div",V:"caption-window",G:{id:"caption-window-"+c.id,dir:V?"rtl":"ltr",tabindex:"0",lang:r.lang},N:N});var G=
this;this.D=[];this.Oq=!1;this.K=c;this.wF=this.dF=null;this.playerWidth=p;this.playerHeight=m;this.X=null;this.maxWidth=p*.96;this.maxHeight=m*.96;this.C=r;this.Nn=J;this.l$=A;this.T=this.Eq("captions-text");this.F1=this.T.style.getPropertyValue("box-decoration-break")!==""||this.T.style.getPropertyValue("-webkit-box-decoration-break")!=="";this.xT=mqH(q,Y,p,m);this.Bf=O;E&&(this.Y=this.Eq("caption-edit"),this.Z(this.Y,"click",function(){G.Bf()}));
this.type=0;this.Ba=this.xT*jFV(H);this.va=R;c=new g.SU(this.element,!0);g.U(this,c);c.subscribe("dragstart",this.Og,this);c.subscribe("dragmove",this.FW,this);c.subscribe("dragend",this.Ti,this);this.Xl=this.I8=this.My=this.pJ=0;c="";this.C.windowOpacity&&(c=eiH(this.C.windowColor),c="rgba("+c[0]+","+c[1]+","+c[2]+","+this.C.windowOpacity+")");A={"background-color":c,display:this.C.isVisible===!1?"none":"","text-align":dqH[this.C.textAlign]};this.F1&&(A["border-radius"]=c?this.Ba/8+"px":"");(this.j=
this.K.params.bY===2||this.K.params.bY===3)&&E3H(this,this.element);g.SL(this.element,A);if(R){var Z;(Z=this.element.parentElement)==null||Z.style.setProperty("--caption-window-color",c)}switch(this.C.yH){case 0:case 1:case 2:g.dc(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.dc(this.element,"ytp-caption-window-bottom")}},E3H=function(c,A){var J="vertical-rl";
c.C.GH===1&&(J="vertical-lr");g.Nm&&(J=J==="vertical-lr"?"tb-lr":"tb-rl");g.SL(A,"-o-writing-mode",J);g.SL(A,"-webkit-writing-mode",J);g.SL(A,"writing-mode",J);g.SL(A,"text-orientation","upright");g.dc(A,"ytp-vertical-caption");c.K.params.bY===3&&(g.SL(A,"text-orientation",""),g.SL(A,"transform","rotate(180deg)"))},jFV=function(c){var A=1+.25*(c.fontSizeIncrement||0);
if(c.offset===0||c.offset===2)A*=.8;return A},OmH=function(c,A){var J={},q=A.background?A.background:c.C.le.background;
if(A.backgroundOpacity!=null||A.background){var Y=A.backgroundOpacity!=null?A.backgroundOpacity:c.C.le.backgroundOpacity;q=eiH(q);J.background="rgba("+q[0]+","+q[1]+","+q[2]+","+Y+")";c.F1&&(J["box-decoration-break"]="clone",J["border-radius"]=c.Ba/8+"px")}if(A.fontSizeIncrement!=null||A.offset!=null)J["font-size"]=c.xT*jFV(A)+"px";q=1;Y=A.color||c.C.le.color;if(A.color||A.textOpacity!=null)Y=eiH(Y),q=A.textOpacity==null?c.C.le.textOpacity:A.textOpacity,Y="rgba("+Y[0]+","+Y[1]+","+Y[2]+","+q+")",
J.color=Y,J.fill=Y;var p=A.charEdgeStyle;p===0&&(p=void 0);if(p){Y="rgba(34, 34, 34, "+q+")";var m="rgba(204, 204, 204, "+q+")";A.Pw&&(m=Y=A.Pw);var E=c.xT/16/2,O=Math.max(E,1),T=Math.max(2*E,1),R=Math.max(3*E,1),r=Math.max(5*E,1);q=[];switch(p){case 4:for(;R<=r;R+=E)q.push(T+"px "+T+"px "+R+"px "+Y);break;case 1:T=window.devicePixelRatio>=2?.5:1;for(p=O;p<=R;p+=T)q.push(p+"px "+p+"px "+Y);break;case 2:q.push(O+"px "+O+"px "+m);q.push("-"+O+"px -"+O+"px "+Y);break;case 3:for(R=0;R<5;R++)q.push("0 0 "+
T+"px "+Y)}J["text-shadow"]=q.join(", ")}Y="";switch(A.fontFamily){case 1:Y='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:Y='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:Y='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:Y='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:Y='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:Y=g.iA()?
'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:Y='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}Y&&(J["font-family"]=Y);Y=A.offset;Y==null&&(Y=c.C.le.offset);switch(Y){case 0:J["vertical-align"]="sub";break;case 2:J["vertical-align"]="super"}A.fontFamily===7&&(J["font-variant"]="small-caps");A.bold&&(J["font-weight"]="bold");A.italic&&(J["font-style"]="italic");A.underline&&(J["text-decoration"]=
"underline");A.HU&&(J.visibility="hidden");A.H9===1&&c.j&&(J["text-combine-upright"]="all",J["text-orientation"]="mixed",Y=g.q9||g.uQ,c.K.params.bY===3?J.transform=Y?"rotate(90deg)":"rotate(180deg)":Y&&(J.transform="rotate(-90deg)"));if(A.textEmphasis===1||A.textEmphasis===2||A.textEmphasis===3||A.textEmphasis===4||A.textEmphasis===5)if(g.q9)J["font-weight"]="bold";else switch(J["text-emphasis-style"]="filled circle",J["text-emphasis-color"]="currentcolor",J["webkit-text-emphasis"]="filled circle",
A.textEmphasis){case 4:case 3:J["text-emphasis-position"]="under left";J["webkit-text-emphasis-position"]="under left";break;case 5:case 2:J["text-emphasis-position"]="over right",J["webkit-text-emphasis-position"]="over right"}return J},TB=function(c){c=c.split("px");
return c.length>0?(c=Number(c[0]))?c:0:0},T6x=function(c){c.X=g.AH("SPAN");
g.SL(c.X,{display:"block"});g.dc(c.X,"caption-visual-line");c.T.appendChild(c.X)},R2O=function(c,A){var J=g.AH("SPAN");
g.SL(J,{display:"inline-block","white-space":"pre-wrap"});g.SL(J,OmH(c,A));J.classList.add("ytp-caption-segment");c.X.appendChild(J);J.previousElementSibling&&(g.SL(J.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.SL(J,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return J},rY9=function(c,A,J){c.Oq=c.Oq||!!J;
var q={};Object.assign(q,c.C.le);Object.assign(q,J||A.C);Object.assign(q,c.Nn.le);(J=!c.X)&&T6x(c);for(var Y=c.dF&&c.wF&&g.Jp(q,c.wF)?c.dF:R2O(c,q),p=typeof A.text==="string",m=p?A.text.split("\n"):[A.text],E=0;E<m.length;E++){var O=E>0||!A.append,T=m[E];O&&!J?(T6x(c),Y=R2O(c,q)):O&&J&&(J=!1);T&&(Y.appendChild(p?g.JH(T):T),p||T.tagName!=="RUBY"||T.childElementCount!==4||g.q9||!g.Pv(T.children[2],"text-emphasis")||(O=c.j?"padding-right":"padding-top",g.Pv(T.children[2],"text-emphasis-position")&&(O=
c.j?"padding-left":"padding-bottom"),g.KB?g.SL(Y,O,"1em"):g.SL(Y,O,"0.5em")))}c.wF=q;c.dF=Y;c.D.push(A)},mqH=function(c,A,J,q){var Y=A/360*16;
A>=c&&(c=640,q>J*1.3&&(c=480),Y=J/c*16);return Y},VPN=function(){this.j=this.time=this.mode=this.K=0;
this.T=new HmM(this);this.U=new HmM(this);this.C=[];this.clear()},Dqi=function(c,A,J){if(c===255&&A===255||!c&&!A)return{Ho:c,
WN:A,result:0};c=N6O[c];A=N6O[A];if(c&128){var q;if(q=!(A&128))q=A,q=J.RZ()&&J.WN===q;if(q)return{Ho:c,WN:A,result:1}}else if(A&128&&1<=c&&c<=31)return{Ho:c,WN:A,result:2};return{Ho:c,WN:A,result:3}},g3N=function(c,A,J,q){A===255&&J===255||!A&&!J?(++c.j===45&&c.reset(),c.T.K.clear(),c.U.K.clear()):(c.j=0,k5r(c.T,A,J,q))},o3w=function(c,A){c.C.sort(function(Y,p){var m=Y.time-p.time;
return m===0?Y.order-p.order:m});
for(var J=g.u(c.C),q=J.next();!q.done;q=J.next())q=q.value,c.time=q.time,q.type===0?g3N(c,q.Yu,q.wU,A):q.type===1&&c.K&496&&k5r(c.U,q.Yu,q.wU,A);c.C.length=0},RX=function(){this.type=0},rH=function(){this.state=this.WN=this.Ho=0},u9N=function(){this.timestamp=this.C=0},HJ=function(c){this.U=c;
this.j=[];this.C=this.K=this.row=0;this.style=new RX;for(c=this.T=0;c<=15;c++){this.j[c]=[];for(var A=0;A<=32;A++)this.j[c][A]=new u9N}},VO=function(c,A){if(c.style.type===3){for(var J=0,q=0,Y=c.U.time+0,p="",m="",E=Y,O=1;O<=15;++O){for(var T=!1,R=q?q:1;R<=32;++R){var r=c.j[O][R];
if(r.C!==0){J===0&&(J=O,q=R);T=String.fromCharCode(r.C);var H=r.timestamp;H<Y&&(Y=H);r.timestamp=E;m&&(p+=m,m="");p+=T;T=!0}if((r.C===0||R===32)&&T){m="\n";break}else if(q&&!T)break}if(J&&!T)break}p&&A.T(J,q,Y,E,p)}else for(q=J=0,p=Y=c.U.time+0,m=1;m<=15;++m)for(E="",O=1;O<=32;++O)if(R=c.j[m][O],r=R.C,r!==0&&(J===0&&(J=m,q=O),T=String.fromCharCode(r),H=R.timestamp,H<=Y&&(Y=H),E+=T,R.reset()),O===32||r===0)E&&A.T(J,q,Y,p,E),Y=p,E="",q=J=0},G5R=function(c,A){switch(c){case 0:return $qN[(A&127)-32];
case 1:return wWJ[A&15];case 2:return WXR[A&31];case 3:return LX9[A&31]}return 0},NH=function(c){return c.j[c.row][c.K]},Da=function(c,A,J){A>=2&&c.K>1&&(--c.K,NH(c).C=0);
var q=NH(c);q.timestamp=c.U.time+0;q.C=G5R(A,J);c.K<32&&c.K++},CeN=function(c,A,J,q){for(var Y=0;Y<q;Y++)for(var p=0;p<=32;p++){var m=c.j[A+Y][p],E=c.j[J+Y][p];
m.C=E.C;m.timestamp=E.timestamp}},kW=function(c,A,J){for(var q=0;q<J;q++)for(var Y=0;Y<=32;Y++)c.j[A+q][Y].reset()},MPO=function(c){c.row=c.C>0?c.C:1;
c.K=1;kW(c,0,15)},FXH=function(c){this.j=c;
this.U=0;this.style=new RX;this.Y=new HJ(this.j);this.D=new HJ(this.j);this.text=new HJ(this.j);this.K=this.Y;this.T=this.D;this.C=this.K},v3e=function(c,A,J){var q=c.K,Y=!1;
switch(c.style.get()){case 4:case 1:case 2:c.style.get()===4&&q.C>0||(VO(q,J),MPO(c.K),MPO(c.T),q.row=15,q.C=A,Y=!0)}c.style.set(3);c.C=q;c.C.style=c.style;c.j.mode=1<<q.T;Y?q.K=1:q.C!==A&&(q.C>A?(VO(q,J),kW(q,q.row-q.C,A)):q.row<A&&(A=q.C),q.C=A)},QFO=function(c){c.style.set(1);
c.C=c.T;c.C.C=0;c.C.style=c.style;c.j.mode=1<<c.C.T},XWJ=function(c){c.style.set(4);
c.C=c.text;c.C.style=c.style;c.j.mode=1<<c.C.T},HmM=function(c){this.C=c;
this.U=0;this.j=new FXH(this.C);this.Y=new FXH(this.C);this.K=new rH;this.T=this.j},k5r=function(c,A,J,q){c.K.update();
A=Dqi(A,J,c.K);switch(A.result){case 0:return;case 1:case 2:return}var Y=A.Ho;J=A.WN;if(32<=Y||!Y)c.C.mode&c.C.K&&(A=Y,A&128&&(A=127),J&128&&(J=127),c=c.T.C,A&96&&Da(c,0,A),J&96&&Da(c,0,J),A!==0&&J!==0&&c.style.type===3&&VO(c,q));else if(Y&16)a:if(!c.K.matches(Y,J)&&(A=c.K,A.Ho=Y,A.WN=J,A.state=2,A=Y&8?c.Y:c.j,c.T=A,c.C.mode=1<<(c.U<<2)+(A.U<<1)+(A.style.type===4?1:0),(c.C.mode|1<<(c.U<<2)+(A.U<<1)+(A.style.type!==4?1:0))&c.C.K))if(J&64){q=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(Y&7)<<1|J>>5&1];
c=J&16?((J&14)>>1)*4:0;J=A.C;switch(A.style.get()){case 4:q=J.row;break;case 3:if(q!==J.row){if(q<J.C&&(q=J.C,q===J.row))break;var p=1+J.row-J.C,m=1+q-J.C;CeN(J,m,p,J.C);A=p;Y=J.C;m<p?(p=m+Y-p,p>0&&(A+=p,Y-=p)):(p=p+Y-m,p>0&&(Y-=p));kW(J,A,Y)}}J.row=q;J.K=c+1}else switch(Y&7){case 1:switch(J&112){case 32:Da(A.C,0,32);break a;case 48:J===57?(q=A.C,NH(q).C=0,q.K<32&&q.K++):Da(A.C,1,J&15)}break;case 2:J&32&&Da(A.C,2,J&31);break;case 3:J&32&&Da(A.C,3,J&31);break;case 4:case 5:if(32<=J&&J<=47)switch(J){case 32:QFO(A);
break;case 33:q=A.C;q.K>1&&(--q.K,NH(q).C=0);break;case 36:q=A.C;A=NH(q);for(c=0;c<=15;c++)for(J=0;J<=32;J++)if(q.j[c][J]===A){for(;J<=32;J++)q.j[c][J].reset();break}break;case 37:v3e(A,2,q);break;case 38:v3e(A,3,q);break;case 39:v3e(A,4,q);break;case 40:Da(A.C,0,32);break;case 41:A.style.set(2);A.C=A.K;A.C.C=0;A.C.style=A.style;A.j.mode=1<<A.C.T;break;case 42:q=A.text;q.C=15;q.style.set(4);MPO(q);XWJ(A);break;case 43:XWJ(A);break;case 44:c=A.K;switch(A.style.get()){case 1:case 2:case 3:VO(c,q)}kW(c,
0,15);break;case 45:b:{c=A.C;switch(A.style.get()){default:case 2:case 1:break b;case 4:if(c.row<15){++c.row;c.K=1;break b}break;case 3:}c.C<2&&(c.C=2,c.row<c.C&&(c.row=c.C));A=c.row-c.C+1;VO(c,q);CeN(c,A,A+1,c.C-1);kW(c,c.row,1)}break;case 46:kW(A.T,0,15);break;case 47:VO(A.K,q),A.T.updateTime(A.j.time+0),q=A.T,A.T=A.K,A.K=q,QFO(A)}break;case 7:switch(J){case 33:case 34:case 35:q=A.C,(q.K+=J&3)>32&&(q.K=32)}}},ZmR=function(){},gH=function(c,A,J,q,Y,p,m){p=p===void 0?!1:p;
m=m===void 0?null:m;g.p$.call(this,c,c+A,{priority:J,namespace:"captions"});this.windowId=q;this.text=Y;this.append=p;this.C=m},z2V=function(c,A,J,q,Y,p,m){var E=p[0],O=m[g.x(E.getAttribute("p"))];
if(O.H$===1){var T=p[1],R=p[2];p=p[3];E.getAttribute("t");T.getAttribute("t");R.getAttribute("t");p.getAttribute("t");E.getAttribute("p");T.getAttribute("p");p.getAttribute("p");m=m[g.x(R.getAttribute("p"))];E=Iiw(E.textContent,T.textContent,R.textContent,p.textContent,m);return new gH(c,A,Y,J,E,q,O)}switch(O.H$){case 9:case 10:O.textEmphasis=1;break;case 11:O.textEmphasis=2;break;case 12:O.textEmphasis=3;break;case 13:O.textEmphasis=4;break;case 14:O.textEmphasis=5}return new gH(c,A,Y,J,E.textContent||
"",q,O)},Iiw=function(c,A,J,q,Y){var p=g.iA(),m=p?g.AH("DIV"):g.AH("RUBY"),E=g.AH("SPAN");
E.textContent=c;m.appendChild(E);c=p?g.AH("DIV"):g.AH("RP");c.textContent=A;m.appendChild(c);A=p?g.AH("DIV"):g.AH("RT");A.textContent=J;m.appendChild(A);J=Y.H$;if(J===10||J===11||J===12||J===13||J===14)if(g.SL(A,"text-emphasis-style","filled circle"),g.SL(A,"text-emphasis-color","currentcolor"),g.SL(A,"webkit-text-emphasis","filled circle"),Y.H$===11||Y.H$===13)g.SL(A,"webkit-text-emphasis-position","under left"),g.SL(A,"text-emphasis-position","under left");J=!0;if(Y.H$===4||Y.H$===7||Y.H$===12||
Y.H$===14)g.SL(m,"ruby-position","over"),g.SL(m,"-webkit-ruby-position","before");else if(Y.H$===5||Y.H$===6||Y.H$===11||Y.H$===13)g.SL(m,"ruby-position","under"),g.SL(m,"-webkit-ruby-position","after"),J=!1;Y=p?g.AH("DIV"):g.AH("RP");Y.textContent=q;m.appendChild(Y);p&&(q=J,g.SL(m,{display:"inline-block",position:"relative"}),p=m.firstElementChild.nextElementSibling,g.SL(p,"display","none"),p=p.nextElementSibling,g.SL(p,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.SL(m.lastElementChild,"display","none"),q?(g.SL(m,"padding-top","0.6em"),g.SL(p,"top","0")):(g.SL(m,"padding-bottom","0.6em"),g.SL(p,"bottom","0")));return m},oX=function(){g.P.apply(this,arguments)},uz=function(c,A,J,q,Y){g.p$.call(this,c,c+A,{priority:J,
namespace:"captions"});this.id=q;this.params=Y;this.C=[]},ST9=function(c){var A="_"+$W++;
return new uz(0,0x8000000000000,0,A,c)},wH=function(c){oX.call(this);
this.j=c;this.pens={};this.D={};this.X={};this.T="_"+$W++;this.Y={};this.K=this.C=null;this.U=!0},WJ=function(c,A){c=c.getAttribute(A);
if(c!=null)return Number(c)},LC=function(c,A){c=c.getAttribute(A);
if(c!=null)return c==="1"},GB=function(c,A){c=WJ(c,A);
return c!==void 0?c:null},MH=function(c,A){c=c.getAttribute(A);
if(c!=null)return CC.test(c),c},xqe=function(c,A){var J={},q=A.getAttribute("ws");
Object.assign(J,q?c.X[q]:c.j);c=GB(A,"mh");c!=null&&(J.PG=c);c=GB(A,"ju");c!=null&&(J.textAlign=c);c=GB(A,"pd");c!=null&&(J.bY=c);c=GB(A,"sd");c!=null&&(J.GH=c);c=MH(A,"wfc");c!=null&&(J.windowColor=c);A=WJ(A,"wfo");A!==void 0&&(J.windowOpacity=A/255);return J},PeV=function(c,A){var J={},q=A.getAttribute("wp");
q&&Object.assign(J,c.D[q]);c=GB(A,"ap");c!=null&&(J.yH=c);c=WJ(A,"cc");c!=null&&(J.VS=c);c=WJ(A,"ah");c!=null&&(J.us=c);c=WJ(A,"rc");c!=null&&(J.uu=c);A=WJ(A,"av");A!=null&&(J.gs=A);return J},sFV=function(c,A,J,q){var Y={};
Object.assign(Y,PeV(c,A));Object.assign(Y,xqe(c,A));q?g.Jp(Y,c.j)?(q=c.T,Y=c.j):q="_"+$W++:q=A.getAttribute("id")||"_"+$W++;c=WJ(A,"t")+J;A=WJ(A,"d")||0x8000000000000;if(Y.bY===2||Y.bY===3)J=Y.uu,Y.uu=Y.VS,Y.VS=J;return new uz(c,A,0,q,Y)},Fw=function(c){oX.call(this);
this.U=c;this.C=new Map;this.j=new Map;this.T=new Map;this.K=new Map},vJ=function(c){c=g.Fa(Math.round(c),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-c.length)+c},Uqe=function(c,A,J,q,Y){q===0&&(q=0x8000000000000);
var p={};A.wpWinPosId&&Object.assign(p,g.x(c.j.get(A.wpWinPosId)));A.wsWinStyleId&&Object.assign(p,g.x(c.T.get(A.wsWinStyleId)));c=A.rcRowCount;c!==void 0&&(p.uu=c);A=A.ccColCount;A!==void 0&&(p.VS=A);if(p.bY===2||p.bY===3)A=p.uu,p.uu=p.VS,p.VS=A;return new uz(J,q,0,Y,p)},QO=function(c,A,J){g.Dr.call(this,c);
this.videoData=A;this.audioTrack=J;this.U=A.N9},Xw=function(c,A,J,q,Y,p,m,E,O,T){Or.call(this,c,A,J,q,Y,p,m,E,O,T);
this.type=1},Za=function(c,A,J){this.trackData=c;
this.Y=J;this.version=this.U=this.j=this.byteOffset=0;this.K=[];this.C=new DataView(this.trackData)},IX=function(c){var A=c.byteOffset;
c.byteOffset+=1;return c.C.getUint8(A)},zB=function(c){var A=c.byteOffset;
c.byteOffset+=4;return c.C.getUint32(A)},Si=function(c,A){oX.call(this);
this.K=c;this.j=A;this.track=this.j.languageName==="CC3"?4:0;this.C=new VPN;this.C.K=1<<this.track},lir=function(c){if(typeof c==="string")return!1;
c=new Za(c,8,0);return fiC(c)},fiC=function(c){if(!(c.byteOffset<c.C.byteLength)||zB(c)!==1380139777)return!1;
c.version=IX(c);if(c.version>1)return!1;IX(c);IX(c);IX(c);return!0},xW=function(c,A,J,q,Y,p,m,E,O,T){Or.call(this,c,A,J,q,Y,p,m,E,O,T);
var R=this;this.type=2;this.nJ=[];this.CJ=this.L=this.eg=0;this.Fl=NaN;this.oJ=0;this.aJ=null;this.CY=new g.hN(this.PY,433,this);this.Y&&(T.createClientVe(this.Y,this,167342),this.Z(this.Y,"click",function(){T.logClick(R.Y)}),c=new g.SU(this.element,!0),g.U(this,c),c.subscribe("hoverstart",function(){T.logVisibility(R.Y,!0)},this));
g.dc(this.element,"ytp-caption-window-rollup");g.U(this,this.CY);g.SL(this.element,"overflow","hidden")},aiV=function(c,A){if(!A)return"";
c.j&&c.K.params.GH!==1&&(A*=-1);return"translate"+(c.j?"X":"Y")+"("+A+"px)"},bmR=function(c){c.nJ=Array.from(c.element.getElementsByClassName("caption-visual-line"));
for(var A=c.K.params.uu,J=0,q=0,Y=c.nJ.length-1;J<A&&Y>-1;){var p=c.nJ[Y];q+=c.j?p.offsetWidth:p.offsetHeight;J++;Y--}c.L=q;A=Math;J=A.max;isNaN(c.Fl)&&((q=c.C.VS)?(Y=g.AH("SPAN"),g.d5(Y,"\u2013".repeat(q)),g.SL(Y,OmH(c,c.C.le)),c.T.appendChild(Y),c.Fl=Y.offsetWidth,c.T.removeChild(Y)):c.Fl=0);q=c.T;c.CJ=J.call(A,c.Fl,c.oJ,(c.j?q.offsetHeight:q.offsetWidth)+1)},tPN=function(c,A){bmR(c);
var J=c.nJ.reduce(function(p,m){return(c.j?m.offsetWidth:m.offsetHeight)+p},0);
J=c.L-J;if(J!==c.eg){var q=J>0&&c.eg===0,Y=J<c.eg;A||isNaN(J)||q||!Y||(g.dc(c.element,"ytp-rollup-mode"),c.Z(c.element,"transitionend",c.PY));g.SL(c.T,"transform",aiV(c,J));c.eg=J}bmR(c)},im9=function(c,A,J,q){var Y=this;
this.J=c;this.j=A;this.logger=J;this.wX=q;this.cf=[];this.vF=[];this.C=null;this.lr={nr8:function(){return Y.C},
s_:function(){return Y.cf}};
c=g.V8(this.J.B().experiments,"html5_override_micro_discontinuities_threshold_ms");this.K=c>0?c:10},n3H=function(c,A){c.C=function(J,q){if(J.info.U){var Y=J;
if(c.vF.length>0){for(Y=c.vF.shift();c.vF.length>0;)Y=g.Ob(Y,c.vF.shift());Y=g.Ob(Y,J)}if(Y){J=Y;try{var p=g.Tp(J)*1E3}catch(T){p=J.info.startTime*1E3}try{var m=g.tII(J)*1E3}catch(T){m=J.info.duration*1E3}if(p<0||m<0)p<0&&(p=J.info.startTime*1E3),m<0&&(m=J.info.duration*1E3);J.info.startTime=p/1E3;J.info.T=p/1E3;J.info.duration=m/1E3;J.info.D=m/1E3;p=c.ow(Y);m=p.Ha;p={formatId:p.formatId,startTimeMs:p.startTimeMs,durationMs:p.durationMs,SV:m,Oe:m};m=yYx(c.cf,p.startTimeMs);var E=(J=m>=0?c.cf[m]:null)?
J.startTimeMs+J.durationMs:0,O=p.startTimeMs+p.durationMs;!J||p.startTimeMs-E>c.K?c.cf.splice(m+1,0,p):(J.durationMs=Math.max(E,O)-J.startTimeMs,J.Oe=Math.max(J.Oe,p.Oe));q(c.cf);q=Y.bG();e2C(c.j,q.buffer.slice(q.byteOffset,q.byteLength+q.byteOffset),A,Y.info.T)}else c.logger.C(350058965,"Empty slice")}else c.vF.push(J)};
c.J.addEventListener("sabrCaptionsDataLoaded",c.C)},yYx=function(c,A){c=g.Zx(c,{startTimeMs:A},function(J,q){return J.startTimeMs-q.startTimeMs});
return c>=0?c:-c-2},KXr=function(c,A){g.Dr.call(this,A);
this.C=c;this.J=A;this.logger=new g.jB("caps");this.j=this.Y=null;this.D=new im9(this.J,this,this.logger,this.C.wX)},e2C=function(c,A,J,q){c.logger.debug(function(){return"SABR captions data received for "+q});
c.Y?c.j==null?c.logger.C(350058965,"Null loaded track meta data at captions data received"):J.oS(A,c.j,q*1E3):c.logger.C(350058965,"Null Representation at captions data received")},h2M=function(c,A){var J=[],q;
for(q in c.C.C)if(c.C.C.hasOwnProperty(q)){var Y=c.C.C[q];if(g.gy(Y,A||null)){var p=Y.info.id,m=p,E="."+p,O="",T="";if(Y=Y.info.captionTrack)p=Y.languageCode,m=Y.displayName,E=Y.vssId,O=Y.kind,T=Y.id;J.push(new g.DS({id:q,languageCode:p,languageName:m,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:E,kind:O,captionId:T}))}}return J},B6R=function(c,A,J){var q=[],Y;
for(Y in c.C.C)if(c.C.C.hasOwnProperty(Y)){var p=c.C.C[Y];if(g.gy(p,J||null)){var m=p.info.captionTrack;m&&m.languageCode===A&&q.push(p)}}return q.length?q[0]:null},cIJ=function(c,A){if(!g.Fxc(c)||c.C!=null&&g.iT$(A,c.C)&&c.C.C.rawcc!=null)return!1;
A=!!c.C&&c.C.isManifestless&&Object.values(c.C.C).some(function(J){return g.gy(J,"386")});
c=!!c.C&&!c.C.isManifestless&&g.mp3(c.C);return A||c},PJ=function(){oX.call(this)},JIw=function(c){var A=AIV.length;
if(c.byteLength<A)return!1;c=new Uint8Array(c,0,A);for(var J=0;J<A;J++)if(AIV[J]!==c[J])return!1;return!0},qvi=function(c,A,J,q,Y,p,m,E,O){switch(m.tagName){case "b":E.bold=!0;
break;case "i":E.italic=!0;break;case "u":E.underline=!0}for(var T=0;T<m.childNodes.length;T++){var R=m.childNodes[T];if(R.nodeType===3)R=new gH(A,J,q,Y.id,R.nodeValue,p||T>0,g.cL(E)?void 0:E),O.push(R),Y.C.push(R);else{var r={};Object.assign(r,E);qvi(c,A,J,q,Y,!0,R,r,O)}}},YvH=function(c){var A=c.split(":");
c=0;A=g.u(A);for(var J=A.next();!J.done;J=A.next())c=c*60+Number(J.value);return c*1E3},pvR=function(c,A,J,q){q=Object.assign({PG:0},q);
return new uz(c,A,J,"_"+$W++,q)},sr=function(c,A){g.P.call(this);
this.J=c;this.o8=A;this.C=null;this.K=this.J.oy();this.logger=new g.jB("caps")},jUN=function(c,A,J){if(typeof A==="string"||lir(A))return[{trackData:A,
pD:J}];if(typeof A==="string"&&A.substring(0,6)==="WEBVTT"||typeof A!=="string"&&JIw(A))return[{trackData:A,pD:J}];var q=new DataView(A);if(q.byteLength<=8||q.getUint32(4)!==1718909296)return[];var Y=g.tbw(q);if(c.K&&Y){var p=g.xn3(Y),m=g.PVL(Y);Y=Y.je;p&&Y&&c.K.yh(Y,p,m)}c=g.Ez(q,1835295092);if(!c||!c.length||!c[0].size)return[];p=[];for(m=0;m<c.length;m++)Y=c[m],Y=new Uint8Array(A,Y.dataOffset,Y.size-(Y.dataOffset-Y.offset)),Y=g.Fi(Y),p.push({trackData:Y,pD:J+m*1E3});mGr(q,p,J);return p=p.filter(function(E){return!!E.trackData})},
mGr=function(c,A,J){var q=g.cB(c,0,1836476516),Y=9E4;
q&&(Y=g.A3(q)||9E4);q=0;for(var p=g.Ez(c,1836019558),m=0;m<p.length;m++){var E=p[m];m<A.length&&(E=g.cB(c,E.dataOffset,1953653094))&&(E=g.cB(c,E.dataOffset,1952867444))&&(E=g.j4(E)/Y*1E3,m===0&&(q=E),A[m].pD=E-q+J||J*m*1E3)}},dGH=function(c,A,J){c.C||(c.C=new PJ);
c=c.C.WP(A,J);Math.random()<.01&&g.Sv(Error("Deprecated subtitles format in web player: WebVTT"));return c},ELR=function(c){var A={};
if(c=g.oj(c))A.lang=c,g.hVi.test(c)&&(A.bY=1);return A},Ur=function(c){g.V5.call(this,c);
var A=this;this.J=c;this.dF=[];this.nJ={};this.Ba={};this.X=!1;this.T="NONE";this.C=this.L=this.CJ=this.xT=this.My=null;this.F1={lY:function(){A.lY()},
oS:function(p,m,E,O){A.oS(p,m,E,O)}};
this.K=null;this.o8=this.J.B();this.videoData=g.x(this.J.getVideoData());this.va=this.J.i$();var J;this.pJ=(J=this.J.getVideoData(1))==null?void 0:g.hu(J);this.j={le:{}};this.Y={le:{}};g.eA(this.videoData)?this.T="OFFLINE":cIJ(this.videoData,this.J)?this.T="SABR_LIVE":g.yqc(this.videoData,this.J)?this.T="LIVE":this.videoData.captionTracks.length?this.T="INNERTUBE":this.videoData.IZ&&(this.T="TTS");this.I8=this.o8.controlsType==="3";this.Xl=new sr(this.J,this.o8);this.Fl=new g.sM(this);this.D=new g.t({S:"div",
V:"ytp-caption-window-container",G:{id:"ytp-caption-window-container"}});this.l$={top:0,right:0,bottom:0,left:0,width:1,height:1};J=null;var q=g.Pd("yt-html5-player-modules::subtitlesModuleData");q&&(J=new g.Fz(q));this.storage=J;var Y;this.oJ=!((Y=c.ri())==null||!Y.Nd());this.U=OaH(this);this.Oq=!this.U&&this.I8&&this.oJ&&(this.T==="LIVE"||this.T==="SABR_LIVE");g.U(this,this.Xl);this.U?this.eg=this.wF=null:(this.wF=new g.Kt(this.l6,void 0,this),g.U(this,this.wF),this.eg=new g.hN(this.f00,2E3,this),
g.U(this,this.eg));g.U(this,this.Fl);g.Sx(this.player,this.D.element,4);g.U(this,this.D);this.U||this.Fl.Z(c,"resize",this.rB);(this.CY=g.SJ(this.o8)&&!g.gt()&&!this.J.isFullscreen()&&!this.U&&!this.Oq)&&this.Fl.Z(c,"resize",this.Dn0);this.Fl.Z(c,"onPlaybackAudioChange",this.LTx);this.Fl.Z(c,g.jo("captions"),function(p){A.onCueRangeEnter(p)});
this.Fl.Z(c,g.dP("captions"),function(p){A.onCueRangeExit(p)});
this.pJ&&this.Fl.Z(c,"videodatachange",function(p,m){A.onVideoDataChange(p,m)});
T7w(this,KCx()||{});this.player.LA("onCaptionsModuleAvailable")},HaC=function(c){if(c.o8.wq===1||c.videoData.Qi===1||g.LN(c.videoData,"yt:cc")==="alwayson")return!0;
if(c.videoData.captionTracks.length)var A=c.getAudioTrack().K;if(c.o8.wq===2){if(g.c1(c.o8))var J=RUe(c);else if(c.storage)try{J=c.storage.get("module-enabled")}catch(Y){c.storage.remove("module-enabled")}else J=null;if(J!=null)return!!J}J=fYR(c.player.getAudioTrack(),g.c1(c.o8));var q=g.LN(c.videoData,"yt:cc");if(rIx(c)===void 0){if(J==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return q?q==="on":!0;if(J==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return q==="on"}else return q==="on";return A==="ON"||
g.LN(c.videoData,"yt:cc")==="on"},fC=function(c,A){if(c.K&&(A===void 0||!A)||!c.videoData.captionTracks.length)return!1;
c=c.getAudioTrack();return!!c.C||c.K==="FORCED_ON"},rIx=function(c){var A=void 0,J=g.aZ(g.l4(),65);
if(g.c1(c.o8)&&J!=null){if(RUe(c)!=null)return!1;A=!J}return A},aX=function(c,A){if(!c.C)return null;
if(c.L&&c.L.T)return c.L.T;A=VLV(c,A);A=g.JB(c.C.K,A);var J=null;if(lYR(c.o8)){var q=c.J.isInline()?void 0:g.Sq("yt-player-caption-sticky-language");for(var Y=[q,c.videoData.captionsLanguagePreference,c.o8.captionsLanguagePreference,g.LN(c.videoData,"yt:cc_default_lang")],p=!1,m=0;m<Y.length;m++){var E=Y[m];if(E){p=!0;for(var O=0;O<A.length;O++)if(g.oj(A[O])===E)return A[O];for(O=0;O<A.length;O++)if(g.oj(A[O]).split("-")[0]===E.split("-")[0])return A[O]}}if(p&&c.C&&(Y=c.C.U,Y.length))for(Y=g.u(Y),
p=Y.next();!p.done;p=Y.next())if(p=p.value,p.languageCode===q){J=p;break}}else for(q=[c.videoData.captionsLanguagePreference,c.o8.captionsLanguagePreference,g.LN(c.videoData,"yt:cc_default_lang")],Y=0;Y<q.length;Y++)for(p=0;p<A.length;p++)if(g.oj(A[p])===q[Y])return A[p];q=null;c.L&&c.L.j&&(q=c.L.j);q||(q=A.find(function(T){return T.isDefault})||null);
q||(q=A[0]||lz(c));q&&J&&g.oj(q).split("-")[0]!==J.languageCode.split("-")[0]&&(q=aYC(q,J));return q},lz=function(c){return c.L&&c.L.C},bz=function(c){var A=lz(c);
return!!A&&c.K===A},N7M=function(c,A){var J=g.x(c.J.ri().nY()).textTracks;
c=c.K.toString();for(var q=0;q<J.length;q++){var Y=J[q];Y.id===c&&(A?Y.mode!=="showing"&&(Y.mode="showing"):Y.mode==="showing"&&(Y.mode="disabled"))}},yO=function(c,A,J){c.loaded&&c.unload();
J!=null&&(c.X=J,c.X&&(g.c1(c.o8)?tQ(c,!!A):iz(c,!!A)));DGM(c,c.K,A,c.X,!1);c.K=A;fC(c)&&(A=lz(c),DGM(c,c.K,A,c.X,!0),c.K=A);var q;kjV(c,(q=c.K)!=null?q:void 0);c.load()},oLi=function(c,A){if(A instanceof uz){var J=c.nJ[A.id];
J&&J.K!==A&&(J.dispose(),delete c.nJ[A.id],J=null);J||(J=gLr(c,A))&&(c.nJ[A.id]=J)}else J=A.windowId,c.Ba[J]||(c.Ba[J]=[]),c.Ba[J].push(A)},gLr=function(c,A){var J=umH(c);
if(!J)return null;var q=c.K?g.oj(c.K):null;q&&g.hVi.test(q)&&(A.params.bY=1);var Y=c.va.getPlayerSize();q=Y.height*c.l$.height;Y=Y.width*c.l$.width;c.o8.playerStyle!=="google-live"||c.j.isDefault||Object.assign(A.params,c.j);switch(A.params.PG!=null?A.params.PG:A.C.length>1?1:0){case 1:return new Xw(A,c.j,c.Y,J.width,J.height,Y,q,c.o8.experiments,c.We.bind(c),c.J);case 2:return new xW(A,c.j,c.Y,J.width,J.height,Y,q,c.o8.experiments,c.We.bind(c),c.J);default:return new Or(A,c.j,c.Y,J.width,J.height,
Y,q,c.o8.experiments,c.We.bind(c),c.J)}},T7w=function(c,A,J){J=J===void 0?!1:J;
var q=ei.le;c.j={};Object.assign(c.j,ei);c.j.le={};Object.assign(c.j.le,q);c.Y={le:{}};var Y=A.backgroundOverride?c.Y:c.j,p=A.background||q.background;CC.test(p);Y.le.background=p;Y=A.colorOverride?c.Y:c.j;p=A.color||q.color;CC.test(p);Y.le.color=p;Y=A.windowColorOverride?c.Y:c.j;p=A.windowColor||ei.windowColor;CC.test(p);Y.windowColor=p;Y=A.backgroundOpacityOverride?c.Y:c.j;p=A.backgroundOpacity;p==null&&(p=q.backgroundOpacity);Y.le.backgroundOpacity=p;Y=A.fontSizeIncrementOverride?c.Y:c.j;p=A.fontSizeIncrement;
p==null&&(p=q.fontSizeIncrement);Y.le.fontSizeIncrement=p;p=A.fontStyleOverride?c.Y:c.j;Y=A.fontStyle;Y==null&&(Y=q.bold&&q.italic?3:q.bold?1:q.italic?2:0);p=p.le;switch(Y){case 1:p.bold=!0;delete p.italic;break;case 2:delete p.bold;p.italic=!0;break;case 3:p.bold=!0;p.italic=!0;break;default:delete p.bold,delete p.italic}Y=A.textOpacityOverride?c.Y:c.j;p=A.textOpacity;p==null&&(p=q.textOpacity);Y.le.textOpacity=p;Y=A.windowOpacityOverride?c.Y:c.j;p=A.windowOpacity;p==null&&(p=ei.windowOpacity);Y.windowOpacity=
p;Y=A.charEdgeStyleOverride?c.Y:c.j;p=A.charEdgeStyle;p==null&&(p=q.charEdgeStyle);Y.le.charEdgeStyle=p;Y=A.fontFamilyOverride?c.Y:c.j;p=A.fontFamily;p==null&&(p=q.fontFamily);Y.le.fontFamily=p;c.loaded&&c.rB();J&&g.zv("yt-player-caption-display-settings",A,2592E3)},$Gx=function(c,A){if(!c.C)return{};
if(A){g.cL(A)||c.Ao(A.vss_id,"m");if(c.U||!g.Je(A))return;if(g.cL(A)){yO(c,null,!0);return}for(var J,q=g.JB(c.C.K,!0),Y=0;Y<q.length;Y++){var p=q[Y];p.languageCode!==A.languageCode||J&&(p.languageName!==A.languageName||(p.captionId||"")!==(A.captionId||"")||g.kp(p)!==A.displayName)||(J=A.translationLanguage?aYC(p,A.translationLanguage):p)}c.Ay(A.position);!J||J===c.K&&c.loaded||(A=g.hs(),q=g.oj(J),A.length&&q===A[A.length-1]||(A.push(q),g.zv("yt-player-caption-language-preferences",A)),lYR(c.o8)&&
!c.J.isInline()&&g.zv("yt-player-caption-sticky-language",q,2592E3),yO(c,J,!0))}else return c.loaded&&c.K&&!bz(c)?g.gC(c.K):{};return""},Wzw=function(c,A,J){A&&!c.CJ?(A=ST9({bY:0,
lang:"en"}),c.CJ=[A,new gH(A.start,A.end-A.start,0,A.id,J!=null?J:"Captions look like this")],c.player.Lo(c.CJ)):!A&&c.CJ&&(wvR(c,c.CJ),c.CJ=null)},wvR=function(c,A){c.player.Eb(A);
A=g.u(A);for(var J=A.next();!J.done;J=A.next())g.oi(c.dF,J.value);ji(c.wF)},kjV=function(c,A){c.o8.W("html5_modify_caption_vss_logging")&&(c.videoData.Rt=A)},umH=function(c){var A=c.va.getVideoContentRect(!0).height,J=c.va.getVideoContentRect(!0).width;
if(!A||!J)return null;A*=c.l$.height;J*=c.l$.width;return{width:J,height:A}},iz=function(c,A){if(c.storage)try{c.storage.set("module-enabled",A)}catch(J){}},tQ=function(c,A){c.J.isInline()||g.zv("yt-player-sticky-caption",A,2592E3)},RUe=function(c){if(!c.J.isInline())return g.Sq("yt-player-sticky-caption")},OaH=function(c){var A,J=!((A=c.J.ri())==null||!A.BR());
return c.I8&&J&&c.T!=="LIVE"&&c.T!=="SABR_LIVE"},VLV=function(c,A){g.P0(c.videoData)&&(A=!0);
A||(A=c.T==="TTS"?!1:c.T==="INNERTUBE"?!1:!0);return A||c.o8.W("web_deprecate_always_includes_asr_setting")&&g.c1(c.o8)?!0:!!g.aZ(g.l4(),66)},DGM=function(c,A,J,q,Y){Y?c.F9(J,!0,"g"):q?A?c.F9(J,!!J,"m"):J&&c.F9(J,!0,"m"):!A&&J&&c.F9(J,!0,"s")};
g.Dr.prototype.h4=g.mY(77,function(){return!1});
g.Dr.prototype.Uz=g.mY(76,function(){});
g.kt.prototype.Uz=g.mY(75,function(c,A,J){var q=this;this.Uq();A=this.AO(c,A);var Y=this.a8.B().W("html5_report_captions_ctmp_qoe"),p=(0,g.b)();this.Ry();UDH(this,A,{format:"RAW",onSuccess:function(m){q.C=null;if(Y){var E=(m.responseText.length/1024).toFixed(),O=(0,g.b)();q.videoData.b$("capresp",{ms:O-p,kb:E})}J.oS(m.responseText,c)},
onError:Y?function(m){var E;m=(E=m==null?void 0:m.status)!=null?E:0;q.videoData.b$("capfail",{status:m})}:void 0,
withCredentials:!0})});
g.ol.prototype.Uz=g.mY(74,function(c,A,J){var q=this;this.Uq();A=this.AO(c,A);this.Ry();this.C=g.C2(A,{format:"RAW",onSuccess:function(Y){q.C=null;J.oS(Y.responseText,c)},
withCredentials:!0})});
g.t_.prototype.Qb=g.mY(73,function(){for(var c=g.yy(document,"track",void 0,this.C),A=0;A<c.length;A++)g.mf(c[A])});
g.Xn.prototype.Qb=g.mY(72,function(){this.mediaElement.Qb()});
g.t_.prototype.Nd=g.mY(71,function(){return!(!this.C.textTracks||!this.C.textTracks.addEventListener)});
g.Xn.prototype.Nd=g.mY(70,function(){return this.mediaElement.Nd()});
g.t_.prototype.BR=g.mY(69,function(){return!!this.C.textTracks});
g.Xn.prototype.BR=g.mY(68,function(){return this.mediaElement.BR()});
g.t_.prototype.N7=g.mY(67,function(c){for(var A=0;A<c.length;A++)this.C.appendChild(c[A])});
g.Xn.prototype.N7=g.mY(66,function(c){this.mediaElement.N7(c)});
g.yk.prototype.yh=g.mY(65,function(c,A,J){this.I4.yh(c,A,J)});
g.tq.prototype.yh=g.mY(64,function(c,A,J){this.K.set(c,{mB:A,lD:J})});
g.i8.prototype.yh=g.mY(63,function(c,A,J){this.dF.yh(c,A,J)});
g.yk.prototype.im=g.mY(62,function(c){return this.I4.im(c)});
g.i8.prototype.im=g.mY(61,function(c){var A=2;this.L.has(c)?A=0:g.Pq$(this,c)&&(A=1);return A});
g.MY.prototype.f2=g.mY(49,function(c){var A=this.app.yp({playerType:void 0});return A?A.f2(c):!1});
g.lU.prototype.f2=g.mY(48,function(c){return this.kT.Mu.f2(c)});
g.XM.prototype.f2=g.mY(47,function(c){return this.cK().some(function(A){return A.namespace===c})});
g.x1.prototype.f2=g.mY(46,function(){return!1});
g.MY.prototype.Ao=g.mY(44,function(c,A){this.app.mT().Ao(c,A)});
g.lU.prototype.Ao=g.mY(43,function(c,A){this.kT.Ao(c,A)});
g.rD.prototype.Ao=g.mY(42,function(c,A){c=[c,A];g.R6(this,g.iD(this.provider),"cfi",c)});
g.MQ.prototype.Ao=g.mY(41,function(c,A){this.qoe&&this.qoe.Ao(c,A)});
g.J_.prototype.Ao=g.mY(40,function(c,A){this.Zt().Ao(c,A)});
g.x1.prototype.Ao=g.mY(39,function(){});
g.MY.prototype.F9=g.mY(38,function(c,A,J){this.app.mT().F9(c,A,J)});
g.lU.prototype.F9=g.mY(37,function(c,A,J){this.kT.F9(c,A,J)});
g.rD.prototype.F9=g.mY(36,function(c,A,J){if(this.eg!==c||this.Nn!==A)A=A==="rawcc"?"":A,J=[c,A,this.eg,J],g.R6(this,g.iD(this.provider),"cfs",J),this.eg=c,this.Nn=A});
g.MQ.prototype.F9=g.mY(35,function(c,A,J){this.qoe&&this.qoe.F9(c,A,J)});
g.J_.prototype.F9=g.mY(34,function(c,A,J){this.Zt().F9(c,A,J)});
g.x1.prototype.F9=g.mY(33,function(){});
g.bD.prototype.j$=g.mY(20,function(){return this.CJ});
g.Vu.prototype.j$=g.mY(19,function(){return this.mT().oy()});
g.MY.prototype.oy=g.mY(18,function(){return this.app.j$()});
g.lU.prototype.oy=g.mY(17,function(){return this.kT.oy()});
g.J_.prototype.oy=g.mY(16,function(){var c;return((c=this.loader)==null?void 0:c.j$())||null});
g.x1.prototype.oy=g.mY(15,function(){return null});
g.sU.prototype.B2=g.mY(1,function(c){return(c=this.M0(c))?c.C:0});
g.Vv.prototype.B2=g.mY(0,function(){return 0});
var ycH=/#(.)(.)(.)/,iVH=/^#(?:[0-9a-f]{3}){1,2}$/i,JYw={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kk_Cyrl:"Kazakh (Cyrillic)",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kok_Deva:"Konkani (Devanagari)",kok_Latn:"Konkani (Latin)",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",
kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",
man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",
my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",
nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",
raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",
sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",
ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",
tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",
wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",
zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};dH.prototype.contains=function(c){c=g.Zx(this.segments,c);return c>=0||c<0&&(-c-1)%2===1};
dH.prototype.length=function(){return this.segments.length/2};
g.k(BnH,g.P);g.D=BnH.prototype;g.D.rF=function(){g.P.prototype.rF.call(this);this.j&&this.j.cancel()};
g.D.vC=function(){this.seekTo(this.player.getCurrentTime())};
g.D.seekTo=function(c){c-=this.player.mR();var A=this.C;this.C=g.r9(this.CJ.lh(c).Gx);A!==this.C&&this.L&&this.L()};
g.D.reset=function(){this.T=new dH;this.Y=-1;this.j&&(this.j.cancel(),this.j=null)};
g.D.Oj=function(){this.Uq();var c;if(c=this.C!=null)c=this.C,c=c.C.HN(c);if(c&&!this.j&&!(this.C&&this.C.startTime-this.player.getCurrentTime()>30)){c=this.C;c=g.x(c.C.KP(c));var A=c.Gx[0],J;if((J=this.player.getVideoData())==null?0:J.enableServerStitchedDai)if(J=this.player.oy()){var q=A.C.info.id,Y=A.Ha,p=c.Gx[0].T;if(this.policy.dF){if(J=J.zm(p,Y,q,3))c.T=J}else if(q=J.G3(p,Y,q,3))if(J=J.im(Y),J===0)q&&(c.C=new g.Q1(q));else if(J===2){this.D.start();cYR(this)&&this.seekTo(this.player.getCurrentTime());
return}}A.C.index.nu(A.Ha)?(this.T.contains(c.Gx[0].Ha)||AYC(this,c),this.C=g.r9(c.Gx)):cYR(this)&&this.seekTo(this.player.getCurrentTime())}this.D.start()};
g.k(Er,g.Dr);g.D=Er.prototype;g.D.Uz=function(c,A,J){var q=this;this.Ry();A=YTN(this,c.getId());A||(A=c.languageCode,A=this.C.isManifestless?pWV(this,A,"386"):pWV(this,A));if(A){var Y=(A.index.B2(A.index.q0())-A.index.getStartTime(A.index.q0()))*1E3,p=this.J.B(),m=new g.VJ8(p),E=function(){q.j&&q.j.reset();q.Y=!0};
p.W("html5_keep_caption_data_after_seek")&&(E=null);this.j=new BnH(m,this.J,A,function(O,T){J.oS(O,c,T,Y)},this.D||g.Ag(A.info),E)}};
g.D.h4=function(){var c=this.Y;this.Y=!1;return c};
g.D.yT=function(c){var A=this.J.B().W("html5_fallback_if_rawcc_missing");var J=this.C.C.rawcc!=null;if(!this.D||!J&&A)A=this.C.isManifestless?qTM(this,"386"):qTM(this);else{if(!J){this.logger.C(386248249,"rawcc used but unavailable");return}A=[new g.DS({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.DS({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}A=g.u(A);
for(J=A.next();!J.done;J=A.next())g.Ny(this.K,J.value);c.lY()};
g.D.Ry=function(){this.j&&(this.j.dispose(),this.j=null)};
g.D.AO=function(){return""};
g.D.JR=function(){this.j&&(this.j.reset(),this.J.hm("captions"))};
var CC=/^#(?:[0-9a-f]{3}){1,2}$/i;var dqH=["left","right","center","justify"];g.k(Or,g.t);g.D=Or.prototype;g.D.Og=function(c,A){this.I8=c;this.Xl=A;var J=g.iP(this.element,this.element.parentElement);this.pJ=c-J.x;this.My=A-J.y};
g.D.FW=function(c,A){if(c!==this.I8||A!==this.Xl){g.jS(this.element,"ytp-dragging")||g.dc(this.element,"ytp-dragging");var J=g.eL(this.element);c=c-this.pJ-.02*this.playerWidth;var q=A-this.My-.02*this.playerHeight,Y=(c+J.width/2)/this.maxWidth*3;Y=Math.floor(g.Fa(Y,0,2));var p=(q+J.height/2)/this.maxHeight*3;p=Math.floor(g.Fa(p,0,2));A=Y+p*3;c=(c+Y/2*J.width)/this.maxWidth;c=g.Fa(c,0,1)*100;J=(q+p/2*J.height)/this.maxHeight;J=g.Fa(J,0,1)*100;this.K.params.yH=A;this.K.params.gs=J;this.K.params.us=
c;this.K.params.isDefault=!1;this.C.yH=A;this.C.gs=J;this.C.us=c;this.C.isDefault=!1;this.l$.yH=A;this.l$.gs=J;this.l$.us=c;this.l$.isDefault=!1;this.fd()}};
g.D.Ti=function(){g.Ot(this.element,"ytp-dragging")};
g.D.fd=function(){this.Mb(this.D)};
g.D.Mb=function(c){var A=this.va?0:Math.min(this.fL(),this.maxWidth),J=this.ez(),q=this.va;if(q){var Y=getComputedStyle(this.T.parentNode);Y=TB(Y.borderLeftWidth)+TB(Y.borderRightWidth)+TB(Y.paddingLeft)+TB(Y.paddingRight)}else Y=0;var p=Y;Y="";this.K.params.bY===3&&(Y="rotate(180deg)");var m=q?"calc(96% - "+p+"px)":"96%";g.SL(this.element,{top:0,left:0,right:"",bottom:"",width:A?A+"px":"",height:J?J+"px":"","max-width":m,"max-height":m,margin:"",transform:""});this.Ww(c);Y={transform:Y,top:"",left:"",
width:A?A+"px":"",height:J?J+"px":"","max-width":"","max-height":""};var E=this.C.us*.96+2;m=this.C.yH;switch(m){case 0:case 3:case 6:(q=this.C.le.fontSizeIncrement)&&q>0&&this.C.bY!==2&&this.C.bY!==3&&(E=Math.max(E/(1+q*2),2));Y.left=E+"%";break;case 1:case 4:case 7:Y.left=E+"%";E=this.T.offsetWidth;A||E?(A=A||E+1,Y.width=A+"px",Y["margin-left"]=q?A/-2-p/2+"px":A/-2+"px"):Y.transform+=" translateX(-50%)";break;case 2:case 5:case 8:Y.right=100-E+"%"}q=this.C.gs*.96+2;switch(m){case 0:case 1:case 2:Y.top=
q+"%";break;case 3:case 4:case 5:Y.top=q+"%";(J=J||this.element.clientHeight)?(Y.height=J+"px",Y["margin-top"]=J/-2+"px"):Y.transform+=" translateY(-50%)";break;case 6:case 7:case 8:Y.bottom=100-q+"%"}g.SL(this.element,Y);if(this.Y){J=this.T.offsetHeight;q=1;for(A=0;A<c.length;A++)Y=c[A],typeof Y.text==="string"&&(q+=Y.text.split("\n").length-1,Y.append||A===0||q++);J/=q;this.Y.style.height=J+"px";this.Y.style.width=J+"px";this.element.style.paddingLeft=J+5+"px";this.element.style.paddingRight=J+
5+"px";c=Number(this.element.style.marginLeft.replace("px",""))-J-5;J=Number(this.element.style.marginRight.replace("px",""))-J-5;this.element.style.marginLeft=c+"px";this.element.style.marginRight=J+"px"}};
g.D.Ww=function(c){var A;for(A=0;A<c.length&&c[A]===this.D[A];A++);if(this.Oq||this.D.length>A)A=0,this.Oq=!1,this.D=[],this.X=this.wF=this.dF=null,g.Yk(this.T);for(;A<c.length;A++)rY9(this,c[A])};
g.D.fL=function(){return 0};
g.D.ez=function(){return 0};
g.D.toString=function(){return g.t.prototype.toString.call(this)};VPN.prototype.clear=function(){this.j=this.time=this.mode=0;this.C=[];this.reset()};
VPN.prototype.reset=function(){this.mode=0;this.T.reset(0);this.U.reset(1)};
var N6O=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];RX.prototype.set=function(c){this.type=c};
RX.prototype.get=function(){return this.type};
rH.prototype.clear=function(){this.state=0};
rH.prototype.update=function(){this.state=this.state===2?1:0};
rH.prototype.RZ=function(){return this.state!==0};
rH.prototype.matches=function(c,A){return this.RZ()&&c===this.Ho&&A===this.WN};
u9N.prototype.reset=function(){this.timestamp=this.C=0};
HJ.prototype.updateTime=function(c){for(var A=1;A<=15;++A)for(var J=1;J<=32;++J)this.j[A][J].timestamp=c};
HJ.prototype.debugString=function(){for(var c="\n",A=1;A<=15;++A){for(var J=1;J<=32;++J){var q=this.j[A][J];c=q.C===0?c+"_":c+String.fromCharCode(q.C)}c+="\n"}return c};
HJ.prototype.reset=function(c){for(var A=0;A<=15;A++)for(var J=0;J<=32;J++)this.j[A][J].reset();this.T=c;this.C=0;this.K=this.row=1};
var $qN=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],wWJ=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],WXR=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],LX9=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];FXH.prototype.reset=function(c,A){this.U=A;this.style.set(2);this.K=this.Y;this.T=this.D;this.C=this.K;var J=(c<<2)+(A<<1);this.Y.reset(J);this.D.reset(J);this.text.reset((c<<2)+(A<<1)+1)};
HmM.prototype.reset=function(c){this.U=c;this.K.clear();this.T=this.j;this.j.reset(c,0);this.Y.reset(c,1)};ZmR.prototype.T=function(){};g.k(gH,g.p$);gH.prototype.toString=function(){return g.p$.prototype.toString.call(this)};g.k(oX,g.P);oX.prototype.WP=function(){return[]};
oX.prototype.reset=function(){};g.k(uz,g.p$);uz.prototype.toString=function(){return g.p$.prototype.toString.call(this)};
var $W=0;g.k(wH,oX);wH.prototype.reset=function(){this.Y={};this.K=this.C=null;this.U=!0};
wH.prototype.WP=function(c,A){c=c.firstChild;c.getAttribute("format");A=A||0;Number.isFinite(A);c=Array.from(c.childNodes);c=g.u(c);for(var J=c.next();!J.done;J=c.next())if(J=J.value,J.nodeType===1)switch(J.tagName){case "head":var q=J;break;case "body":var Y=J}if(q)for(q=Array.from(q.childNodes),q=g.u(q),c=q.next();!c.done;c=q.next())if(c=c.value,c.nodeType===1)switch(c.tagName){case "pen":J=c.getAttribute("id");var p=this.pens,m={},E=c.getAttribute("p");E&&Object.assign(m,this.pens[E]);E=LC(c,"b");
E!=null&&(m.bold=E);E=LC(c,"i");E!=null&&(m.italic=E);E=LC(c,"u");E!=null&&(m.underline=E);E=GB(c,"et");E!=null&&(m.charEdgeStyle=E);E=GB(c,"of");E!=null&&(m.offset=E);E=MH(c,"bc");E!=null&&(m.background=E);E=MH(c,"ec");E!=null&&(m.Pw=E);E=MH(c,"fc");E!=null&&(m.color=E);E=GB(c,"fs");E!=null&&E!==0&&(m.fontFamily=E);E=WJ(c,"sz");E!==void 0&&(m.fontSizeIncrement=E/100-1);E=WJ(c,"bo");E!==void 0&&(m.backgroundOpacity=E/255);E=WJ(c,"fo");E!==void 0&&(m.textOpacity=E/255);E=GB(c,"rb");E!=null&&E!==10&&
E!==0&&(m.H$=E>10?E-1:E);c=GB(c,"hg");c!=null&&(m.H9=c);p[J]=m;break;case "ws":J=c.getAttribute("id");this.X[J]=xqe(this,c);break;case "wp":J=c.getAttribute("id"),this.D[J]=PeV(this,c)}if(Y){q=[];Y=Array.from(Y.childNodes);Y=g.u(Y);for(c=Y.next();!c.done;c=Y.next())if(c=c.value,c.nodeType===1)switch(c.tagName){case "w":this.C=sFV(this,c,A,!1);(c=this.Y[this.C.id])&&c.end>this.C.start&&(c.end=this.C.start);this.Y[this.C.id]=this.C;q.push(this.C);break;case "p":var O=c;E=A;J=[];p=O.getAttribute("w")||
this.T;m=!!LC(O,"a");E=(WJ(O,"t")||0)+E;var T=WJ(O,"d")||5E3;m||(!this.U&&this.K&&this.K.windowId===p&&this.K.end>E&&(this.K.end=E),this.K&&this.K.text==="\n"&&(this.K.text=""));var R=m?6:5,r=O.getAttribute("p");r=r?this.pens[r]:null;var H=Array.from(O.childNodes);H.length&&(this.U=O.getAttribute("d")!=null);for(O=0;O<H.length;O++){var V=H[O],N=void 0;O>0&&(m=!0);var w=void 0;V.nodeType===1&&(w=V);if(w&&w.tagName==="s"){if((V=(V=w.getAttribute("p"))?this.pens[V]:null)&&V.H$&&(V.H$===1?(V=H.slice(O,
O+4),V.length===4&&(N=z2V(E,T,p,m,R,V,this.pens),O+=3)):N=z2V(E,T,p,m,R,[w],this.pens)),!N){var W=w;N=E;w=T;V=p;var C=m,G=R,Z=W.textContent?W.textContent:"",I=W.getAttribute("p");I=I?this.pens[I]:null;W=WJ(W,"t")||0;N=new gH(N+W,w-W,G,V,Z,C,I)}}else N=new gH(E,T,R,p,V.textContent||"",m,r);J.push(N);this.K=N}if(J.length>0)for(J[0].windowId===this.T&&(this.C=sFV(this,c,A,!0),q.push(this.C)),c=g.u(J),J=c.next();!J.done;J=c.next())J=J.value,J.windowId=this.C.id,this.C.C.push(J),q.push(J)}A=q}else A=[];
return A};var LzR=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.k(Fw,oX);Fw.prototype.reset=function(){this.K.clear()};
Fw.prototype.WP=function(c,A){var J=JSON.parse(c);if(!J)return[];if(J.pens){c=0;for(var q=g.u(J.pens),Y=q.next();!Y.done;Y=q.next()){Y=Y.value;var p={},m=Y.pParentId;m&&Object.assign(p,g.x(this.C.get(m)));Y.bAttr&&(p.bold=!0);Y.iAttr&&(p.italic=!0);Y.uAttr&&(p.underline=!0);m=Y.ofOffset;m!=null&&(p.offset=m);Y.szPenSize!==void 0&&(p.fontSizeIncrement=Y.szPenSize/100-1);m=Y.etEdgeType;m!=null&&(p.charEdgeStyle=m);Y.ecEdgeColor!==void 0&&(p.Pw=vJ(Y.ecEdgeColor));m=Y.fsFontStyle;m!=null&&m!==0&&(p.fontFamily=
m);Y.fcForeColor!==void 0&&(p.color=vJ(Y.fcForeColor));Y.foForeAlpha!==void 0&&(p.textOpacity=Y.foForeAlpha/255);Y.bcBackColor!==void 0&&(p.background=vJ(Y.bcBackColor));Y.boBackAlpha!==void 0&&(p.backgroundOpacity=Y.boBackAlpha/255);(m=Y.rbRuby)&&m!==10&&(p.H$=m>10?m-1:m,p.textEmphasis=LzR.get(p.H$));Y.hgHorizGroup&&(p.H9=Y.hgHorizGroup);this.C.set(c++,p)}}if(J.wsWinStyles)for(c=0,q=g.u(J.wsWinStyles),Y=q.next();!Y.done;Y=q.next())Y=Y.value,p={},(m=Y.wsParentId)?Object.assign(p,g.x(this.T.get(m))):
Object.assign(p,this.U),Y.mhModeHint!==void 0&&(p.PG=Y.mhModeHint),Y.juJustifCode!==void 0&&(p.textAlign=Y.juJustifCode),Y.pdPrintDir!==void 0&&(p.bY=Y.pdPrintDir),Y.sdScrollDir!==void 0&&(p.GH=Y.sdScrollDir),Y.wfcWinFillColor!==void 0&&(p.windowColor=vJ(Y.wfcWinFillColor)),Y.wfoWinFillAlpha!==void 0&&(p.windowOpacity=Y.wfoWinFillAlpha/255),this.T.set(c++,p);if(J.wpWinPositions)for(c=0,q=g.u(J.wpWinPositions),Y=q.next();!Y.done;Y=q.next())Y=Y.value,p={},(m=Y.wpParentId)&&Object.assign(p,g.x(this.j.get(m))),
Y.ahHorPos!==void 0&&(p.us=Y.ahHorPos),Y.apPoint!==void 0&&(p.yH=Y.apPoint),Y.avVerPos!==void 0&&(p.gs=Y.avVerPos),Y.ccCols!==void 0&&(p.VS=Y.ccCols),Y.rcRows!==void 0&&(p.uu=Y.rcRows),this.j.set(c++,p);if(J.events){c=[];J=g.u(J.events);for(q=J.next();!q.done;q=J.next()){var E=q.value;Y=(E.tStartMs||0)+A;p=E.dDurationMs||0;if(E.id)m=String(E.id),q=Uqe(this,E,Y,p,m),c.push(q),this.K.set(m,q);else{E.wWinId?m=E.wWinId.toString():(m="_"+$W++,q=Uqe(this,E,Y,p,m),c.push(q),this.K.set(m,q));q=c;var O=E;
p===0&&(p=5E3);E=g.x(this.K.get(m));var T=!!O.aAppend,R=T?6:5,r=O.segs,H=null;O.pPenId&&(H=g.x(this.C.get(O.pPenId)));for(O=0;O<r.length;O++){var V=r[O],N=V.utf8;if(N){var w=V.tOffsetMs||0,W=null;V.pPenId&&(W=g.x(this.C.get(V.pPenId)));if((E.params.PG!=null?E.params.PG:E.C.length>1?1:0)===2&&T&&N==="\n")continue;V=null;var C=[],G;if(G=W&&W.H$===1){G=r;var Z=O;if(Z+3>=G.length||!G[Z+1].pPenId||!G[Z+2].pPenId||!G[Z+3].pPenId)G=!1;else{var I=G[Z+1].pPenId;(I=this.C.get(I))&&I.H$&&I.H$===2?(I=G[Z+2].pPenId,
I=this.C.get(I),!I||!I.H$||I.H$<3?G=!1:(I=G[Z+3].pPenId,G=(I=this.C.get(I))&&I.H$&&I.H$===2?!0:!1)):G=!1}}if(G)w=r[O+1].utf8,V=r[O+3].utf8,G=r[O+2].utf8,Z=g.x(this.C.get(r[O+2].pPenId)),N=Iiw(N,w,G,V,Z),V=new gH(Y,p,R,m,N,T,W),O+=3;else{if(N.indexOf("<")>-1){var f=void 0;C=W;G=H;Z=Y;I=p;var K=w,y=R,q8=T,pI=[],cw=g.x(g.et("<html>"+N+"</html>"));if(!cw.getElementsByTagName("parsererror").length&&((f=cw.firstChild)==null?0:f.childNodes.length))for(f=g.u(cw.firstChild.childNodes),cw=f.next();!cw.done;cw=
f.next()){cw=cw.value;var EL=void 0,h=void 0,wa=(h=(EL=cw.textContent)==null?void 0:EL.replace(/\n/g,""))!=null?h:"";if(cw.nodeType!==3||wa&&wa.match(/^ *$/)==null){EL={};Object.assign(EL,C||G);h=void 0;switch((h=cw)==null?void 0:h.tagName){case "b":EL.bold=!0;break;case "i":EL.italic=!0;break;case "u":EL.underline=!0}pI.push(new gH(Z+K,I-K,y,E.id,wa,q8,EL))}}C=pI}C.length||(C=[new gH(Y+w,p-w,R,E.id,N,T,W||H)])}if(C.length)for(T=g.u(C),W=T.next();!W.done;W=T.next())W=W.value,q.push(W),E.C.push(W);
else V&&(q.push(V),E.C.push(V))}T=!0}}}A=c}else A=[];return A};g.k(QO,g.Dr);QO.prototype.Uz=function(c,A,J){tOr(this.videoData.videoId,c.vssId,J.oS)};
QO.prototype.yT=function(c){if(this.audioTrack)for(var A=g.u(this.audioTrack.captionTracks),J=A.next();!J.done;J=A.next())g.Ny(this.K,J.value);c.lY()};g.k(Xw,Or);Xw.prototype.Ww=function(c){var A=this.K.C;Or.prototype.Ww.call(this,c);for(c=c.length;c<A.length;c++){var J=A[c];if(p&&J.C===Y)var q=p;else{q={};Object.assign(q,J.C);Object.assign(q,Gjx);var Y=J.C;var p=q}rY9(this,J,q)}};
var Gjx={HU:!0};g.k(Za,ZmR);Za.prototype.T=function(c,A,J,q,Y){if(J<q){var p="_"+$W++;J=J/1E3-this.Y;q=q/1E3-this.Y;c=new uz(J,q-J,5,p,{textAlign:0,yH:0,us:A*2.5,gs:c*5.33});Y=new gH(J,q-J,5,p,Y);this.K.push(c);this.K.push(Y)}};
g.k(Si,oX);Si.prototype.WP=function(c){c=new Za(c,c.byteLength,this.K);if(fiC(c)){for(;c.byteOffset<c.C.byteLength;)for(c.version===0?c.j=zB(c)*(1E3/45):c.version===1&&(c.j=zB(c)*4294967296+zB(c)),c.U=IX(c);c.U>0;c.U--){var A=IX(c),J=IX(c),q=IX(c);A&4&&(A&3)===this.track&&(this.track===0||this.track===1)&&(A=this.C,A.C.push({time:c.j,type:this.track,Yu:J,wU:q,order:A.C.length}))}o3w(this.C,c);return c.K}return[]};
Si.prototype.reset=function(){this.C.clear()};g.k(xW,Or);g.D=xW.prototype;g.D.fd=function(){g.cd(this.CY)};
g.D.PY=function(){this.element.removeEventListener("transitionend",this.PY,!1);g.Ot(this.element,"ytp-rollup-mode");this.Mb(this.aJ,!0)};
g.D.ez=function(){return this.j?this.CJ:this.L};
g.D.fL=function(){return this.j?this.L:this.CJ};
g.D.Mb=function(c,A){this.aJ=c;if(this.K.params.uu){for(var J=0,q=0;q<this.D.length&&J<c.length;q++)this.D[q]===c[J]&&J++;J>0&&J<c.length&&(c=this.D.concat(c.slice(J)));this.oJ=this.CJ;this.L=this.CJ=0;Or.prototype.Mb.call(this,c);tPN(this,A)}Or.prototype.Mb.call(this,c)};im9.prototype.unload=function(){this.C!=null&&(this.J.removeEventListener("sabrCaptionsDataLoaded",this.C),this.C=null);this.cf=[];this.J.publish("sabrCaptionsBufferedRangesUpdated",this.cf)};
im9.prototype.ow=function(c){return{formatId:g.qu(c.info.C.info,this.wX),Ha:c.info.Ha+(this.wX?0:1),startTimeMs:c.info.T*1E3,durationMs:c.info.D*1E3}};g.k(KXr,g.Dr);g.D=KXr.prototype;g.D.Uz=function(c,A,J){this.Ry();A=c.getId();A=A!=null&&A in this.C.C?this.C.C[A]:null;A||(A=c.languageCode,A=this.C.isManifestless?B6R(this,A,"386"):B6R(this,A));A&&(this.j=c,this.Y=A,n3H(this.D,J),this.J.publish("sabrCaptionsTrackChanged",g.qu(A.info,this.C.wX)))};
g.D.yT=function(c){var A=this.C.isManifestless?h2M(this,"386"):h2M(this);A=g.u(A);for(var J=A.next();!J.done;J=A.next())g.Ny(this.K,J.value);c.lY()};
g.D.Ry=function(){this.j&&(this.j=this.Y=null,this.D.unload(),this.J.publish("sabrCaptionsTrackChanged",null))};
g.D.AO=function(){return""};
g.D.JR=function(){this.J.hm("captions")};var AIV="WEBVTT".split("").map(function(c){return c.charCodeAt(0)});
g.k(PJ,oX);
PJ.prototype.WP=function(c,A){c instanceof ArrayBuffer&&(c=g.Fi(new Uint8Array(c)));var J=[];c=c.split(CPO);for(var q=1;q<c.length;q++){var Y=c[q],p=A;if(Y!==""&&!MLw.test(Y)){var m=Fz9.exec(Y);if(m&&m.length>=4){var E=YvH(m[1]),O=YvH(m[2])-E;E+=p;var T=(m=m[3])?m.split(" "):[];m={};var R=null;var r="";var H=null,V="";T=g.u(T);for(var N=T.next();!N.done;N=T.next())if(N=N.value.split(":"),N.length===2){var w=N[1];switch(N[0]){case "line":N=w.split(",");N[0].endsWith("%")&&(R=N[0],m.gs=Number.parseInt(R,10),
N.length===2&&(r=N[1].trim()));break;case "position":N=w.split(",");H=N[0];m.us=Number.parseInt(H,10);N.length===2&&(V=N[1].trim());break;case "align":switch(w){case "start":m.textAlign=0;break;case "middle":m.textAlign=2;break;case "end":m.textAlign=1}}}R||r||(r="end");if(!H)switch(m.textAlign){case 0:m.us=0;break;case 1:m.us=100;break;case 2:m.us=50}if(m.textAlign!=null){R=0;switch(r){case "center":R+=3;break;case "end":R+=6;break;default:R+=0}switch(V){case "line-left":R+=0;break;case "center":R+=
1;break;case "line-right":R+=2;break;default:switch(m.textAlign){case 0:R+=0;break;case 2:R+=1;break;case 1:R+=2}}r=R<0||R>8?7:R;m.yH=r}Y=Y.substring(Fz9.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");V=m;m=Y;Y={};if(m.indexOf("<")<0&&m.indexOf("&")<0)p=pvR(E,O,5,V),O=new gH(E,O,5,p.id,m,!1,g.cL(Y)?void 0:Y),J.push(p),J.push(O),p.C.push(O);else for(r=m.split(vLM),r.length===1?(m=5,V=pvR(E,O,m,V)):(R=m=6,V=Object.assign({VS:32},V),V=new uz(E,O,R,"_"+$W++,V)),J.push(V),R=E,H=0;H<r.length;H++)T=r[H],
H%2===0?(N=g.x(g.et("<html>"+T+"</html>")),N.getElementsByTagName("parsererror").length?(w=N.createElement("span"),w.appendChild(N.createTextNode(T))):w=N.firstChild,qvi(this,R,O-(R-E),m,V,H>0,w,Y,J)):R=YvH(T)+p}Fz9.lastIndex=0}}return J};
var MLw=/^NOTE/,CPO=/(?:\r\n|\r|\n){2,}/,Fz9=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),vLM=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.Z7.bW(PJ,{WP:"wvppt"});g.k(sr,g.P);
sr.prototype.WP=function(c,A,J,q){q=q||0;J=jUN(this,c,J||0);c=[];try{for(var Y=g.u(J),p=Y.next();!p.done;p=Y.next()){var m=p.value,E=m.trackData,O=m.pD,T=this.o8.W("safari_live_drm_captions_fix");if(typeof E!=="string"){J=c;var R=J.concat;if(T&&JIw(E))var r=dGH(this,E,O);else{var H=A,V=E,N=O,w=q;if(!lir(V))throw Error("Invalid binary caption track data");this.C||(this.C=new Si(w,H));r=this.C.WP(V,N)}var W=R.call(J,r)}else{if(E.substring(0,6)==="WEBVTT")var C=c.concat(dGH(this,E,O));else{J=c;var G=
J.concat;a:{H=A;if(E[0]==="{")try{this.C||(this.C=new Fw(ELR(H)));var Z=this.C.WP(E,O);break a}catch(pI){g.zg(pI);Z=[];break a}var I=g.et(E);if(!I||!I.firstChild){var f=Error("Invalid caption track data");f.params=E;throw f;}if(I.firstChild.tagName==="timedtext"){if(Number(I.firstChild.getAttribute("format"))===3){V=I;this.C||(this.C=new wH(ELR(H),this.o8));Z=this.C.WP(V,O);break a}var K=Error("Unsupported subtitles format in web player (Format2)");K.params=E;throw K;}if(I.firstChild.tagName==="transcript"){var y=
Error("Unsupported subtitles format in web player (Format1)");y.params=E;throw y;}var q8=Error("Invalid caption track data");q8.params=E;throw q8;}C=G.call(J,Z)}W=C}c=W}return c}catch(pI){return this.logger.C(187101178,"Captions parsing failed: "+pI.message+". "),this.clear(),[]}};
sr.prototype.clear=function(){this.C&&this.C.dispose();this.C=null};
sr.prototype.reset=function(){this.C&&this.C.reset()};
sr.prototype.rF=function(){g.P.prototype.rF.call(this);this.clear()};var ei={windowColor:"#080808",windowOpacity:0,textAlign:2,yH:7,us:50,gs:100,isDefault:!0,le:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.k(Ur,g.V5);g.D=Ur.prototype;g.D.rF=function(){if(this.U||this.Oq){var c=this.J.ri();c&&!c.Uq()&&c.Qb()}else Wzw(this,!1);g.V5.prototype.rF.call(this)};
g.D.aV=function(){return this.o8.W("html5_honor_caption_availabilities_in_audio_track")&&this.T!=="LIVE"&&this.T!=="SABR_LIVE"};
g.D.JC=function(){if(this.I8)return this.U||this.Oq;var c=this.getAudioTrack();if(this.aV()){if(!c.captionTracks.length)return!1;if(!this.C)return!0}c=fYR(c,g.c1(this.o8));return c==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:c==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?fC(this):rIx(this)||fC(this)?!0:HaC(this)};
g.D.load=function(){g.V5.prototype.load.call(this);this.L=this.getAudioTrack();if(this.C)this.K&&(this.Xl.clear(),this.U?N7M(this,!0):this.player.getPresentingPlayerType()!==3&&this.C.Uz(this.K,"json3",this.F1),this.U||this.Oq||bz(this)||this.player.LA("captionschanged",g.gC(this.K)));else{var c;this.T==="OFFLINE"?c=new QO(this.player,this.videoData,this.getAudioTrack()):this.T==="SABR_LIVE"?c=new KXr(this.videoData.C,this.player):this.T==="LIVE"?c=new Er(this.videoData.C,this.player):this.T==="INNERTUBE"?
c=new g.kt(this.player,this.videoData,this.getAudioTrack()):c=new g.ol(this.player,this.videoData.IZ,this.videoData.videoId,g.ZR$(this.videoData),this.videoData.Yo,this.videoData.eventId);this.C=c;g.U(this,this.C);this.C.yT(this.F1)}};
g.D.unload=function(){this.U&&this.K?N7M(this,!1):(this.eg&&g.A2(this.eg),this.player.hm("captions"),this.dF=[],this.C&&this.C.Ry(),this.Xl.clear(),this.CJ&&this.player.Lo(this.CJ),this.rB());g.V5.prototype.unload.call(this);this.player.FH();this.player.LA("captionschanged",{})};
g.D.create=function(){this.JC()&&this.load();var c;a:{var A,J,q;if(this.o8.W("web_player_nitrate_promo_tooltip")&&((A=this.videoData.getPlayerResponse())==null?0:(J=A.captions)==null?0:(q=J.playerCaptionsTracklistRenderer)==null?0:q.enableTouchCaptionsNitrate)){var Y,p;if(A=(c=this.videoData.getPlayerResponse())==null?void 0:(Y=c.captions)==null?void 0:(p=Y.playerCaptionsTracklistRenderer)==null?void 0:p.captionTracks)for(c=g.u(A),Y=c.next();!Y.done;Y=c.next())if(Y=Y.value,Y.kind==="asr"&&Y.languageCode===
"en"){c=!0;break a}}c=!1}c&&this.J.publish("showpromotooltip",this.D.element)};
g.D.lY=function(){var c=fYR(this.player.getAudioTrack(),g.c1(this.o8));var A=c==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?aX(this,this.X):c==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&fC(this)?lz(this):rIx(this)||this.X||HaC(this)?aX(this,this.X):fC(this)?lz(this):null;if(this.U||this.Oq){var J=g.JB(this.C.K,!0);c=[];for(var q=0;q<J.length;q++){var Y=J[q],p=g.AH("TRACK");p.setAttribute("kind","subtitles");p.setAttribute("label",g.kp(Y));p.setAttribute("srclang",g.oj(Y));p.setAttribute("id",Y.toString());
this.Oq||p.setAttribute("src",this.C.AO(Y,"vtt"));Y===A&&p.setAttribute("default","1");c.push(p)}A=this.J.ri();A.N7(c);c=g.x(A.nY());this.oJ&&this.Fl.Z(c.textTracks,"change",this.aa$)}else!this.K&&A&&yO(this,A),this.player.LA("onCaptionsTrackListChanged"),this.player.hT("onApiChange")};
g.D.aa$=function(){for(var c=g.x(this.J.ri().nY()).textTracks,A=null,J=0;J<c.length;J++)if(c[J].mode==="showing")a:{A=g.JB(this.C.K,!0);for(var q=0;q<A.length;q++)if(A[q].toString()===c[J].id){A=A[q];break a}A=null}(this.loaded?this.K:null)!==A&&yO(this,A,!0)};
g.D.o6q=function(){!this.K&&this.U||this.unload()};
g.D.oS=function(c,A,J,q){if(c){var Y;kjV(this,(Y=this.K)!=null?Y:void 0);this.C.h4()&&(this.dF=[],this.J.hm("captions"),ji(this.wF),this.Xl.reset());if(this.videoData.FX){var p;J=((p=J)!=null?p:0)+this.videoData.FX}c=this.Xl.WP(c,A,J,q);if(this.pJ)for(A=g.u(c),J=A.next();!J.done;J=A.next())J=J.value,J.j=this.videoData.clientPlaybackNonce,J.Pr=this.videoData.FX;A=!this.o8.W("html5_keep_caption_data_after_seek")&&(this.T==="LIVE"||this.T==="SABR_LIVE");this.player.Lo(c,void 0,A);!this.X||this.Oq||bz(this)||
g.FP(this.o8)||g.P6(this.o8)||g.fk(this.o8)||this.o8.Oq==="shortspage"||this.player.isInline()||(g.A2(this.eg),c=ST9({yH:0,us:5,gs:5,uu:2,textAlign:0,bY:0,lang:"en"}),this.xT=[c],A=["Click "," for settings"],this.My||(J=new g.H4(g.Xr()),g.U(this,J),this.My=J.element),J=c.end-c.start,(q=g.kp(this.K))&&this.xT.push(new gH(c.start,J,0,c.id,q)),this.xT.push(new gH(c.start,J,0,c.id,A[0]),new gH(c.start,J,0,c.id,this.My,!0),new gH(c.start,J,0,c.id,A[1],!0)),this.player.Lo(this.xT),g.Ba(this.eg));!this.X||
this.Oq||bz(this)||(g.c1(this.o8)?tQ(this,!0):iz(this,!0),this.L&&(this.L.T=this.K),this.player.FH());this.X=!1}};
g.D.onCueRangeEnter=function(c){this.dF.push(c);ji(this.wF)};
g.D.onCueRangeExit=function(c){g.oi(this.dF,c);this.C instanceof Er&&this.C.D&&this.player.Eb([c]);ji(this.wF)};
g.D.getCaptionWindowContainerId=function(){return this.D.element.id};
g.D.f00=function(){wvR(this,this.xT);this.xT=null};
g.D.l6=function(){var c=this;if(!this.CY||!this.U){this.wF.stop();g.x83(this.Ba);this.dF.sort(g.mo);var A=this.dF;if(this.CJ){var J=g.IR(A,function(p){return this.CJ.indexOf(p)===-1},this);
J.length&&(A=J)}A=g.u(A);for(J=A.next();!J.done;J=A.next())oLi(this,J.value);A=g.u(Object.entries(this.nJ));var q=A.next();for(J={};!q.done;J={Ty:void 0,K2:void 0},q=A.next()){var Y=g.u(q.value);q=Y.next().value;Y=Y.next().value;J.Ty=q;J.K2=Y;this.Ba[J.Ty]?(J.K2.element.parentNode||(J.K2 instanceof xW||J.K2 instanceof Xw||g.te(this.nJ,function(p){return function(m,E){E!==p.Ty&&m.K.params.yH===p.K2.K.params.yH&&m.K.params.us===p.K2.K.params.us&&m.K.params.gs===p.K2.K.params.gs&&(m.dispose(),delete c.nJ[E]);
return E===p.Ty}}(J),this),this.D.element.appendChild(J.K2.element)),J.K2.Mb(this.Ba[J.Ty])):(J.K2.dispose(),delete this.nJ[J.Ty])}}};
g.D.yTT=function(){T7w(this,{},!0);this.player.LA("captionssettingschanged")};
g.D.h3=function(){var c=ei.le;c={background:c.background,backgroundOpacity:c.backgroundOpacity,charEdgeStyle:c.charEdgeStyle,color:c.color,fontFamily:c.fontFamily,fontSizeIncrement:c.fontSizeIncrement,fontStyle:c.bold&&c.italic?3:c.bold?1:c.italic?2:0,textOpacity:c.textOpacity,windowColor:ei.windowColor,windowOpacity:ei.windowOpacity};var A=KCx()||{};A.background!=null&&(c.background=A.background);A.backgroundOverride!=null&&(c.backgroundOverride=A.backgroundOverride);A.backgroundOpacity!=null&&(c.backgroundOpacity=
A.backgroundOpacity);A.backgroundOpacityOverride!=null&&(c.backgroundOpacityOverride=A.backgroundOpacityOverride);A.charEdgeStyle!=null&&(c.charEdgeStyle=A.charEdgeStyle);A.charEdgeStyleOverride!=null&&(c.charEdgeStyleOverride=A.charEdgeStyleOverride);A.color!=null&&(c.color=A.color);A.colorOverride!=null&&(c.colorOverride=A.colorOverride);A.fontFamily!=null&&(c.fontFamily=A.fontFamily);A.fontFamilyOverride!=null&&(c.fontFamilyOverride=A.fontFamilyOverride);A.fontSizeIncrement!=null&&(c.fontSizeIncrement=
A.fontSizeIncrement);A.fontSizeIncrementOverride!=null&&(c.fontSizeIncrementOverride=A.fontSizeIncrementOverride);A.fontStyle!=null&&(c.fontStyle=A.fontStyle);A.fontStyleOverride!=null&&(c.fontStyleOverride=A.fontStyleOverride);A.textOpacity!=null&&(c.textOpacity=A.textOpacity);A.textOpacityOverride!=null&&(c.textOpacityOverride=A.textOpacityOverride);A.windowColor!=null&&(c.windowColor=A.windowColor);A.windowColorOverride!=null&&(c.windowColorOverride=A.windowColorOverride);A.windowOpacity!=null&&
(c.windowOpacity=A.windowOpacity);A.windowOpacityOverride!=null&&(c.windowOpacityOverride=A.windowOpacityOverride);return c};
g.D.jI=function(c,A){var J={};Object.assign(J,KCx());Object.assign(J,c);T7w(this,J,A);this.player.LA("captionssettingschanged")};
g.D.rB=function(){!this.U&&this.loaded&&(g.lC(this.nJ,function(c,A){c.dispose();delete this.nJ[A]},this),this.l6())};
g.D.Jo=function(c,A){switch(c){case "fontSize":if(isNaN(A))break;c=g.Fa(A,-2,4);this.jI({fontSizeIncrement:c});return c;case "reload":A&&!this.U&&yO(this,this.K,!0);break;case "stickyLoading":A!==void 0&&this.o8.X&&(g.c1(this.o8)?tQ(this,!!A):iz(this,!!A));break;case "track":return $Gx(this,A);case "tracklist":return this.C?g.il(g.JB(this.C.K,!(!A||!A.includeAsr)),function(J){return g.gC(J)}):[];
case "translationLanguages":return this.C?this.C.U.map(function(J){return Object.assign({},J)}):[];
case "sampleSubtitles":this.U||A===void 0||Wzw(this,!!A);break;case "sampleSubtitlesCustomized":this.U||Wzw(this,!!A,A);break;case "recommendedTranslationLanguages":return g.hs();case "defaultTranslationSourceTrackIndices":return this.C?this.C.X:[]}};
g.D.getOptions=function(){var c="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.o8.X&&c.push("stickyLoading");return c};
g.D.rK=function(){var c=this.K;if(this.J.f2("captions")){if(this.o8.W("html5_modify_caption_vss_logging")){var A;return(c=(A=this.videoData.Rt)!=null?A:null)?{cc:g.noa(c)}:{}}if(c)return A=c.vssId,c.translationLanguage&&A&&(A="t"+A+"."+g.oj(c)),{cc:A}}return{}};
g.D.zgT=function(){this.isSubtitlesOn()?(g.c1(this.o8)?tQ(this,!1):iz(this,!1),kjV(this),yO(this,null,!0)):this.ZY()};
g.D.ZY=function(){var c=bz(this)||!this.K?aX(this,!0):this.K;c&&this.Ao(c.vssId,"m");this.isSubtitlesOn()||yO(this,bz(this)||!this.K?aX(this,!0):this.K,!0)};
g.D.isSubtitlesOn=function(){return!!this.loaded&&!!this.K&&!bz(this)};
g.D.LTx=function(){var c=bz(this);fC(this,c)?yO(this,this.getAudioTrack().C,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.aV()&&(this.X=!1,this.K=null,this.C&&(this.C.dispose(),this.C=null)),this.JC()&&(c?yO(this,aX(this,!1),!1):this.load()))};
g.D.Ay=function(c){c&&(this.l$={top:c.top,right:c.right,bottom:c.bottom,left:c.left,width:1-c.left-c.right,height:1-c.top-c.bottom},this.D.element.style.top=this.l$.top*100+"%",this.D.element.style.left=this.l$.left*100+"%",this.D.element.style.width=this.l$.width*100+"%",this.D.element.style.height=this.l$.height*100+"%",this.D.element.style.position="absolute",c=umH(this))&&(this.D.element.style.width=c.width+"px",this.D.element.style.height=c.height+"px")};
g.D.onVideoDataChange=function(c,A){c==="newdata"&&(this.videoData=A,this.loaded&&this.unload(),this.X=!1,this.K=null,this.C&&(this.C.dispose(),this.C=null,this.player.LA("captionschanged",{})),this.JC()&&this.load())};
g.D.getAudioTrack=function(){return this.pJ&&this.player.getPresentingPlayerType()===2?this.videoData.gO:this.player.getAudioTrack()};
g.D.Dn0=function(){var c=this.J.ri();c&&!c.Uq()&&c.Qb();this.J.isFullscreen()?(this.U=this.I8=!0,this.loaded&&this.lY()):(this.I8=this.o8.controlsType==="3",this.U=OaH(this));yO(this,this.K)};
g.D.We=function(){var c,A,J,q=(c=this.videoData.getPlayerResponse())==null?void 0:(A=c.captions)==null?void 0:(J=A.playerCaptionsTracklistRenderer)==null?void 0:J.openTranscriptCommand;q&&this.player.gF("innertubeCommand",q)};
g.D.F9=function(c,A,J){var q=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,Y="";c&&(Y=c.vssId,Y=Y.replace(q,""));var p="";c&&c.getId()&&(p=c.getId()||"");c&&c.getXtags()&&(c=c.getXtags(),c=c.replace(q,""),p=p.concat(";"+c));this.J.F9(A?Y:"",A?p:"",J)};
g.D.Ao=function(c,A){c=(c||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");c.length>0&&this.J.Ao(c,A)};
g.D.JR=function(){this.C&&this.C.JR()};
g.Z7.bW(Ur,{l6:"smucd"});g.HO("captions",Ur);})(_yt_player);
