(function(g){var window=this;'use strict';var qNr=function(c){c.publish("autonavvisibility")},YNr=function(c,A){c.gF("onAutonavCoundownStarted",A)},pSM=function(c){var A,J,q;
return c==null?void 0:(A=c.playerOverlays)==null?void 0:(J=A.playerOverlayRenderer)==null?void 0:(q=J.autoplay)==null?void 0:q.playerOverlayAutoplayRenderer},qS=function(c,A,J){g.Rf(c.element,"ytp-suggestion-set",!!A.videoId);
var q=A.playlistId;J=A.tX(J?J:"mqdefault.jpg");var Y=null,p=null;A instanceof g.M9&&(A.lengthText?(Y=A.lengthText||null,p=A.U6||null):A.lengthSeconds&&(Y=g.M3(A.lengthSeconds),p=g.M3(A.lengthSeconds,!0)));var m=!!q;q=m&&g.GN(q).type==="RD";var E=A instanceof g.M9?A.isLivePlayback:null,O=A instanceof g.M9?A.isUpcoming:null,T=A.author,R=A.shortViewCount,r=A.publishedTimeText,H=[],V=[];T&&H.push(T);R&&(H.push(R),V.push(R));r&&V.push(r);J={title:A.title,author:T,author_and_views:H.join(" \u2022 "),aria_label:A.ariaLabel||
g.k7("Watch $TITLE",{TITLE:A.title}),duration:Y,timestamp:p,url:A.uY(),is_live:E,is_upcoming:O,is_list:m,is_mix:q,background:J?"background-image: url("+J+")":"",views_and_publish_time:V.join(" \u2022 "),autoplayAlternativeHeader:A.xS};A instanceof g.CJ&&(J.playlist_length=A.playlistLength);c.update(J)},Ya=function(c){var A=c.B(),J=A.T;
g.t.call(this,{S:"a",V:"ytp-autonav-suggestion-card",G:{href:"{{url}}",target:J?A.L:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},N:[{S:"div",QP:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],G:{style:"{{background}}"},N:[{S:"div",G:{"aria-label":"{{timestamp}}"},QP:["ytp-autonav-timestamp"],KJ:"{{duration}}"},{S:"div",QP:["ytp-autonav-live-stamp"],KJ:"Live"},{S:"div",
QP:["ytp-autonav-upcoming-stamp"],KJ:"Upcoming"},{S:"div",V:"ytp-autonav-list-overlay",N:[{S:"div",V:"ytp-autonav-mix-text",KJ:"Mix"},{S:"div",V:"ytp-autonav-mix-icon"}]}]},{S:"div",QP:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],KJ:"{{title}}"},{S:"div",QP:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],KJ:"{{author}}"},{S:"div",QP:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],KJ:"{{views_and_publish_time}}"}]});this.J=c;this.suggestion=
null;this.C=J;this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress)},p8=function(c,A){A=A===void 0?!1:A;
g.t.call(this,{S:"div",V:"ytp-autonav-endscreen-countdown-overlay"});var J=this;this.D=A;this.cancelCommand=this.Y=void 0;this.j=0;this.container=new g.t({S:"div",V:"ytp-autonav-endscreen-countdown-container"});g.U(this,this.container);this.container.Sg(this.element);A=c.B();var q=A.T;this.J=c;this.suggestion=null;this.onVideoDataChange("newdata",g.x(this.J.getVideoData()));this.Z(c,"videodatachange",this.onVideoDataChange);this.C=new g.t({S:"div",V:"ytp-autonav-endscreen-upnext-container",G:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},N:[{S:"div",V:"ytp-autonav-endscreen-upnext-header"},{S:"div",V:"ytp-autonav-endscreen-upnext-alternative-header",KJ:"{{autoplayAlternativeHeader}}"},{S:"a",V:"ytp-autonav-endscreen-link-container",G:{href:"{{url}}",target:q?A.L:""},N:[{S:"div",V:"ytp-autonav-endscreen-upnext-thumbnail",G:{style:"{{background}}"},N:[{S:"div",G:{"aria-label":"{{timestamp}}"},QP:["ytp-autonav-timestamp"],
KJ:"{{duration}}"},{S:"div",QP:["ytp-autonav-live-stamp"],KJ:"Live"},{S:"div",QP:["ytp-autonav-upcoming-stamp"],KJ:"Upcoming"}]},{S:"div",V:"ytp-autonav-endscreen-video-info",N:[{S:"div",V:"ytp-autonav-endscreen-premium-badge"},{S:"div",V:"ytp-autonav-endscreen-upnext-title",KJ:"{{title}}"},{S:"div",V:"ytp-autonav-endscreen-upnext-author",KJ:"{{author}}"},{S:"div",V:"ytp-autonav-view-and-date",KJ:"{{views_and_publish_time}}"},{S:"div",V:"ytp-autonav-author-and-view",KJ:"{{author_and_views}}"}]}]}]});
g.U(this,this.C);this.C.Sg(this.container.element);q||this.Z(this.C.Eq("ytp-autonav-endscreen-link-container"),"click",this.pn);this.J.createClientVe(this.container.element,this,115127);this.J.createClientVe(this.C.Eq("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.t({S:"div",V:"ytp-autonav-overlay"});g.U(this,this.overlay);this.overlay.Sg(this.container.element);this.K=new g.t({S:"div",V:"ytp-autonav-endscreen-button-container"});g.U(this,this.K);this.K.Sg(this.container.element);
this.cancelButton=new g.t({S:"button",QP:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",A.W("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],G:{"aria-label":"Cancel autoplay"},KJ:"Cancel"});g.U(this,this.cancelButton);this.cancelButton.Sg(this.K.element);this.cancelButton.listen("click",this.YJ,this);this.J.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.t({S:"a",QP:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
A.W("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],G:{href:"{{url}}",role:"button","aria-label":"Play next video"},KJ:"Play Now"});g.U(this,this.playButton);this.playButton.Sg(this.K.element);this.playButton.listen("click",this.pn,this);this.J.createServerVe(this.playButton.element,this.playButton,!0);(A=this.J.getVideoData())&&mAM(this,A);this.T=new g.hN(function(){jRr(J)},500);
g.U(this,this.T);this.R0();this.Z(c,"autonavvisibility",this.R0);this.J.W("web_autonav_color_transition")&&(this.Z(c,"autonavchange",this.Q3),this.Z(c,"onAutonavCoundownStarted",this.Mg0))},mi=function(c){var A=c.J.LX(!0,c.J.isFullscreen());
g.Rf(c.container.element,"ytp-autonav-endscreen-small-mode",c.E_(A));g.Rf(c.container.element,"ytp-autonav-endscreen-is-premium",!!c.suggestion&&!!c.suggestion.jGa);g.Rf(c.J.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!c.J.UD());g.Rf(c.J.getRootNode(),"countdown-running",c.Gt());g.Rf(c.container.element,"ytp-player-content",c.J.UD());g.SL(c.overlay.element,{width:A.width+"px"});if(!c.Gt()){c.J.UD()?dAR(c,Math.round(EFw(c)/1E3)):dAR(c);A=!!c.suggestion&&!!c.suggestion.xS;var J=c.J.UD()||
!A;g.Rf(c.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!J&&A);g.Rf(c.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",J&&!A);c.K.LY(c.J.UD());g.Rf(c.element,"ytp-enable-w2w-color-transitions",OpR(c))}},jRr=function(c){var A=EFw(c),J=Math,q=J.min;
var Y=c.j?Date.now()-c.j:0;J=q.call(J,Y,A);dAR(c,Math.ceil((A-J)/1E3));A-J<=500&&c.Gt()?c.select(!0):c.Gt()&&c.T.start()},EFw=function(c){if(c.J.isFullscreen()){var A;
c=(A=c.J.getVideoData())==null?void 0:A.xV;return c===-1||c===void 0?8E3:c}return c.J.MZ()>=0?c.J.MZ():g.V8(c.J.B().experiments,"autoplay_time")||1E4},mAM=function(c,A){A=A.getWatchNextResponse();
var J,q;A=(J=pSM(A))==null?void 0:(q=J.nextButton)==null?void 0:q.buttonRenderer;c.Y=A==null?void 0:A.navigationEndpoint;J=A==null?void 0:A.trackingParams;c.playButton&&J&&c.J.setTrackingParams(c.playButton.element,J)},OpR=function(c){var A;
return!((A=c.J.getVideoData())==null||!A.watchToWatchTransitionRenderer)},dAR=function(c,A){A=A===void 0?-1:A;
c=c.C.Eq("ytp-autonav-endscreen-upnext-header");g.Yk(c);if(A>=0){A=String(A);var J="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],q="Up next in $SECONDS".indexOf(J);if(q>=0){c.appendChild(g.JH("Up next in $SECONDS".slice(0,q)));var Y=g.AH("span");g.mW(Y,"ytp-autonav-endscreen-upnext-header-countdown-number");g.d5(Y,A);c.appendChild(Y);c.appendChild(g.JH("Up next in $SECONDS".slice(q+J.length)));return}}g.d5(c,"Up next")},jm=function(c,A){g.t.call(this,{S:"div",
QP:["html5-endscreen","ytp-player-content",A||"base-endscreen"]});this.created=!1;this.player=c},dk=function(c){g.t.call(this,{S:"div",
QP:["ytp-upnext","ytp-player-content"],G:{"aria-label":"{{aria_label}}"},N:[{S:"div",V:"ytp-cued-thumbnail-overlay-image",G:{style:"{{background}}"}},{S:"span",V:"ytp-upnext-top",N:[{S:"span",V:"ytp-upnext-header",KJ:"Up Next"},{S:"span",V:"ytp-upnext-title",KJ:"{{title}}"},{S:"span",V:"ytp-upnext-author",KJ:"{{author}}"}]},{S:"a",V:"ytp-upnext-autoplay-icon",G:{role:"button",href:"{{url}}","aria-label":"Play next video"},N:[{S:"svg",G:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
N:[{S:"circle",V:"ytp-svg-autoplay-circle",G:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{S:"circle",V:"ytp-svg-autoplay-ring",G:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{S:"path",V:"ytp-svg-fill",G:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{S:"span",V:"ytp-upnext-bottom",N:[{S:"span",V:"ytp-upnext-cancel"},{S:"span",V:"ytp-upnext-paused",
KJ:"Autoplay is paused"}]}]});this.api=c;this.cancelButton=null;this.Y=this.Eq("ytp-svg-autoplay-ring");this.j=this.notification=this.C=this.suggestion=null;this.T=new g.hN(this.VG,5E3,this);this.K=0;var A=this.Eq("ytp-upnext-cancel");this.cancelButton=new g.t({S:"button",QP:["ytp-upnext-cancel-button","ytp-button"],G:{tabindex:"0","aria-label":"Cancel autoplay"},KJ:"Cancel"});g.U(this,this.cancelButton);this.cancelButton.listen("click",this.w0,this);this.cancelButton.Sg(A);this.cancelButton&&this.api.createClientVe(this.cancelButton.element,
this,115129);g.U(this,this.T);this.api.createClientVe(this.element,this,18788);A=this.Eq("ytp-upnext-autoplay-icon");this.Z(A,"click",this.HV);this.api.createClientVe(A,this,115130);this.Gz();this.Z(c,"autonavvisibility",this.Gz);this.Z(c,"mdxnowautoplaying",this.ZY8);this.Z(c,"mdxautoplaycanceled",this.mnl);g.Rf(this.element,"ytp-upnext-mobile",this.api.B().K)},TwR=function(c,A){if(A)return A;
if(c.api.isFullscreen()){var J;c=(J=c.api.getVideoData())==null?void 0:J.xV;return c===-1||c===void 0?8E3:c}return c.api.MZ()>=0?c.api.MZ():g.V8(c.api.B().experiments,"autoplay_time")||1E4},Rkr=function(c,A){A=TwR(c,A);
var J=Math,q=J.min;var Y=(0,g.b)()-c.K;J=q.call(J,Y,A);A=A===0?1:Math.min(J/A,1);c.Y.setAttribute("stroke-dashoffset",""+-211*(A+1));A>=1&&c.Gt()&&c.api.getPresentingPlayerType()!==3?c.select(!0):c.Gt()&&c.C.start()},Ei=function(c){jm.call(this,c,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.t({S:"div",V:"ytp-suggestion-panel",N:[{S:"div",QP:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],KJ:"More videos"}]});this.X=new g.t({S:"div",V:"ytp-suggestions-container"});this.videos=[];this.j=null;this.Y=this.D=!1;this.K=new p8(this.player);g.U(this,this.K);this.K.Sg(this.element);c.getVideoData().Zy?this.C=this.K:(this.C=new dk(c),g.Sx(this.player,this.C.element,4),g.U(this,this.C));this.overlay=new g.t({S:"div",
V:"ytp-autonav-overlay-cancelled-state"});g.U(this,this.overlay);this.overlay.Sg(this.element);this.T=new g.sM(this);g.U(this,this.T);g.U(this,this.table);this.table.Sg(this.element);this.table.show();g.U(this,this.X);this.X.Sg(this.table.element);this.hide()},Oi=function(c){var A=c.UD();
A!==c.Y&&(c.Y=A,qNr(c.player),c.Y?(c.K!==c.C&&c.K.hide(),c.table.hide()):(c.K!==c.C&&c.K.show(),c.table.show()))},TT=function(c,A){g.t.call(this,{S:"button",
QP:["ytp-watch-on-youtube-button","ytp-button"],KJ:"{{content}}"});this.J=c;this.buttonType=this.buttonType=A;this.uN();this.buttonType===2&&g.dc(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.uN);this.LY(!0)},R_=function(c,A){jm.call(this,c,"embeds-lite-endscreen");
this.J=c;this.C=A;this.J.createClientVe(this.element,this,156943);this.watchButton=new TT(c,2);g.U(this,this.watchButton);this.watchButton.Sg(this.element);this.hide()},rk=function(c){var A=c.B(),J=g.zh||g.F0?{style:"will-change: opacity"}:void 0,q=A.T,Y=["ytp-modern-videowall-still"];
A.K&&Y.push("ytp-videowall-show-text");g.t.call(this,{S:"a",QP:Y,G:{href:"{{url}}",target:q?A.L:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},N:[{S:"div",V:"ytp-modern-videowall-still-image",G:{style:"{{background}}"},N:[{S:"span",V:"ytp-modern-videowall-still-info-duration",KJ:"{{duration}}"}]},{S:"span",V:"ytp-modern-videowall-still-info",G:{"aria-hidden":"true"},N:[{S:"span",V:"ytp-modern-videowall-still-info-bg",N:[{S:"span",
V:"ytp-modern-videowall-still-info-content",G:J,N:[{S:"span",V:"ytp-modern-videowall-still-info-title",KJ:"{{title}}"},{S:"span",V:"ytp-modern-videowall-still-info-author",KJ:"{{author_and_views}}"},{S:"span",V:"ytp-modern-videowall-still-info-live",KJ:"Live"}]}]}]},{S:"span",QP:["ytp-modern-videowall-still-listlabel-regular","ytp-modern-videowall-still-listlabel"],G:{"aria-hidden":"true"},N:[{S:"span",V:"ytp-modern-videowall-still-listlabel-icon"},"Playlist",{S:"span",V:"ytp-modern-videowall-still-listlabel-length",
N:[" (",{S:"span",KJ:"{{playlist_length}}"},")"]}]},{S:"span",QP:["ytp-modern-videowall-still-listlabel-mix","ytp-modern-videowall-still-listlabel"],G:{"aria-hidden":"true"},N:[{S:"span",V:"ytp-modern-videowall-still-listlabel-mix-icon"},"Mix",{S:"span",V:"ytp-modern-videowall-still-listlabel-length",KJ:" (50+)"}]}]});this.suggestion=null;this.K=q;this.api=c;this.C=new g.sM(this);g.U(this,this.C);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.C.Z(c,"videodatachange",
this.onVideoDataChange);c.createServerVe(this.element,this);this.onVideoDataChange()},rPR=function(c){jm.call(this,c,"videowall-endscreen");
var A=this;this.J=c;this.stills=[];this.j=this.videoData=null;this.T=this.D=!1;this.X=null;g.dc(this.element,"modern-videowall-endscreen");this.K=new g.sM(this);g.U(this,this.K);this.Y=new g.hN(function(){g.dc(A.element,"ytp-show-tiles")},0);
g.U(this,this.Y);this.table=new g.H4({S:"div",V:"ytp-modern-endscreen-content"});g.U(this,this.table);this.table.Sg(this.element);c.getVideoData().Zy?this.C=new p8(c,!0):this.C=new dk(c);g.U(this,this.C);g.Sx(this.player,this.C.element,4);c.createClientVe(this.element,this,158789);this.hide()},HU=function(c){return g.xm(c.player)&&c.Y9()&&!c.j},Vh=function(c){var A=c.UD();
A!==c.D&&(c.D=A,qNr(c.player))},Hpe=function(c){jm.call(this,c,"subscribecard-endscreen");
this.C=new g.t({S:"div",V:"ytp-subscribe-card",N:[{S:"img",V:"ytp-author-image",G:{src:"{{profilePicture}}"}},{S:"div",V:"ytp-subscribe-card-right",N:[{S:"div",V:"ytp-author-name",KJ:"{{author}}"},{S:"div",V:"html5-subscribe-button-container"}]}]});g.U(this,this.C);this.C.Sg(this.element);var A=c.getVideoData();this.subscribeButton=new g.nZ("Subscribe",null,"Unsubscribe",null,!0,!1,A.QH,A.subscribed,"trailer-endscreen",null,c,!1);g.U(this,this.subscribeButton);this.subscribeButton.Sg(this.C.Eq("html5-subscribe-button-container"));
this.Z(c,"videodatachange",this.Wa);this.Wa();this.hide()},NS=function(c){var A=c.B(),J=g.zh||g.F0?{style:"will-change: opacity"}:void 0,q=A.T,Y=["ytp-videowall-still"];
A.K&&Y.push("ytp-videowall-show-text");g.t.call(this,{S:"a",QP:Y,G:{href:"{{url}}",target:q?A.L:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},N:[{S:"div",V:"ytp-videowall-still-image",G:{style:"{{background}}"}},{S:"span",V:"ytp-videowall-still-info",G:{"aria-hidden":"true"},N:[{S:"span",V:"ytp-videowall-still-info-bg",N:[{S:"span",V:"ytp-videowall-still-info-content",G:J,N:[{S:"span",V:"ytp-videowall-still-info-title",KJ:"{{title}}"},
{S:"span",V:"ytp-videowall-still-info-author",KJ:"{{author_and_views}}"},{S:"span",V:"ytp-videowall-still-info-live",KJ:"Live"},{S:"span",V:"ytp-videowall-still-info-duration",KJ:"{{duration}}"}]}]}]},{S:"span",QP:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],G:{"aria-hidden":"true"},N:[{S:"span",V:"ytp-videowall-still-listlabel-icon"},"Playlist",{S:"span",V:"ytp-videowall-still-listlabel-length",N:[" (",{S:"span",KJ:"{{playlist_length}}"},")"]}]},{S:"span",QP:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],G:{"aria-hidden":"true"},N:[{S:"span",V:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{S:"span",V:"ytp-videowall-still-listlabel-length",KJ:" (50+)"}]}]});this.suggestion=null;this.K=q;this.api=c;this.C=new g.sM(this);g.U(this,this.C);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.C.Z(c,"videodatachange",this.onVideoDataChange);c.createServerVe(this.element,this);this.onVideoDataChange()},DU=function(c){jm.call(this,c,"videowall-endscreen");
var A=this;this.J=c;this.j=0;this.stills=[];this.T=this.videoData=null;this.Y=this.X=!1;this.L=null;this.K=new g.sM(this);g.U(this,this.K);this.D=new g.hN(function(){g.dc(A.element,"ytp-show-tiles")},0);
g.U(this,this.D);var J=new g.t({S:"button",QP:["ytp-button","ytp-endscreen-previous"],G:{"aria-label":"Previous"},N:[g.wZ()]});g.U(this,J);J.Sg(this.element);J.listen("click",this.h9,this);this.table=new g.H4({S:"div",V:"ytp-endscreen-content"});g.U(this,this.table);this.table.Sg(this.element);J=new g.t({S:"button",QP:["ytp-button","ytp-endscreen-next"],G:{"aria-label":"Next"},N:[g.W4()]});g.U(this,J);J.Sg(this.element);J.listen("click",this.f7,this);c.getVideoData().Zy?this.C=new p8(c,!0):this.C=
new dk(c);g.U(this,this.C);g.Sx(this.player,this.C.element,4);c.createClientVe(this.element,this,158789);this.hide()},ka=function(c){return g.xm(c.player)&&c.Y9()&&!c.T},gk=function(c){var A=c.UD();
A!==c.X&&(c.X=A,qNr(c.player))},o_=function(c){jm.call(this,c,"watch-again-on-youtube-endscreen");
this.watchButton=new TT(c,1);g.U(this,this.watchButton);this.watchButton.Sg(this.element);g.OIJ(c)&&(this.C=new g.K9(c),g.U(this,this.C),this.K=new g.t({S:"div",QP:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],G:{tabIndex:"-1"},N:[this.C]}),g.U(this,this.K),this.C.Sg(this.K.element),this.K.Sg(this.element));c.createClientVe(this.element,this,156914);this.hide()},kcR=function(c){g.V5.call(this,c);
var A=this;this.endScreen=null;this.K=this.C=this.j=this.T=!1;this.listeners=new g.sM(this);g.U(this,this.listeners);var J=c.B(),q=c.getVideoData();q=q&&q.limitedPlaybackDurationInSeconds!==0;g.RZ(g.UE(J))&&q&&!g.X3(c)?(this.K=!0,this.endScreen=new R_(c,g.km(c))):c.isEmbedsShortsMode()?this.endScreen=new o_(c):VQr(c)?(this.T=!0,NwJ(this),this.C?this.endScreen=new Ei(c):J.W("delhi_modern_endscreen")?this.endScreen=new rPR(c):this.endScreen=new DU(c)):J.c$?this.endScreen=new Hpe(c):this.endScreen=new jm(c);
g.U(this,this.endScreen);g.Sx(c,this.endScreen.element,4);DAx(this);this.listeners.Z(c,"videodatachange",this.onVideoDataChange,this);this.listeners.Z(c,g.jo("endscreen"),function(Y){A.onCueRangeEnter(Y)});
this.listeners.Z(c,g.dP("endscreen"),function(Y){A.onCueRangeExit(Y)})},NwJ=function(c){var A=c.player.getVideoData();
if(!A||c.C===A.tv&&c.j===A.Zy)return!1;c.C=A.tv;c.j=A.Zy;return!0},VQr=function(c){c=c.B();
return c.fA&&!c.c$&&!c.disableOrganicUi},DAx=function(c){c.player.hm("endscreen");
var A=c.player.getVideoData();A=new g.p$(Math.max((A.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var J=new g.p$(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});c.player.Lo([A,J])};
g.MY.prototype.MZ=g.mY(14,function(){return this.app.MZ()});
g.Vu.prototype.MZ=g.mY(13,function(){return this.getVideoData().Lp});
g.WH.prototype.oT=g.mY(12,function(c){this.vK().oT(c)});
g.Ou.prototype.oT=g.mY(11,function(c){this.C!==c&&(this.C=c,this.Wa())});
g.Ml.prototype.oT=g.mY(10,function(c){this.overflowButton&&this.overflowButton.oT(c)});
g.WH.prototype.kS=g.mY(9,function(c){this.vK().kS(c)});
g.Nk.prototype.kS=g.mY(8,function(c){this.K!==c&&(this.K=c,this.Wa())});
g.Ml.prototype.kS=g.mY(7,function(c){this.shareButton&&this.shareButton.kS(c)});
g.WH.prototype.pc=g.mY(6,function(c){this.vK().pc(c)});
g.lM.prototype.pc=g.mY(5,function(c){this.TV!==c&&(this.TV=c,this.WH())});
g.WH.prototype.RU=g.mY(4,function(c){this.vK().RU(c)});
g.Ml.prototype.RU=g.mY(3,function(c){this.Ew!==c&&(this.Ew=c,this.ew())});g.k(Ya,g.t);Ya.prototype.select=function(){this.J.J5(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.Vb||void 0)&&this.J.logClick(this.element)};
Ya.prototype.onClick=function(c){g.dg(c,this.J,this.C,this.suggestion.sessionData||void 0)&&this.select()};
Ya.prototype.onKeyPress=function(c){switch(c.keyCode){case 13:case 32:c.defaultPrevented||(this.select(),c.preventDefault())}};g.k(p8,g.t);g.D=p8.prototype;g.D.iZ=function(c){this.suggestion!==c&&(this.suggestion=c,qS(this.C,c),this.playButton.updateValue("url",this.suggestion.uY()),mi(this))};
g.D.Gt=function(){return this.j>0};
g.D.dR=function(){this.Gt()||(this.j=Date.now(),jRr(this),YNr(this.J,EFw(this)),g.Rf(this.J.getRootNode(),"countdown-running",this.Gt()))};
g.D.v5=function(){this.Nw();jRr(this);var c=this.C.Eq("ytp-autonav-endscreen-upnext-header");c&&g.d5(c,"Up next")};
g.D.Nw=function(){this.Gt()&&(this.T.stop(),this.j=0)};
g.D.select=function(c){this.J.nextVideo(!1,c===void 0?!1:c);this.Nw()};
g.D.pn=function(c){g.dg(c,this.J)&&(c.currentTarget===this.playButton.element?this.J.logClick(this.playButton.element):c.currentTarget===this.C.Eq("ytp-autonav-endscreen-link-container")&&(c=this.C.Eq("ytp-autonav-endscreen-link-container"),this.J.logVisibility(c,!0),this.J.logClick(c)),this.Y?(this.J.gF("innertubeCommand",this.Y),this.Nw()):this.select())};
g.D.YJ=function(){this.J.logClick(this.cancelButton.element);g.vH(this.J,!0);this.cancelCommand&&this.J.gF("innertubeCommand",this.cancelCommand)};
g.D.onVideoDataChange=function(c,A){mAM(this,A);c=A.getWatchNextResponse();var J,q;c=(J=pSM(c))==null?void 0:(q=J.cancelButton)==null?void 0:q.buttonRenderer;this.cancelCommand=c==null?void 0:c.command};
g.D.Mg0=function(c){if(OpR(this)){var A=this.J.getVideoData().watchToWatchTransitionRenderer,J=A==null?void 0:A.fromColorPaletteDark;A=A==null?void 0:A.toColorPaletteDark;if(J&&A){var q=this.element;q.style.setProperty("--w2w-start-background-color",g.lZ(J.surgeColor));q.style.setProperty("--w2w-start-primary-text-color",g.lZ(J.primaryTitleColor));q.style.setProperty("--w2w-start-secondary-text-color",g.lZ(J.secondaryTitleColor));q.style.setProperty("--w2w-end-background-color",g.lZ(A.surgeColor));
q.style.setProperty("--w2w-end-primary-text-color",g.lZ(A.primaryTitleColor));q.style.setProperty("--w2w-end-secondary-text-color",g.lZ(A.secondaryTitleColor));q.style.setProperty("--w2w-animation-duration",c+"ms")}g.Rf(this.element,"ytp-w2w-animate",!0)}};
g.D.Q3=function(c){this.J.W("web_autonav_color_transition")&&c!==2&&g.Rf(this.element,"ytp-w2w-animate",!1)};
g.D.R0=function(){var c=this.J.UD();this.D&&this.qy!==c&&this.LY(c);mi(this);this.J.logVisibility(this.container.element,c);this.J.logVisibility(this.cancelButton.element,c);this.J.logVisibility(this.C.Eq("ytp-autonav-endscreen-link-container"),c);this.J.logVisibility(this.playButton.element,c)};
g.D.E_=function(c){return c.width<400||c.height<459};g.k(jm,g.t);g.D=jm.prototype;g.D.create=function(){this.created=!0};
g.D.destroy=function(){this.created=!1};
g.D.Y9=function(){return!1};
g.D.UD=function(){return!1};
g.D.Wr=function(){return!1};g.k(dk,g.t);g.D=dk.prototype;g.D.VG=function(){this.notification&&(this.T.stop(),this.Jz(this.j),this.j=null,this.notification.close(),this.notification=null)};
g.D.iZ=function(c){this.suggestion=c;qS(this,c,"hqdefault.jpg")};
g.D.Gz=function(){this.LY(this.api.UD());this.api.logVisibility(this.element,this.api.UD());this.api.logVisibility(this.Eq("ytp-upnext-autoplay-icon"),this.api.UD());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.UD())};
g.D.gFD=function(){window.focus();this.VG()};
g.D.dR=function(c){var A=this;this.Gt()||(g.dF("a11y-announce","Up Next "+this.suggestion.title),this.K=(0,g.b)(),this.C=new g.hN(function(){Rkr(A,c)},25),Rkr(this,c),YNr(this.api,TwR(this,c)));
g.Ot(this.element,"ytp-upnext-autoplay-paused")};
g.D.hide=function(){g.t.prototype.hide.call(this)};
g.D.Gt=function(){return!!this.C};
g.D.v5=function(){this.Nw();this.K=(0,g.b)();Rkr(this);g.dc(this.element,"ytp-upnext-autoplay-paused")};
g.D.Nw=function(){this.Gt()&&(this.C.dispose(),this.C=null)};
g.D.select=function(c){c=c===void 0?!1:c;if(this.api.B().W("autonav_notifications")&&c&&window.Notification&&typeof document.hasFocus==="function"){var A=Notification.permission;A==="default"?Notification.requestPermission():A!=="granted"||document.hasFocus()||(this.VG(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.tX()}),this.j=this.Z(this.notification,"click",this.gFD),this.T.start())}this.Nw();this.api.nextVideo(!1,c)};
g.D.HV=function(c){!g.jG(this.cancelButton.element,c.target)&&g.dg(c,this.api)&&(this.api.UD()&&this.api.logClick(this.Eq("ytp-upnext-autoplay-icon")),this.select())};
g.D.w0=function(){this.api.UD()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.vH(this.api,!0)};
g.D.ZY8=function(c){this.api.getPresentingPlayerType();this.show();this.dR(c)};
g.D.mnl=function(){this.api.getPresentingPlayerType();this.Nw();this.hide()};
g.D.rF=function(){this.Nw();this.VG();g.t.prototype.rF.call(this)};g.k(Ei,jm);g.D=Ei.prototype;g.D.create=function(){jm.prototype.create.call(this);this.T.Z(this.player,"appresize",this.Gj);this.T.Z(this.player,"onVideoAreaChange",this.Gj);this.T.Z(this.player,"videodatachange",this.onVideoDataChange);this.T.Z(this.player,"autonavchange",this.i6);this.T.Z(this.player,"onAutonavCancelled",this.d0);this.onVideoDataChange()};
g.D.show=function(){jm.prototype.show.call(this);(this.D||this.j&&this.j!==this.videoData.clientPlaybackNonce)&&g.vH(this.player,!1);g.xm(this.player)&&this.Y9()&&!this.j?(Oi(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.C.select(!0):this.C.dR():this.videoData.autonavState===3&&this.C.v5()):(g.vH(this.player,!0),Oi(this));this.Gj()};
g.D.hide=function(){jm.prototype.hide.call(this);this.C.v5();Oi(this)};
g.D.Gj=function(){var c=this.player.LX(!0,this.player.isFullscreen());Oi(this);mi(this.K);g.Rf(this.element,"ytp-autonav-cancelled-small-mode",this.E_(c));g.Rf(this.element,"ytp-autonav-cancelled-tiny-mode",this.T2(c));g.Rf(this.element,"ytp-autonav-cancelled-mini-mode",c.width<=400||c.height<=360);this.overlay&&g.SL(this.overlay.element,{width:c.width+"px"});if(!this.Y)for(c=0;c<this.videos.length;c++)g.Rf(this.videos[c].element,"ytp-suggestion-card-with-margin",c%2===1)};
g.D.onVideoDataChange=function(){var c=this.player.getVideoData();if(this.videoData!==c&&c){this.videoData=c;if((c=this.videoData.suggestions)&&c.length||this.player.W("web_player_autonav_empty_suggestions_fix")){var A=g.qC(this.videoData);A&&(this.C.iZ(A),this.C!==this.K&&this.K.iZ(A))}if(c&&c.length)for(A=0;A<gFx.length;++A){var J=gFx[A];if(c&&c[J]){this.videos[A]=new Ya(this.player);var q=this.videos[A];J=c[J];q.suggestion!==J&&(q.suggestion=J,qS(q,J));g.U(this,this.videos[A]);this.videos[A].Sg(this.X.element)}}this.Gj()}};
g.D.i6=function(c){c===1?(this.D=!1,this.j=this.videoData.clientPlaybackNonce,this.C.Nw(),this.qy&&this.Gj()):(this.D=!0,this.UD()&&(c===2?this.C.dR():c===3&&this.C.v5()))};
g.D.d0=function(c){c?this.i6(1):(this.j=null,this.D=!1)};
g.D.Y9=function(){return this.videoData.autonavState!==1};
g.D.E_=function(c){return(c.width<910||c.height<459)&&!this.T2(c)&&!(c.width<=400||c.height<=360)};
g.D.T2=function(c){return c.width<800&&!(c.width<=400||c.height<=360)};
g.D.UD=function(){return this.qy&&g.xm(this.player)&&this.Y9()&&!this.j};
var gFx=[1,3,2,4];g.k(TT,g.t);g.D=TT.prototype;g.D.uN=function(){switch(this.buttonType){case 1:var c="Watch again on YouTube";var A=156915;break;case 2:c="Continue watching on YouTube";A=156942;break;default:c="Continue watching on YouTube",A=156942}this.update({content:c});this.J.hasVe(this.element)&&this.J.destroyVe(this.element);this.J.createClientVe(this.element,this,A)};
g.D.onClick=function(c){this.J.W("web_player_log_click_before_generating_ve_conversion_params")&&this.J.logClick(this.element);g.ES(this.getVideoUrl(),this.J,c);this.J.W("web_player_log_click_before_generating_ve_conversion_params")||this.J.logClick(this.element)};
g.D.getVideoUrl=function(){var c=!0;switch(this.buttonType){case 1:c=!0;break;case 2:c=!1}c=this.J.getVideoUrl(c,!1,!1,!0);var A=this.J.B();if(g.Qx(A)){var J={};g.Qx(A)&&g.rq(this.J,"addEmbedsConversionTrackingParams",[J]);c=g.zy(c,J)}return c};
g.D.logVisibility=function(){this.J.logVisibility(this.element,this.qy&&this.U)};
g.D.show=function(){g.t.prototype.show.call(this);this.logVisibility()};
g.D.hide=function(){g.t.prototype.hide.call(this);this.logVisibility()};
g.D.xF=function(c){g.t.prototype.xF.call(this,c);this.logVisibility()};g.k(R_,jm);R_.prototype.show=function(){this.player.getPlayerState()!==3&&(jm.prototype.show.call(this),this.C.RU(!0),this.C.kS(!0),this.J.B().Qp||this.C.oT(!0),this.J.logVisibility(this.element,!0),this.watchButton.xF(!0))};
R_.prototype.hide=function(){jm.prototype.hide.call(this);this.C.RU(!1);this.C.kS(!1);this.C.oT(!1);this.J.logVisibility(this.element,!1);this.watchButton.xF(!1)};g.k(rk,g.t);rk.prototype.select=function(){this.api.J5(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.Vb||void 0)&&this.api.logClick(this.element)};
rk.prototype.onClick=function(c){if(g.Qx(this.api.B())&&this.api.W("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var A=this.suggestion.uY(),J={};g.ZL(this.api,J);A=g.zy(A,J);g.ES(A,this.api,c)}else g.dg(c,this.api,this.K,this.suggestion.sessionData||void 0)&&this.select()};
rk.prototype.onKeyPress=function(c){switch(c.keyCode){case 13:case 32:c.defaultPrevented||(this.select(),c.preventDefault())}};
rk.prototype.onVideoDataChange=function(){var c=this.api.getVideoData(),A=this.api.B();this.K=c.Nq?!1:A.T};g.k(rPR,jm);g.D=rPR.prototype;g.D.create=function(){jm.prototype.create.call(this);var c=this.player.getVideoData();c&&(this.videoData=c);this.gR();this.K.Z(this.player,"appresize",this.gR);this.K.Z(this.player,"onVideoAreaChange",this.gR);this.K.Z(this.player,"videodatachange",this.onVideoDataChange);this.K.Z(this.player,"autonavchange",this.DK);this.K.Z(this.player,"onAutonavCancelled",this.Ug);c=this.videoData.autonavState;c!==this.X&&this.DK(c);this.K.Z(this.element,"transitionend",this.t9)};
g.D.destroy=function(){g.QD(this.K);g.rw(this.stills);this.stills=[];jm.prototype.destroy.call(this);g.Ot(this.element,"ytp-show-tiles");this.Y.stop();this.X=this.videoData.autonavState};
g.D.Y9=function(){return this.videoData.autonavState!==1};
g.D.show=function(){var c=this.qy;jm.prototype.show.call(this);g.Ot(this.element,"ytp-show-tiles");this.player.B().K?g.cd(this.Y):this.Y.start();(this.T||this.j&&this.j!==this.videoData.clientPlaybackNonce)&&g.vH(this.player,!1);HU(this)?(Vh(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.C.select(!0):this.C.dR():this.videoData.autonavState===3&&this.C.v5()):(g.vH(this.player,!0),Vh(this));c!==this.qy&&this.player.logVisibility(this.element,!0)};
g.D.hide=function(){var c=this.qy;jm.prototype.hide.call(this);this.C.v5();Vh(this);c!==this.qy&&this.player.logVisibility(this.element,!1)};
g.D.t9=function(c){c.target===this.element&&this.gR()};
g.D.gR=function(){var c,A,J,q;var Y=((c=this.videoData)==null?0:(A=c.suggestions)==null?0:A.length)?(J=this.videoData)==null?void 0:J.suggestions:[(q=this.videoData)==null?void 0:g.qC(q)];if(Y.length){A=this.J.LX(!0,this.J.isFullscreen());c=Math.floor((A.width-64+16)/(g.Fa(A.width*.27,250,450)+16));A=Math.min(3,Math.floor((A.height-64)/((A.width-64-(c-1)*16)/c*.5625+70)));g.Ts(this.element,["ytp-modern-endscreen-limit-rows-1","ytp-modern-endscreen-limit-rows-2","ytp-modern-endscreen-limit-rows-3"]);
g.dc(this.element,"ytp-modern-endscreen-limit-rows-"+A);g.Rf(this.element,"ytp-modern-endscreen-single-item",c===1);g.Rf(this.element,"ytp-modern-endscreen-row-0",A===0);c=this.table.element;c.ariaLive="polite";this.C.iZ(g.qC(this.videoData));this.C instanceof p8&&mi(this.C);g.Rf(this.element,"ytp-endscreen-takeover",HU(this));Vh(this);A=0;c.ariaBusy="true";J=Y.length;for(q=0;q<J;q++){var p=q%J,m=this.stills[q];m||(m=new rk(this.player),this.stills[q]=m,c.appendChild(m.element));p=Y[p];if(m.suggestion!==
p){m.suggestion=p;var E=m.api.B();qS(m,p,"hqdefault.jpg");if(g.Qx(E)&&!m.api.W("web_player_log_click_before_generating_ve_conversion_params")){E=p.uY();var O={};g.rq(m.api,"addEmbedsConversionTrackingParams",[O]);E=g.zy(E,O);m.updateValue("url",E)}(p=(p=p.sessionData)&&p.itct)&&m.api.setTrackingParams(m.element,p)}A++}this.stills.length=A}};
g.D.onVideoDataChange=function(){var c=this.player.getVideoData(1);this.videoData!==c&&(c!=null&&g.qC(c)?(this.videoData=c,this.gR()):this.player.b$("missg",{vid:(c==null?void 0:c.videoId)||"",cpn:(c==null?void 0:c.clientPlaybackNonce)||""}))};
g.D.Wr=function(){return this.C.Gt()};
g.D.DK=function(c){c===1?(this.T=!1,this.j=this.videoData.clientPlaybackNonce,this.C.Nw(),this.qy&&this.gR()):(this.T=!0,this.qy&&HU(this)&&(c===2?this.C.dR():c===3&&this.C.v5()))};
g.D.Ug=function(c){if(c){for(c=0;c<this.stills.length;c++)this.J.logVisibility(this.stills[c].element,!0);this.DK(1)}else this.j=null,this.T=!1;this.gR()};
g.D.UD=function(){return this.qy&&HU(this)};g.k(Hpe,jm);Hpe.prototype.Wa=function(){var c=this.player.getVideoData();this.C.update({profilePicture:c.profilePicture,author:c.author});this.subscribeButton.channelId=c.QH;var A=this.subscribeButton;c.subscribed?A.C():A.K()};g.k(NS,g.t);NS.prototype.select=function(){this.api.J5(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.Vb||void 0)&&this.api.logClick(this.element)};
NS.prototype.onClick=function(c){if(g.Qx(this.api.B())&&this.api.W("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var A=this.suggestion.uY(),J={};g.ZL(this.api,J);A=g.zy(A,J);g.ES(A,this.api,c)}else g.dg(c,this.api,this.K,this.suggestion.sessionData||void 0)&&this.select()};
NS.prototype.onKeyPress=function(c){switch(c.keyCode){case 13:case 32:c.defaultPrevented||(this.select(),c.preventDefault())}};
NS.prototype.onVideoDataChange=function(){var c=this.api.getVideoData(),A=this.api.B();this.K=c.Nq?!1:A.T};g.k(DU,jm);g.D=DU.prototype;g.D.create=function(){jm.prototype.create.call(this);var c=this.player.getVideoData();c&&(this.videoData=c);this.II();this.K.Z(this.player,"appresize",this.II);this.K.Z(this.player,"onVideoAreaChange",this.II);this.K.Z(this.player,"videodatachange",this.onVideoDataChange);this.K.Z(this.player,"autonavchange",this.VM);this.K.Z(this.player,"onAutonavCancelled",this.eK);c=this.videoData.autonavState;c!==this.L&&this.VM(c);this.K.Z(this.element,"transitionend",this.aq)};
g.D.destroy=function(){g.QD(this.K);g.rw(this.stills);this.stills=[];jm.prototype.destroy.call(this);g.Ot(this.element,"ytp-show-tiles");this.D.stop();this.L=this.videoData.autonavState};
g.D.Y9=function(){return this.videoData.autonavState!==1};
g.D.show=function(){var c=this.qy;jm.prototype.show.call(this);g.Ot(this.element,"ytp-show-tiles");this.player.B().K?g.cd(this.D):this.D.start();(this.Y||this.T&&this.T!==this.videoData.clientPlaybackNonce)&&g.vH(this.player,!1);ka(this)?(gk(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.C.select(!0):this.C.dR():this.videoData.autonavState===3&&this.C.v5()):(g.vH(this.player,!0),gk(this));c!==this.qy&&this.player.logVisibility(this.element,!0)};
g.D.hide=function(){var c=this.qy;jm.prototype.hide.call(this);this.C.v5();gk(this);c!==this.qy&&this.player.logVisibility(this.element,!1)};
g.D.aq=function(c){c.target===this.element&&this.II()};
g.D.II=function(){var c,A,J,q;var Y=((c=this.videoData)==null?0:(A=c.suggestions)==null?0:A.length)?(J=this.videoData)==null?void 0:J.suggestions:[(q=this.videoData)==null?void 0:g.qC(q)];if(Y.length){g.dc(this.element,"ytp-endscreen-paginate");var p=this.J.LX(!0,this.J.isFullscreen());if(c=g.km(this.J))c=c.hX()?48:32,p.width-=c*2;var m=p.width/p.height;q=96/54;A=c=2;var E=Math.max(p.width/96,2),O=Math.max(p.height/54,2);J=Y.length;var T=J*4;for(T-=4;T>0&&(c<E||A<O);){var R=c/2,r=A/2,H=c<=E-2&&T>=
r*4,V=A<=O-2&&T>=R*4;if((R+1)/r*q/m>m/(R/(r+1)*q)&&V)T-=R*4,A+=2;else if(H)T-=r*4,c+=2;else if(V)T-=R*4,A+=2;else break}q=!1;T>=12&&J*4-T<=6&&(A>=4||c>=4)&&(q=!0);T=c*96;E=A*54;m=T/E<m?p.height/E:p.width/T;m=Math.min(m,2);T=Math.floor(Math.min(p.width,T*m));E=Math.floor(Math.min(p.height,E*m));p=this.table.element;p.ariaLive="polite";g.yZ(p,T,E);g.SL(p,{marginLeft:T/-2+"px",marginTop:E/-2+"px"});this.C.iZ(g.qC(this.videoData));this.C instanceof p8&&mi(this.C);g.Rf(this.element,"ytp-endscreen-takeover",
ka(this));gk(this);T+=4;E+=4;m=0;p.ariaBusy="true";for(O=0;O<c;O++)for(R=0;R<A;R++)if(r=m,V=0,q&&O>=c-2&&R>=A-2?V=1:R%2===0&&O%2===0&&(R<2&&O<2?R===0&&O===0&&(V=2):V=2),r=g.vj(r+this.j,J),V!==0){H=this.stills[m];H||(H=new NS(this.player),this.stills[m]=H,p.appendChild(H.element));var N=Math.floor(E*R/A),w=Math.floor(T*O/c),W=Math.floor(E*(R+V)/A)-N-4,C=Math.floor(T*(O+V)/c)-w-4;g.aU(H.element,w,N);g.yZ(H.element,C,W);g.SL(H.element,"transitionDelay",(R+O)/20+"s");g.Rf(H.element,"ytp-videowall-still-mini",
V===1);g.Rf(H.element,"ytp-videowall-still-large",V>2);V=Math.max(C,W);g.Rf(H.element,"ytp-videowall-still-round-large",V>=256);g.Rf(H.element,"ytp-videowall-still-round-medium",V>96&&V<256);g.Rf(H.element,"ytp-videowall-still-round-small",V<=96);r=Y[r];H.suggestion!==r&&(H.suggestion=r,V=H.api.B(),N=g.jS(H.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",qS(H,r,N),g.Qx(V)&&!H.api.W("web_player_log_click_before_generating_ve_conversion_params")&&(V=r.uY(),N={},g.rq(H.api,"addEmbedsConversionTrackingParams",
[N]),V=g.zy(V,N),H.updateValue("url",V)),(r=(r=r.sessionData)&&r.itct)&&H.api.setTrackingParams(H.element,r));m++}p.ariaBusy="false";g.Rf(this.element,"ytp-endscreen-paginate",m<J);for(Y=this.stills.length-1;Y>=m;Y--)c=this.stills[Y],g.mf(c.element),g.RR(c);this.stills.length=m}};
g.D.onVideoDataChange=function(){var c=this.player.getVideoData(1);this.videoData!==c&&(c!=null&&g.qC(c)?(this.j=0,this.videoData=c,this.II()):this.player.b$("missg",{vid:(c==null?void 0:c.videoId)||"",cpn:(c==null?void 0:c.clientPlaybackNonce)||""}))};
g.D.f7=function(){this.j+=this.stills.length;this.II()};
g.D.h9=function(){this.j-=this.stills.length;this.II()};
g.D.Wr=function(){return this.C.Gt()};
g.D.VM=function(c){c===1?(this.Y=!1,this.T=this.videoData.clientPlaybackNonce,this.C.Nw(),this.qy&&this.II()):(this.Y=!0,this.qy&&ka(this)&&(c===2?this.C.dR():c===3&&this.C.v5()))};
g.D.eK=function(c){if(c){for(c=0;c<this.stills.length;c++)this.J.logVisibility(this.stills[c].element,!0);this.VM(1)}else this.T=null,this.Y=!1;this.II()};
g.D.UD=function(){return this.qy&&ka(this)};g.k(o_,jm);o_.prototype.hasSuggestions=function(){var c;return(c=this.C)==null?void 0:c.hasSuggestions()};
o_.prototype.show=function(){if(this.player.getPlayerState()!==3){jm.prototype.show.call(this);var c=this.K;if(c){var A=this.C.hasSuggestions();g.Rf(this.element,"ytp-shorts-branded-ui",A);A?c.show():c.hide()}var J;(J=g.km(this.player))==null||J.pc(!0);this.player.logVisibility(this.element,!0);this.watchButton.xF(!0)}};
o_.prototype.hide=function(){jm.prototype.hide.call(this);var c;(c=g.km(this.player))==null||c.pc(!1);this.player.logVisibility(this.element,!1);this.watchButton.xF(!1)};g.k(kcR,g.V5);g.D=kcR.prototype;g.D.JC=function(){var c=this.player.getVideoData(),A=c.mutedAutoplay&&(c.limitedPlaybackDurationInSeconds>0||c.endSeconds>0||c.mutedAutoplayDurationMode!==2);if((this.player.isEmbedsShortsMode()||this.K)&&!A)return!0;var J;var q=!!((c==null?0:g.qC(c))||(c==null?0:(J=c.suggestions)==null?0:J.length));q=!VQr(this.player)||q;c=c.FK;J=this.player.Rn();return q&&!c&&!J&&!A};
g.D.UD=function(){return this.endScreen.UD()};
g.D.Zn=function(){return this.UD()?this.endScreen.Wr():!1};
g.D.rF=function(){this.player.hm("endscreen");g.V5.prototype.rF.call(this)};
g.D.load=function(){var c=this.player.getVideoData();var A=c.transitionEndpointAtEndOfStream;if(A&&A.videoId){var J=this.player.rX().oL.get("heartbeat"),q=g.qC(c);!q||A.videoId!==q.videoId||c.D8?(this.player.J5(A.videoId,void 0,void 0,!0,!0,A),J&&J.ev("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),c=!0):c=!1}else c=!1;c||(g.V5.prototype.load.call(this),this.endScreen.show())};
g.D.unload=function(){g.V5.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.D.onCueRangeEnter=function(c){this.JC()&&(this.endScreen.created||this.endScreen.create(),c.getId()==="load"&&this.load())};
g.D.onCueRangeExit=function(c){c.getId()==="load"&&this.loaded&&this.unload()};
g.D.onVideoDataChange=function(){DAx(this);this.T&&NwJ(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.C?this.endScreen=new Ei(this.player):this.endScreen=new DU(this.player),g.U(this,this.endScreen),g.Sx(this.player,this.endScreen.element,4))};g.HO("endscreen",kcR);})(_yt_player);
