(function(g){var window=this;'use strict';var I_=function(c,A){g.t.call(this,{S:"button",QP:["ytp-miniplayer-expand-watch-page-button","ytp-button","ytp-miniplayer-button-top-left"],G:{title:"{{title}}","data-tooltip-target-id":"ytp-miniplayer-expand-watch-page-button","aria-keyshortcuts":"i","data-title-no-tooltip":"{{data-title-no-tooltip}}"},N:[{S:"svg",G:{height:"24px",version:"1.1",viewBox:"0 0 24 24",width:"24px"},N:[{S:"g",G:{fill:"none","fill-rule":"evenodd",stroke:"none","stroke-width":"1"},N:[{S:"g",G:{transform:"translate(12.000000, 12.000000) scale(-1, 1) translate(-12.000000, -12.000000) "},
N:[{S:"path",G:{d:"M19,19 L5,19 L5,5 L12,5 L12,3 L5,3 C3.89,3 3,3.9 3,5 L3,19 C3,20.1 3.89,21 5,21 L19,21 C20.1,21 21,20.1 21,19 L21,12 L19,12 L19,19 Z M14,3 L14,5 L17.59,5 L7.76,14.83 L9.17,16.24 L19,6.41 L19,10 L21,10 L21,3 L14,3 Z",fill:"#fff","fill-rule":"nonzero"}}]}]}]}]});this.J=c;this.listen("click",this.onClick,this);this.updateValue("title",g.Cu(c,"Expand","i"));this.update({"data-title-no-tooltip":"Expand"});this.addOnDisposeCallback(g.Lu(A.Da(),this.element))},DIx=function(c){g.t.call(this,
{S:"div",
V:"ytp-miniplayer-ui"});this.Y=!1;this.player=c;this.Z(c,"minimized",this.yR);this.Z(c,"onStateChange",this.w$x);this.Z(c,"documentpictureinpicturechange",this.FRy)},kxR=function(c,A){g.Rf(c.player.getRootNode(),"ytp-player-minimized",A)},gzV=function(c){g.V5.call(this,c);
this.K=new g.sM(this);this.C=new DIx(this.player);this.C.hide();g.Sx(this.player,this.C.element,4);c.isMinimized()&&(this.load(),g.Rf(c.getRootNode(),"ytp-player-minimized",!0))};
g.k(I_,g.t);I_.prototype.onClick=function(){this.J.gF("onExpandMiniplayer")};g.k(DIx,g.t);g.D=DIx.prototype;
g.D.show=function(){this.C=new g.Kt(this.V3,null,this);this.C.start();if(!this.Y){this.tooltip=new g.CT(this.player,this);g.U(this,this.tooltip);g.Sx(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.aZ=new g.tB(this.player);g.U(this,this.aZ);this.progressBar=new g.Uu(this.player,this);g.U(this,this.progressBar);g.Sx(this.player,this.progressBar.element,4);this.K=new g.t({S:"div",V:"ytp-miniplayer-scrim"});g.U(this,this.K);this.K.Sg(this.element);this.Z(this.K.element,"click",this.eC);
var c=new g.t({S:"button",QP:["ytp-miniplayer-close-button","ytp-button"],G:{"aria-label":"Close"},N:[g.L4()]});g.U(this,c);c.Sg(this.K.element);this.Z(c.element,"click",this.MM);c=new I_(this.player,this);g.U(this,c);c.Sg(this.K.element);this.j=new g.t({S:"div",V:"ytp-miniplayer-controls"});g.U(this,this.j);this.j.Sg(this.K.element);this.Z(this.j.element,"click",this.eC);var A=new g.t({S:"div",V:"ytp-miniplayer-button-container"});g.U(this,A);A.Sg(this.j.element);c=new g.t({S:"div",V:"ytp-miniplayer-play-button-container"});
g.U(this,c);c.Sg(this.j.element);var J=new g.t({S:"div",V:"ytp-miniplayer-button-container"});g.U(this,J);J.Sg(this.j.element);this.X=new g.IV(this.player,this,!1);g.U(this,this.X);this.X.Sg(A.element);A=new g.Z3(this.player,this);g.U(this,A);A.Sg(c.element);this.nextButton=new g.IV(this.player,this,!0);g.U(this,this.nextButton);this.nextButton.Sg(J.element);this.D=new g.D7(this.player,this,0);g.U(this,this.D);this.D.Sg(this.K.element);this.T=new g.t({S:"div",V:"ytp-miniplayer-buttons"});g.U(this,
this.T);g.Sx(this.player,this.T.element,4);c=new g.t({S:"button",QP:["ytp-miniplayer-close-button","ytp-button"],G:{"aria-label":"Close"},N:[g.L4()]});g.U(this,c);c.Sg(this.T.element);this.Z(c.element,"click",this.MM);c=new g.t({S:"button",QP:["ytp-miniplayer-replay-button","ytp-button"],G:{"aria-label":"Close"},N:[g.QX()]});g.U(this,c);c.Sg(this.T.element);this.Z(c.element,"click",this.GLJ);c=new I_(this.player,this);g.U(this,c);c.Sg(this.T.element);this.Z(this.player,"presentingplayerstatechange",
this.ZI);this.Z(this.player,"appresize",this.RJ);this.Z(this.player,"fullscreentoggled",this.RJ);this.RJ();this.Y=!0}this.player.getPlayerState()!==0&&g.t.prototype.show.call(this);this.progressBar.show();this.player.unloadModule("annotations_module")};
g.D.hide=function(){this.C&&(this.C.dispose(),this.C=void 0);g.t.prototype.hide.call(this);this.player.isMinimized()||(this.Y&&this.progressBar.hide(),this.player.loadModule("annotations_module"))};
g.D.rF=function(){this.C&&(this.C.dispose(),this.C=void 0);g.t.prototype.rF.call(this)};
g.D.MM=function(){this.player.W("kevlar_watch_while_v2")||this.player.stopVideo();this.player.gF("onCloseMiniplayer")};
g.D.GLJ=function(){this.player.playVideo()};
g.D.eC=function(c){if(c.target===this.K.element||c.target===this.j.element)this.player.getPlayerStateObject().isOrWillBePlaying()?this.player.pauseVideo():this.player.playVideo()};
g.D.yR=function(){kxR(this,this.player.isMinimized())};
g.D.FRy=function(){kxR(this,this.player.qj());g.Rf(this.player.getRootNode(),"ytp-player-document-picture-in-picture",this.player.qj())};
g.D.Gh=function(){this.progressBar.H6();this.D.H6()};
g.D.V3=function(){this.Gh();this.C&&this.C.start()};
g.D.ZI=function(c){g.e(c.state,32)&&this.tooltip.hide()};
g.D.RJ=function(){var c=this.player.i$().getPlayerSize().width;g.bi1(this.progressBar,0,c,!1);g.ff(this.progressBar)};
g.D.w$x=function(c){this.player.isMinimized()&&(c===0?this.hide():this.show())};
g.D.Da=function(){return this.tooltip};
g.D.bx=function(c,A,J,q,Y){var p=0,m=0,E=0,O=g.eL(c);q=A&&(g.jS(A,"ytp-prev-button")||g.jS(A,"ytp-next-button"));if(A){J=g.jS(A,"ytp-play-button");var T=g.jS(A,"ytp-miniplayer-expand-watch-page-button");q?p=E=12:J?(A=g.iP(A,this.element),E=A.x,p=A.y-12):T&&(E=g.jS(A,"ytp-miniplayer-button-top-left"),p=g.iP(A,this.element),A=g.eL(A),E?(E=8,p=p.y+40):(E=p.x-O.width+A.width,p=p.y-20))}else E=J-O.width/2,m=25+(Y||0);A=this.player.i$().getPlayerSize();Y=p+(Y||0);O=g.Fa(E,0,A.width-O.width-12);Y?(c.style.top=
Y+"px",c.style.bottom=""):(c.style.top="",c.style.bottom=m+"px");c.style.left=O+"px";m=g.jS(c,"ytp-preview");c.style.visibility=q&&m&&A.height<225?"hidden":""};g.k(gzV,g.V5);g.D=gzV.prototype;g.D.onVideoDataChange=function(){if(this.player.getVideoData()){var c=this.player.getVideoAspectRatio(),A=16/9;c=c>A+.1||c<A-.1;g.Rf(this.player.getRootNode(),"ytp-rounded-miniplayer-not-regular-wide-video",c)}};
g.D.create=function(){g.V5.prototype.create.call(this);this.K.Z(this.player,"videodatachange",this.onVideoDataChange);this.onVideoDataChange()};
g.D.A5=function(){return!1};
g.D.load=function(){this.player.hideControls();this.C.show()};
g.D.unload=function(){this.player.showControls();this.C.hide()};g.HO("miniplayer",gzV);})(_yt_player);
